### ISSUE TITLE
Is it posible to globaly define case insensitive mapping

### ISSUE THREAD

**Issue by MichalJana** [mikependon/RepoDb#1016]
Hi, is it possible to globally define case insensitive mappings in case where my database column names are lowercased (PostgreSQL) and my C# entity models are uppercased. I know i can use FluentMapper but i don't want to do it for each entity just for that. Thx.

**Comment by mikependon** [comment]
Though the column projections between the DB and the Models are case-insensitive, the SQL compositions are case-sensitive. Therefore, the answer to this is NO. There is no direct support (i.e.: flags) to this case within the library. However, you can do the trick below via reflection.

Let us say you have models below.

```csharp
public class Sales
{
	...
}

public class Product
{
	...
}
```

You have to create a method that does the things for you. (See below)

```csharp
private static void MapType<TEntity>()
{
	var properties = typeof(TEntity).GetProperties();
	foreach (var property in properties)
	{
		FluentMapper
			.Entity<TEntity>()
			.Column(property.Name, property.Name.ToLower());
	}
}
```

Then, call the method by passing your model as the target generic type. Below is the sample code implementation (simplified).

```csharp
public class Program
{
	public static void Main(string[] args)
	{
		RepoDb.PostgreSqlBootstrap.Initialize()
		MapAllTypes();
	}
	
	private static void MapTypes()
	{
		MapType<Sales>();
		MapType<Product>();
	}
	
	private void MapType<TEntity>()
	{
		var properties = typeof(TEntity).GetProperties();
		foreach (var property in properties)
		{
			FluentMapper
				.Entity<TEntity>()
				.Column(property.Name, property.Name.ToLower());
		}
	}
}
```

With this, you force the mapping to be lower-case all the time. This trick will only work if the fields/properties are equal (name-wise).

Note: It is important to take note that you should only call the `FieldCache.Get<TEntity>` and `PropertyCache.Get<TEntity>` after the mapping initializations so the cachers would cache the valid mappings.
