### ISSUE TITLE
Bug: RepoDb.SqlServer v1.1.5 breaks System.Data.SqlClient support

### ISSUE THREAD

**Issue by w5l** [mikependon/RepoDb#1034]
### Bug Description

After updating the `RepoDb.SqlServer` package reference from v1.1.4 (which worked fine) to v1.1.5, I get errors about "no database helper mapping found", as if the bootstrapper has not been run. No code was changed, only the package reference.

**Exception Message:**

> There is no database helper mapping found for `'System.Data.SqlClient.SqlConnection'`. Make sure to install the correct extension library and call the bootstrapper method. You can also visit the library's installation page (https://repodb.net/tutorial/installation).

### Solution

I checked `RepoDb.SqlServerBootstrap` at the time of the exception, and `IsInitialized` is `true`, so this is not a case of the initializer not running. Just in case, I tried, and adding an explicit call to `RepoDb.SqlServerBootstrap.Initialize()`, but that did not change anything.

On a hunch, I changed package dependencies from `System.Data.SqlClient` to `Microsoft.Data.SqlClient` and return a `Microsoft.Data.SqlClient.SqlConnection`. With that the errors are gone.

A little digging in the recent changes to RepoDB brings up these:

- https://github.com/mikependon/RepoDb/issues/857
- https://github.com/mikependon/RepoDB/pull/931

The [issue](https://github.com/mikependon/RepoDb/issues/857#issuecomment-907635978) mentions:

> We are afraid that we might affect some of the users if we are to remove this without the proper acceptance from the community.

**Suggestion**

I don't mind support for `System.Data.SqlClient` being dropped. However it is strange that this is done without a clear mention in the release notes, and without a major version change. That leads me to believe this might be an unintended side-effect.

When this breaking change is on purpose, please bump the major package version, and put a clear message in the the changelog.

**Library Version:**

Example: RepoDb  v1.12.10 and RepoDb.SqlServer v1.1.5

**Comment by mikependon** [comment]
It is expected and this should be very minor to change on the solution.

On the recent release, we have removed the support to SDS and we will be more focusing on the MDS. Can you now start using the new MDS?

SDS = System.Data.SqlClient
MDS = Microsoft.Data.SqlClient

**Comment by mikependon** [comment]
Just to give you more insights, this has been Tweeted AFAIK and we even placed a special [section](https://github.com/mikependon/RepoDB#systemdatasqlclient) into our main README page.

**Comment by w5l** [comment]
Thanks for the reply, as written this is not a blocking issue at all. I can revert to a previous version of `RepoDB.SQLServier` or update the software to use `MDS` instead of `SDS`. No need for code changes to `RepoDB`.

The mentioned section in the README is interesting, especially since it is 5 months old. It's been working fine with the regular bootstrapper call as advertised in [Get Started for SQL Server](https://repodb.net/tutorial/get-started-sqlserver).

I would suggest to add the extra `SDS` setup instructions to that page. It is what the error links to, where searches for the error message lead, and what StackOverflow answers link to as well, thus the most likely place to help people.

> It is expected and this should be very minor to change on the solution.

In that case, we can close this issue, though I still find it wrong that a breaking change in behavior (however small and easily fixed) is hidden in a "patch" [semver](https://semver.org/) bump.

**Comment by mikependon** [comment]
Closing this issue now. Thanks

**Comment by mikependon** [comment]
FYI: We have updated our [installation](https://repodb.net/tutorial/installation) page as per this request.
