### ISSUE TITLE
"The certificate chain was issued by an authority that is not trusted" exception after update to 1.12.10

### ISSUE THREAD

**Issue by Simon-Carr** [mikependon/RepoDb#1039]
RepoDb 1.12.10
RepoDb.SqlServer 1.1.5

After upgrading to these versions all databases connections fail on open with the following exception:

_Microsoft.Data.SqlClient.SqlException
"A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)"_

the issue seems to be in RepoDb.SqlServer 1.1.5 as I am able to update to RepoDb.SqlServer 1.12.10 without issue.

Example code (unchanged)
`using IDbConnection cnn = new SqlConnection(_connectionStrings.Connection);`
       `     cnn.Open();`
        `    using var multi =`
               ` await cnn.ExecuteQueryMultipleAsync(request.SprocName, request.Parameters, CommandType.StoredProcedure,`
                `    cancellationToken: cancellationToken);`
          `  var subs = await multi.ExtractAsync<LoadSubscriptionDto>();`
       `     var providers = await multi.ExtractAsync<ProviderDto>();`
    `        var products = await multi.ExtractAsync<LoadSubscriptionProviderProductDto>();`
          `  var discounts = await multi.ExtractAsync<SubscriptionProviderProductDiscountDto>()`

**Comment by dendism** [comment]
it's a breaking change in the Microsoft.Data.SqlClient library. Just put Encrypt=false to your connection string.

**Comment by mikependon** [comment]
...and also the [Trust Server Certificate](https://github.com/mikependon/RepoDB#trust-server-certificate) section of our README.

**Comment by Simon-Carr** [comment]
Ah great. thanks for the help
