### ISSUE TITLE
Question: No coersion operator defined between Nullable System.Int64 and System.Boolean

### ISSUE THREAD

**Issue by JanBrandenburger** [mikependon/RepoDb#1092]
Hi together,
I have a problem using RepoDB with SQLite.

### My SQLite Table (interesting part is marked bold):
CREATE TABLE "Artikel" (
	"UniqID"	TEXT,
	"ArtikelNr"	TEXT,
	"EAN1"	TEXT,
	"EAN2"	TEXT,
	"EAN3"	TEXT,
	"BestandIst"	REAL NOT NULL DEFAULT 0,
	"BestandGezaehlt"	REAL NOT NULL DEFAULT 0,
	"Bezeichnung"	TEXT NOT NULL,
	"Warengruppe"	TEXT NOT NULL,
	"Zusatz1"	TEXT,
	"Zusatz2"	TEXT,
	"Zusatz3"	TEXT,
	**"LagerverwaltungAktiv"	INTEGER NOT NULL DEFAULT 0,**
	"LetzteZaehlung"	TEXT,
	"VKBrutto1"	REAL,
	PRIMARY KEY("UniqID")
)

### My C# Model (interesting part is marked bold):
 public class ArtikelSqlite
    {
        public string UniqID { get; set; }
        public string ArtikelNr { get; set; }
        public string EAN1 { get; set; }
        public string EAN2 { get; set; }
        public string EAN3 { get; set; }
        public double BestandIst { get; set; }
        public double BestandGezaehlt { get; set; }
        public string Bezeichnung { get; set; }
        public string Warengruppe { get; set; }
        public string Zusatz1 { get; set; }
        public string Zusatz2 { get; set; }
        public string Zusatz3 { get; set; }
        **[PropertyHandler(typeof(BitSqlLiteConversionHandler))]**
        **public bool LagerverwaltungAktiv { get; set; }**
        [PropertyHandler(typeof(DateTimeConversionHandler))]
        public DateTime? LetzteZaehlung { get; set; }
        public double VKBrutto1 { get; set; }
    }

### The BitSqlLiteConversionHandler
```
public class BitSqlLiteConversionHandler : IPropertyHandler<Int64, bool>
    {
        public bool Get(Int64 input, ClassProperty property)
        {
            return Convert.ToBoolean(input);
        }

        public Int64 Set(bool input, ClassProperty property)
        {
            if (input)
            {
                return 1;
            }
            else
            {
                return 0;
            }
//I tried also:
//return Convert.ToUInt64(input);

        }
    }
```

### When I try to insert data with the following code, I get the error:

```
public int AddArtikelListe(List<ArtikelSqlite> artikel)
        {
            using (var connection = ConnectionManager.CreateSqliteConnection())
            {
                return connection.InsertAll(artikel);
            }
        }
```

_No coersion operator defined between Nullable System.Int64 and System.Boolean_

Interesting for me is:

When loading data from the table, the "Get-Method" of the BitSqlLiteConversionHandler  is reached.
But when try to insert data the "Set-Method" of the BitSqlLiteConversionHandler never reached.
Also interesting: the column is set to "NOT NULL" but in the error is written "Nullable System.Int64".

Have anyone any idea, how to fix this?

Thank you very much!

Best from Germany, 
Jan

**Comment by mikependon** [comment]
The master branch has been updated and the code below is working there at least. Would it be possible for you to utilize the latest release [RepoDb.SQLite.System](https://www.nuget.org/packages/RepoDb.SQLite.System/1.13.0-alpha1)?

```csharp
[TestMethod]
public void TestTest()
{
	using (var connection = new SQLiteConnection("Data Source=:memory:;"))
	{
		var schema = @"CREATE TABLE ""ArtikelSqlite"" (
			""UniqID"" TEXT,
			""ArtikelNr"" TEXT,
			""EAN1"" TEXT,
			""EAN2"" TEXT,
			""EAN3"" TEXT,
			""BestandIst"" REAL NOT NULL DEFAULT 0,
			""BestandGezaehlt"" REAL NOT NULL DEFAULT 0,
			""Bezeichnung"" TEXT NOT NULL,
			""Warengruppe"" TEXT NOT NULL,
			""Zusatz1"" TEXT,
			""Zusatz2"" TEXT,
			""Zusatz3"" TEXT,
			""LagerverwaltungAktiv"" INTEGER NOT NULL DEFAULT 0,
			""LetzteZaehlung"" TEXT,
			""VKBrutto1"" REAL,
			PRIMARY KEY(""UniqID"")
			)";
		connection.ExecuteNonQuery(schema);
		var artikel = new ArtikelSqlite()
		{
			ArtikelNr = "ArtikelNr",
			EAN1 = "EAN1",
			EAN2 = "EAN2",
			BestandIst = 1,
			BestandGezaehlt = 2,
			Bezeichnung = "Bezeichnung",
			Warengruppe = "Warengruppe",
			Zusatz1 = "Zusatz1",
			Zusatz2 = "Zusatz2",
			Zusatz3 = "Zusatz3",
			LagerverwaltungAktiv = true,
			LetzteZaehlung = DateTime.UtcNow,
			VKBrutto1 = 1
		};

		var data = new List<ArtikelSqlite>() { artikel };
		connection.InsertAll(data);
	}
}
```

Note: You will notice the changes on the signature of the `IPropertyHandler` method. We made an update to this just for this latest release.

**Comment by JanBrandenburger** [comment]
Hi Mike,
thank you very much. I tested the alpha release and it works.

Best, 
Jan
