### ISSUE TITLE
DirectionalQueryField with string output in stored procedure

### ISSUE THREAD

**Issue by Trobeloo** [mikependon/RepoDb#1117]
Hello,

Using RepoDb.SqlServer 1.13.0

I have an SQL Server Stored proc with the following signature:
[Create] (@gmnv varchar(20) OUTPUT)

I try to call the SP like this
var GMNV = new DirectionalQueryField("gmnv", ParameterDirection.Input, 20, DbType.AnsiStringFixedLength);
var param = new { GMNV };
var result1 = Connection.ExecuteNonQuery("Create", param, commandType: CommandType.StoredProcedure);

It doesn't work and I get an exception:
No mapping exists from object type RepoDb.DirectionalQueryField to a known managed provider native type.

I tried with no luck:
var GMNV = new DirectionalQueryField("gmnv", ParameterDirection.Input);
var GMNV = new DirectionalQueryField("gmnv", ParameterDirection.Input,20,  DbType.String);

It was working with previous Repodb version like this:
var GMNV = new DirectionalQueryField("gmnv", typeof(string), 20, ParameterDirection.InputOutput);

What I am doing wrong?

BTW in that page of the doc https://repodb.net/class/directionalqueryfield
This doesn't compile
var output = new DirectionalQueryField("Output", "Whatever", 256, ParamDirection.InputOutput); // Type is TEXT

**Comment by mikependon** [comment]
Have you tried with InputOutput or just Output?

**Comment by Trobeloo** [comment]
Sory my samples were wrong ParameterDirection.input is of course incorrect. 
I have tried both InputOutput and Output with same error.
var GMNV = new DirectionalQueryField("gmnv", ParameterDirection.InputOutput, 20, DbType.String);

**Comment by Trobeloo** [comment]
Solved problem was here
var param = new{ GMNV }; instead of var param = **new[]** { GMNV };
