### ISSUE TITLE
Enhancement: Follow Npgsql connvention for DateTime and DateTimeOffset

### ISSUE THREAD

**Issue by anpin** [mikependon/RepoDb#1126]
### Describe the enhancement
Hello @mertkokusen , following our conversation on Matrix I'm opening an issue here.  
I would love `RepoDb` to follow `Npgsql` convention for `DateTime` and `DateTimeOffset` as in [here (lines 62-83)](https://github.com/npgsql/npgsql/blob/main/src/Npgsql/TypeMapping/BuiltInTypeHandlerResolver.cs), meaning `DateTime ` <-> `timestamp`; `DateTimeOffset` <-> `timestamptz`; `DateOnly` <->  `date` etc
Currently calling `connection.Insert<TimedData, DateTime>(entity)` renders into `INSERT INTO "public"."timeddata" ( "Timestamp", "ParentId", "Value" ) VALUES ( $1, $2, $3 ) RETURNING CAST("Timestamp" AS DATE) AS "Result"  Parameters: [12/22/2022 13:20:34, 2247d283-410c-4abb-a3ae-f9b12e3f09cf, 1]` and the result of such query is lacking time precision e.g. `2022-12-22T00:00:00.0000000` which is hardcoded around [here](https://github.com/mikependon/RepoDB/blob/master/RepoDb.PostgreSql/RepoDb.PostgreSql/Resolvers/DbTypeToPostgreSqlStringNameResolver.cs)

**Comment by xperiandri** [comment]
Why can I have Npgsql failing to insert `DateTimeOffset` to `TimestampTz` because it tries to insert it as a string?
What do I do wrong?

**Comment by xperiandri** [comment]
Same thing happens if I try inserting `DateOnly`

**Comment by mikependon** [comment]
Can you share the error?
