### ISSUE TITLE
BaseRepository does not work with generic TDbConnection.

### ISSUE THREAD

**Issue by plsft** [mikependon/RepoDb#1144]
I'm trying to add RDB to my app  but I can't get it to compile. The BaseRepository (from the UnitOfWork / GenericRepository docs) will not accept a DbConnection of type TDbConnection, rather it seems to require SqlConnection.

![Screenshot 2023-04-10 123221](https://user-images.githubusercontent.com/13736152/230946972-0ed8f83c-4d89-45f4-a4e5-71954f464f87.png)

```C#
public class EntityRepository<TEntity, TDbConnection> : BaseRepository<TEntity, TDbConnection>, IRepository<TEntity, TDbConnection>
    where TEntity : class
    where TDbConnection : IDbConnection
{
    private IUnitOfWork<DbConnection> _unitOfWork;

    public EntityRepository(IOptions<AppSettings> options)
        : base(options.Value.ConnectionString) { }

    public void Attach(IUnitOfWork<DbConnection> unitOfWork) =>
        _unitOfWork = unitOfWork;

    public TResult Save<TResult>(TEntity entity) =>
        Insert<TResult>(entity,
            transaction: _unitOfWork.Transaction);

    public int SaveAll(IEnumerable<TEntity> entities) =>
        InsertAll(entities,
            transaction: _unitOfWork.Transaction);

    public int Delete(object id) =>
        Delete(id,
            transaction: _unitOfWork.Transaction);

    public TResult Merge<TResult>(TEntity entity) =>
        Merge<TResult>(entity,
            transaction: _unitOfWork?.Transaction);

    public TEntity Query(object id) =>
        Query(id,
            transaction: _unitOfWork?.Transaction)?.FirstOrDefault();

    public int Update(TEntity entity) =>
        Update(entity,
            transaction: _unitOfWork?.Transaction);
}
```

**Comment by mikependon** [comment]
Can you use DbConnection instead of IDbConnection? Here is the [restriction](https://github.com/mikependon/RepoDB/blob/8213ca425f2d3d4f83adc51bf507224c20206e82/RepoDb.Core/RepoDb/BaseRepository.cs#L19).

**Comment by plsft** [comment]
thanks for the quick response @mikependon 

![Screenshot 2023-04-10 124303](https://user-images.githubusercontent.com/13736152/230948846-020ecb21-2b65-4ba5-9109-7b8c14adad34.png)

Still giving me an error. I pulled this ref code from the docs here:

https://repodb.net/reference/output/unitofwork

Under "Repositories" 

BaseResponsitory won't accept DbConnection here.  Must be non-abstract with public .ctor

**Comment by mikependon** [comment]
We are afraid to say that the documentation is not updated since the latest PR from the community, we can update that soon. In anyway, would you be able to follow the BaseRepository construct? I mean, can you also add the new() keyword? Otherwise, we will try to see how to rectify your problem later.

**Comment by plsft** [comment]
Thanks @mikependon -- Will do, but I'm not clear on where to new() in this construct?

**Comment by plsft** [comment]
![image](https://user-images.githubusercontent.com/13736152/231544918-0466226b-82c2-4297-bfc1-eea7dbd9880a.png)

This works fine. I created a GenericDb and GenericDbConnection.

**Comment by plsft** [comment]
Direct Use:
![image](https://user-images.githubusercontent.com/13736152/231545214-a4f3bc74-4c64-4cfc-a9a6-6f26aa9bd43d.png)

DI Use:

![image](https://user-images.githubusercontent.com/13736152/231545340-61688d82-d73d-4fc5-a710-ff3c879526be.png)

![image](https://user-images.githubusercontent.com/13736152/231545484-82b41c10-1065-4302-8b05-424479c748ee.png)

DI via Business Logic Service

![image](https://user-images.githubusercontent.com/13736152/231545872-29ed2032-9186-4b84-884b-03f1431d6e80.png)

**Comment by mikependon** [comment]
Hey @plsft , we are glad that you made it work. For your reference, we have also created this simple project for you based on the documentation. Note: We renamed the SalesManager to SalesService.

[RepoDbUnitOfWorkProject.zip](https://github.com/mikependon/RepoDB/files/11215632/RepoDbUnitOfWorkProject.zip)

**Comment by plsft** [comment]
@mikependon thanks for the reference project! I'll review and see how I can use it. really impressed with RDB so far. I've used PetaPoco and NPoco for years, Massive/MightOrm too, because I felt EntityFx was too bloated with too much ceremony. The performance of RDB and the bulk import and merge features are killer. great work!

**Comment by mikependon** [comment]
Thanks mate. Please do not hesitate to revert if you have questions and need support.
