### ISSUE TITLE
the incoming request has too many parameters

### ISSUE THREAD

**Issue by sipi41** [mikependon/RepoDb#1147]
### Bug Description

Dear friends, I want to first say "thank you" for such amazing thing, I'm new to this so I hope not doing something wrong, let me try to explain... I found your product because I'll be doing some bulk update from EF, so far I been playing with this, reading the docs and just playing around, so far so good... then I found what I think is a bug... I created a simple table, with 3 fields, id, number and winner.  Then I'm generating 50k items, then I tried to use the **InsertAllAsync** method (I know it's not the best way to do this but just trying), I understood by the docs, that I can't put more than 2100 (I'm not sure if batch means total # of entities or properties with values), so I decided to try 1000, my understanding is that I'll be inserting batches of 1000, for a total of 50 batches = 50k records... the problem is, I'm getting an error... thank you for any help you may bring.

**Exception Message:**

```csharp

Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__209_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at RepoDb.DbConnectionExtension.InsertAllAsyncInternalBase[TEntity](IDbConnection connection, String tableName, IEnumerable`1 entities, Int32 batchSize, IEnumerable`1 fields, String hints, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\GuillermoPerez\Projects\ITT_OneTeam\Touch Plan Console API Importer\TouchPlanConsoleImporter\Program.cs:line 29
   at Program.<Main>(String[] args)
ClientConnectionId:e3ae8eba-afc2-42f2-94e5-96d6c245b28d
Error Number:8003,State:1,Class:16

```

**Schema and Model:**

Please share to us the schema of the table (not actual) that could help us replicate the issue if necessary.

```csharp

using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using RepoDb;
using TouchPlanConsoleImporter.Data;
using TouchPlanConsoleImporter.Models;

GlobalConfiguration
    .Setup()
    .UseSqlServer();

using TSMC_ODS_DbContext dbContext = new TSMC_ODS_DbContext();

async Task<IEnumerable<WinningNumber>> GenerateParticipants(int HowMany)
{
    await Console.Out.WriteLineAsync($"generating {HowMany} participants...");
    return Enumerable.Range(1050, 1050 + HowMany).Select(s => new WinningNumber { Number = (uint)s, Winner = false });
}



using SqlConnection sqlConnection = (SqlConnection)dbContext.Database.GetDbConnection();

Console.WriteLine(DateTime.Now.ToString("mm:ss.fff"));
var generatedList = await GenerateParticipants(50000);
Console.WriteLine(DateTime.Now.ToString("mm:ss.fff"));

await sqlConnection.InsertAllAsync(entities: generatedList, batchSize: 1500);

Console.WriteLine(DateTime.Now.ToString("mm:ss.fff"));

```

And also the model that corresponds the schema.

```csharp

namespace TouchPlanConsoleImporter.Models
{
    [Table("WinningNumbers")]
    public class WinningNumber
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)] 
        public int Id { get; set; }
        [Required]
        public uint Number { get; set; }
        [Required]
        public bool Winner { get; set; } = false;
    }
}


```

**Library Version:**

1.13.1

**Comment by cajuncoding** [comment]
That error is not a bug…it’s a limitation of SQL Seever where only 2100 parameters can be sent in a single query…by parameters it’s referring to arguments that begin with `@`. 
 
RepoDB is automating that for you and using parameters, for every field value for every entity/record, just as it should to avoid SQL injection risks! However it does not do a bounds check so your just passing in too much data into that method….every field on every record is resulting in a variable/param.

You should look into the BulkInsert API (RepoDB provides this also) as a much more reliable way to send large amounts of data in the fastest way possible…InsertAll is for smaller batches of dozens of records…if you have hundreds or thousands then BulkInsert is more appropriate.

**Comment by sipi41** [comment]
thank you @cajuncoding! like I said, I was monkeying with it... I want to point out that the mention was not "parameters" but "batch", I thought it was a record, an entry, not a single field value.  Thank you for your good advise! :-)

**Comment by mikependon** [comment]
Thanks @cajuncoding. @sipi41 yes, please the real [Bulk Operation](https://repodb.net/feature/bulkoperations/sqlserver) if you have such requirement.
