### ISSUE TITLE
Using Memory Cache

### ISSUE THREAD

**Issue by rubenalves** [mikependon/RepoDb#1173]
Is there any examples of using memory cache ?

I see this example on the documentation but it does not say how to implement the Cache object.

`var cache = CacheFactory.GetMemoryCache();

using (var connection = new SqlConnection(connectionString))
{
    var products = connection.QueryAll<Product>(cacheKey: "products", cache: cache);
}`

**Comment by mikependon** [comment]
The [MemoryCache](https://repodb.net/class/memorycache) page should help.

**Comment by rubenalves** [comment]
Got it. Thanks.
