### ISSUE TITLE
Bulk Insert

### ISSUE THREAD

**Issue by tabishfriend** [mikependon/RepoDB#134]
Currently, Bulk insert using DbDataReader return -1 and it doesn't differentiate between whether it's been successful or not. Instead of returning -1, Is it possible for it to return True or False?

**Comment by mikependon** [comment]
Bulk-insert truly returns -1, as we cannot identity whether the records has been successfully bulk-inserted. We only do single call (fire and forget).

In anyway, I will weigh this one and think about whether to enable this or not.

Documentation: https://repodb.readthedocs.io/en/latest/pages/connection.html#bulkinsert

**Comment by mikependon** [comment]
The fix has been introduced and checked in to the master. This will be available in the next release > v1.9.1.
