### ISSUE TITLE
Set identity

### ISSUE THREAD

**Issue by tabishfriend** [mikependon/RepoDB#135]
Currently there is no function to set Identity ON or OFF on certain table(s). It will be good to have a function for it.

**Comment by mikependon** [comment]
Hi @tabishfriend , are you referring to something like this?

     using (var connection = new SqlConnection(connectionString))
     {
           connection.AllowInsertOnIdentity<TEntity>();
     }

**Comment by tabishfriend** [comment]
Hi @mikependon , exactly but it will be good to have more simple and flexible. something like that 

```
 using (var connection = new SqlConnection(connectionString))
 {
       connection.SetIdentity("dbo.Student",true);

       connection.SetIdentity("dbo.Student",false);

**OR**

      connection.SetIdentity("dbo.Class,dbo.Student",true);

       connection.SetIdentity("dbo.Class,dbo.Student",false);

 }
```

**Comment by mikependon** [comment]
The method name `SetIdentity` does not have a valid context on its purpose. Though I understand what you mean. This is a DB Provider specific operation, and if I have to introduce this one, then the library is being dragged to be limited to a SQL Server DB Provider (in specific).

Alternatively for SQL Server, you can do something like this:

     using (var connection = new SqlConnection(connectionString))
     {
          connection.ExecuteNonQuery("SET IDENTITY_INSERT [dbo].[TableName] ON;");
     }

     using (var connection = new SqlConnection(connectionString))
     {
          connection.ExecuteNonQuery("SET IDENTITY_INSERT [dbo].[TableName] OFF;");
     }

This is very doable! Thank you for this, we will see how should I handle this based on community feedback.

**Comment by mikependon** [comment]
Will not doing this as it seems to be a provider specific calls.
