### ISSUE TITLE
Query is defaulting to TOP instead of using PK

### ISSUE THREAD

**Issue by rdagumampan** [mikependon/RepoDB#15]
When executing repository.Query, the resulting query is using TOP instead of using the PK of the table.

These two approach returns 2 different rows when we expect the same row.

```
var repository = new DbRepository<SqlConnection>(Constants.TestDatabase);
var customer = repository.Query<Customer>(1).FirstOrDefault();

```
```
var customer = repository.Query<Customer>(new { Id = 1 }).FirstOrDefault();
```

**Comment by mikependon** [comment]
Thank you for this. Fixed as master just now.
