### ISSUE TITLE
Consider creating .NET Type to DBType mapping

### ISSUE THREAD

**Issue by rdagumampan** [mikependon/RepoDB#16]
When parameters are created we rely on the ADO.NET facility to derive the right db types. In cases the type is not supported, we can use `TypeMap` to support it. This works so far but maybe not the best approach for the ff reasons:

- we may get inconsistent precision like when in DB its real but in model its double
- there might be overhead given we use variant types
- we may lose data like in char and nvarchar

**Comment by mikependon** [comment]
Fixed at master just now.
