### ISSUE TITLE
Support BLOB data types

### ISSUE THREAD

**Issue by rdagumampan** [mikependon/RepoDB#19]
Test shows the BLOB types are currently not support. The IL generator used to fast-read the datareader are emitting empty byte arrays for data  columns that are Image, VarBinary or VarBinaryMax. Insert works fine but repository cannot read the byte arrays back.

Integration tests available here https://github.com/rdagumampan/RepoDb

```
[Test]
public void BlobTypeMap()
{
	//arrange
	var resourceName = "RepoDb.IntegrationTests.Setup.hello-world.png";
	var baseByteData = ExtractResource(resourceName);
	
	var fixtureData = new Models.TypeMapBlob
	{
		image_column = baseByteData,
		varbinary_column = baseByteData,
		varbinarymax_column = baseByteData
	};

	//act
	var sut = new DbRepository<SqlConnection>(Constants.TestDatabase);
	var returnedId = sut.Insert(fixtureData);

	//TODO: support guid primary key

	//assert
	var saveData = sut.Query<Models.TypeMapBlob>(top: 1).FirstOrDefault();
	saveData.ShouldNotBeNull();
	saveData.image_column.SequenceEqual(fixtureData.image_column).ShouldBe(true);
	saveData.varbinary_column.SequenceEqual(fixtureData.varbinary_column).ShouldBe(true);
	saveData.varbinarymax_column.SequenceEqual(fixtureData.varbinarymax_column).ShouldBe(true);
}
```

```
System.EntryPointNotFoundException : Entry point was not found.
   at System.Collections.Generic.IEnumerable`1.GetEnumerator()
   at System.Linq.Enumerable.SequenceEqual[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at RepoDb.IntegrationTests.TestBlobDataTypeMapping.BlobTypeMap() in C:\play\_forked\RepoDb\RepoDb\RepoDb.Tests\RepoDb.IntegrationTests\TestBlobDataTypeMapping.cs:line 72

```

**Comment by mikependon** [comment]
Any data type PrimaryKey is supported by the library. The returnedId variable must contain the newly added record's PrimaryKey (SCOPE_IDENTITY() for INT IDENTITY and GUID for UNIQUEIDENTIFIER).

**Comment by rdagumampan** [comment]
The issue here is not the PK but the support for BLOB data types. Integration tests shows that BINARY, VARBINARY and IMAGE are not supported by readers based on IL EMIT commands.

Further, DATETIMEOFFSET AND Spatial types like GEOGRAPHY AND GEOMETRY are not supported also.

**Comment by mikependon** [comment]
Looking at this now.

**Comment by mikependon** [comment]
Fixed at the version greater than "beta5". Introduced the [TypeMap] interface for some special case to support the property-level type mapping. Also requested at (reddit).
- Supported the BLOB Data Type 
- Supported the Binary Data Type

The DataTimeOffset is not yet supported for now.

For the Spatial types like GEOGRAPHY ang GEOMETRY, I will try do create an Integration Test.

**Comment by mikependon** [comment]
Will close this issue. The GEOGRAPHY and GEOMETRY will be supported at versions greater than "v1.2.0-beta5"

**Comment by mikependon** [comment]
Creating a separate issue to support the DateTimeOffset type.
