### ISSUE TITLE
Support for SQLite

### ISSUE THREAD

**Issue by TechInterMezzo** [mikependon/RepoDB#259]
This looks like a promising ORM library.
What would be needed to support SQLite?
Which classes should be added or interfaces inherited?

**Comment by mikependon** [comment]
@TechInterMezzo , thank you. By default, it supports all databases if you are using the RawSql extended methods (ie: ExecuteQuery, ExecuteNonQuery, ExecuteScalar, ExecuteReader). It means that SQLite is supported.

But, if you intend to make it more fluent and support the method-based call, then to be specific, we need to create the following.

- **SqLiteStatementBuilder**: a class that implements IStatementBuilder. A sample for SQL Server (https://github.com/mikependon/RepoDb/blob/master/RepoDb/RepoDb/StatementBuilders/SqlStatementBuilder.cs)
- **SqLiteDbHelper**: a class that implements the IDbHelper. A sample for SQL Server (https://github.com/mikependon/RepoDb/blob/master/RepoDb/RepoDb/DbHelpers/SqlDbHelper.cs)
- **SqlLiteOperationProvider**: a class that implements the IDbOperationProvier. A sample for SQL Server (https://github.com/mikependon/RepoDb/blob/master/RepoDb/RepoDb/DbOperationProviders/SqlServer/BulkInsert.cs).

Once everything is done, we can just simply call the mapper like below.

- StatementBuilderMapper.Add(typeof(SqLiteConnection), new SqLiteStatementBuilder());
- DbHelperMapper.Add(typeof(SqLiteConnection), new SqLiteDbHelper());
- DbOperationProviderMapper.Add(typeof(SqLiteConnection), new SqLiteDbOperationProvider());

**Comment by mikependon** [comment]
The extension is now being written. Will update this ticket from time-to-time.

**Comment by mikependon** [comment]
@TechInterMezzo - the full support to SqLite has been published today. Below is the thing you need to do to make it work on your end.

1. Install the RepoDb.SqLite via PMC (Install-Package RepoDb.SqLite).
2. Call the Bootstrap.Initialize() method.
`Bootstrap.Initialize();`
3. Wrapped everything in the SQLiteConnection object. It has inherited all the features/operations of the RepoDb.Core.

I will be closing this one soon. But please feel free to revert if you have questions.

**More Code Samples:**

	using (var connection = new SQLiteConnection(""))
	{
		// Average/AverageAll
		var result = connection.Average<TEntity>(e => e.Field, e => e.Field == "Value");
		var result = connection.AverageAll<TEntity>(e => e.Field);
		
		// Count/CountAll
		var result = connection.Count<TEntity>(e => e.Field == "Value");
		var result = connection.CountAll<TEntity>();

		// BatchQuery
		var data = connection.BatchQuery<TEntity>(e => e.Field == "Value", page: 0, rows: 1000, OrderField.Ascending<TEntity>(e => e.Id).AsEnumerable());
		
		// Delete/DeleteAll
		var result = connection.Delete<TEntity>(1); // Auto-detected Id
		var result = connection.Delete<TEntity>(e => e.Field == "Value");
		var result = connection.DeleteAll<TEntity>();
		
		// Delete/DeleteAll
		var result = connection.Exists<TEntity>(1); // Auto-detected Id
		var result = connection.Exists<TEntity>(e => e.Field == "Value");
		
		// Insert/InsertAll
		var result = connection.Insert<TEntity>(entity);
		var result = connection.InsertAll<TEntity>(entities);
		
		// Max/MaxAll
		var result = connection.Max<TEntity>(e => e.Field, e => e.Field == "Value");
		var result = connection.MaxAll<TEntity>(e => e.Field);
		
		// Merge/MergeAll
		var result = connection.Merge<TEntity>(entity);
		var result = connection.MergeAll<TEntity>(entities);
		
		// Min/MinAll
		var result = connection.Min<TEntity>(e => e.Field, e => e.Field == "Value");
		var result = connection.MinAll<TEntity>(e => e.Field);
		
		// Query/QueryAll
		var result = connection.Query<TEntity>(1); // Auto-detected Id
		var result = connection.Query<TEntity>(e => e.Field == "Value");
		var result = connection.QueryAll<TEntity>();
		
		// QueryMultiple
		var result = connection.Query<T1, T2>(e => e.Field == "Value", e => e.Field == "Value");
		var result = connection.Query<T1, T2, T3, T4, T5, T6, T7>(e => e.Field == "Value", e => e.Field == "Value", etc etc);
		
		// Sum/SumAll
		var result = connection.Sum<TEntity>(e => e.Field, e => e.Field == "Value");
		var result = connection.SumAll<TEntity>(e => e.Field);
		
		// Update/UpdateAll
		var result = connection.Insert<TEntity>(entity);
		var result = connection.InsertAll<TEntity>(entities);
	}
