### ISSUE TITLE
RepoDB hangs at warmup in RawDataAccessBencher. Starting with 1.9.6

### ISSUE THREAD

**Issue by FransBouma** [mikependon/RepoDB#266]
Hi,

I migrated the reference to RepoDB from 1.9.5 to 1.9.8. However when I ran the benchmarks (on .net core or .net framework, no difference) the two benchers of RepoDB hung at warmup. Reverting back to 1.9.5 solved it. Migrating to 1.9.6 also shows this issue so it's a change made in 1.9.6 that causes this. Not sure what's going on, I'll leave that to you :)

**Comment by mikependon** [comment]
Thank you Franz. I will look at it and will update you soon. I will just issue a PR on RDAB instead, once this issue is isolated.

**Comment by mikependon** [comment]
Changes checked-in to the master branch. The fix is available at version > v1.9.8.
Reason: Used yield operation during the table schema extraction, that slow down the process during the iteration and the composition of the command text for (Packed Operations - InsertAll, MergeAll, UpdateAll).
