### ISSUE TITLE
Login fails when using a connection string that doesnt use Trusted_Connection=True

### ISSUE THREAD

**Issue by Wolfteam** [mikependon/RepoDB#267]
Hiho, im not sure if this is a bug, but im trying to query some data and it works with the following connection string:
server=.;database=Students;uid=sa;password=12345;Trusted_Connection=True;

But if i try to connect using the following one:
server=.;database=Students;uid=sa;password=12345;

it throws an exception saying that the login failed for user 'sa'

I tried using pure ado.net and it works for both cases D:

            try
            {
                using (var connection = new SqlConnection())
                {
                    connection.ConnectionString = "server=.;database=Students;uid=sa;password=12345;";
                    //connection.Open();

                    //var cmd = new SqlCommand("select count(*) from students");
                    //cmd.Connection = connection;
                    //var reader = cmd.ExecuteReader();
                    //while (reader.Read())
                    //{
                    //    var something = reader[0].ToString();
                    //}
                    connection.EnsureOpen();

                    var query = connection.QueryAll<StudentQuery>();
                    var students = query.ToList();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

    [Map("Students")]
    public class StudentQuery
    {
        [Primary]
        public int ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public DateTime CreatedAt { get; set; }
    }

**Comment by mikependon** [comment]
Refer to #62, almost related. The trusted connection is equivalent to integrated security. Meaning, the user windows credential context is being used when authenticating against SQL Server. When removing (or setting to false) both trusted connection or integrated security, you are required to provide user id and password as what you did.

It usually works in the first attempt, but fails afterwards if you use the same connection string. The solution is to set Persist Security Info to true. See if that works.

**Comment by Wolfteam** [comment]
yeah, that works, thanks
