### ISSUE TITLE
SqlException: Login failed for user 'xxx'

### ISSUE THREAD

**Issue by gimlichael** [mikependon/RepoDB#270]
I have been mingling a little with the RepoDB, and found an issue i cannot reproduce in ADO.NET or EF.Core; it turns out, that if i use normal connection strings and use ExecuteReaderAsync, I trigger a SqlException from RepoDB.

After a hint from the author, i tried to set Persist Security Info to True, but this is not a normal practice, and I dare to say it is bad practice. I have included a link to a SO article: https://stackoverflow.com/questions/30419627/persist-security-info-property-true-and-persist-security-info-property-false/30420514

> I suggest you specify FALSE or omit the keyword entirely since it is the default, even during development.  The only time you need to specify TRUE is if the application uses SQL authentication and subsequently retrieves the password from the connection object, which in my experience is rarely done or needed.  Performance is not a concern.

I consider this a bug in the otherwise good ORM; I would expect same behavior from RepoDB as ADO.NET / EF.Core.

**Comment by mikependon** [comment]
This is now fixed in the master branch. Will be available on the builds and releases > v1.9.8.

**Comment by mikependon** [comment]
Will be available at >= v1.9.9-beta1. Closing this ticket now.
