### ISSUE TITLE
Request: Support a Schema other than dbo

### ISSUE THREAD

**Issue by BeeFrog** [mikependon/RepoDB#284]
I can't see a way to use an Entity without the attribute on a schema other than dbo.
I really wanted to have my entities on my own schema but the code ends up hitting DataEntityExtension.GetMappedName which only returns the type name and thus ends up defaulting to the dbo schema.

I was hoping that i could manually add my mappings in maybe via ClassMappedNameCache but i can't see anything in there.

maybe something like ClassMappedNameCache.Set(Type type, string name, bool quoted = true)

**Comment by mikependon** [comment]
Of course! In your class, decorate it with Attribute [Map]. See below.

     [Map(“[schema].[TableName]”)]
     public class WhateverClass
     {
          ....
     }

Hope this helps!

**Comment by mikependon** [comment]
Documentation link: https://repodb.readthedocs.io/en/latest/pages/attributes.html#map

**Comment by mikependon** [comment]
Closing this issue for now. Please revert if you have questions. Thanks!

**Comment by BeeFrog** [comment]
Thanks for replying, I did see the attribute route but i really wanted a way to keep my models abstracted from the framework. 
Ideally I'd use the attribute but i'm writing a provider which can handle multiple data sources and it does not know about the models in question. I therefore can't add the attribute to the models,

What I was looking for was another way for map the entity types to a table name or set a default schema for the entities.
Sorry I'm probably not explaining this very well.

**Comment by BeeFrog** [comment]
I guess i'm looking for somethign similar to the TypeMapper but for Entities. or i'd be happy to use the same thing.
TypeMapper.Map(typeof(Decimal), DbType.Double);
e.g 
TypeMapper.Map(typeof(Customer), "mySchema.Customer");

**Comment by mikependon** [comment]
Valid point! I am just afraid to map the Entities on a provider level, if we are to introduce the feature to be a part of Mapper. Like below:

     TypeMapper.Map(typeof(SqlConnection), typeof(Customer), “[sales].[Customer]”);
     TypeMapper.Map(typeof(SQLiteConnection), typeof(Customer), “[Customers]”);

This would slowdown RepoDb in terms of performance by identifying the models before even extracting it. But, I will consider this.

Reopening the case...

**Comment by mikependon** [comment]
FYI: RepoDb has a multi-entity mapper feature as partof first release and eventually removed due to its non-realistic scenario.

We were able to do it like this before:

     EntityMapper.Map(typeof(Customer)).On(Action.Select, “[dbo].[vwCustomer]”).On(Action.Insert, “[sales].[Customer]”):

Also, even though that makes RepoDb SOLID, but that also remove the dynamic(s) as I have to maintain the “Action” enum bound to actual operations. In the end, I have decided to completely remove the features.

**Comment by BeeFrog** [comment]
>  TypeMapper.Map(typeof(SqlConnection), typeof(Customer), “[sales].[Customer]”);
>  TypeMapper.Map(typeof(SQLiteConnection), typeof(Customer), “[Customers]”);

I quite like this approach. What are your concerns with this approach?

Is there anything I can do to help out?

**Comment by mikependon** [comment]
It is simple to implement. The library is abstracted where we could only change 1 method to attain this :)

My concern is a bit high-level, that even it is in Cached object, I am still concern it will affect the efficiencies and performance. But I will test it first, and definitely, this input is a valid point.

I promised RepoDb to run the fastest and most efficient, and the more features it got, the slower it becomes. But I will consider this.

I can also say, that it should be DB level not just provider level.

**Comment by mikependon** [comment]
@BeeFrog, how are you? Can you check the [Implicit Mapping](https://repodb.net/feature/implicitmapping) feature if it is the one you are looking for? Thanks!

**Comment by BeeFrog** [comment]
Thanks Mikependon/Repodb

This is exactly what I was looking for.

**Comment by mikependon** [comment]
Hey @BeeFrog, has this been tested on your side already? Thanks

**Comment by mikependon** [comment]
@BeeFrog, I am closing this one now. Please feel free to reopen if you think this is not yet fixed. Thanks
