### ISSUE TITLE
Where expression using IEnumerable's contains throws error when using inherited class property

### ISSUE THREAD

**Issue by cutig3r** [mikependon/RepoDB#301]
Consider the following classes
`public class Base {
      public int SomeId { get; set;}
}`
`public class Child: Base { }`

Using the following code will fail due to the SomeId property not existing on the child class:
`var someIds = new[] { 1, 2, 3};`
`using (var db = new DbRepository<SqlConnection>(connectionString)) { return db.Query<Child>(c => someIds.Contains(c.SomeId)); }`

**Comment by mikependon** [comment]
This is fixed at RepoDb releases >= v1.10.0.
