### ISSUE TITLE
Requests: Support for Table attribute

### ISSUE THREAD

**Issue by Grauenwolf** [mikependon/RepoDB#360]
Rather than requiring a custom `Map` attribute, this should support the `Table` attribute from `System.ComponentModel.DataAnnotations.Schema`.

This is from the `System.ComponentModel.Annotations` package, so any ORM is allowed to use it.

**Comment by mikependon** [comment]
#284 - could be related.

**Comment by andreas-soroko** [comment]
+1 
maybe also ColumnAttribute ?

**Comment by mikependon** [comment]
I am not prioritizing this for now, please advise if [this](https://repodb.readthedocs.io/en/latest/pages/attributes.html#map) is not enough. It does the job as you pointed here.

**Comment by andreas-soroko** [comment]
but why reinvent the wheel ? is there any special reason ?

**Comment by Grauenwolf** [comment]
The benefit of supporting `System.ComponentModel.DataAnnotations.Schema` is that it would make it easier to port code from other ORMs to yours.

For example, you could just drop-in a EF or EF Core class that was declared with those attributes and it would more or less just work.

I'm not suggesting removing what you already have, as that would break backwards compatibility. It's just a suggestion for making entity classes more portable. It's like how all the serialization libraries now honor `[DataContract]` and `[DataMember]` in addition to their own attributes for advanced cases.

**Comment by mikependon** [comment]
Really makes sense. I may be doing this, but not for now because the impact is a bit high due to the fact that it is in Core of RepoDb.

Also, it requires me to rewrite/retests thousands of Unit and Integration Tests.

For now, this is not feasible, but the support might be done in the future. No timeline yet.

**Comment by lauw** [comment]
I made a gist to use Table/Column attributes (mostly so I can use different casing), it's just for my own use-case, but you can edit it as you see fit. It's required that you use the latest beta version which has support for Class/PropertyMapping.

https://gist.github.com/lauw/20747e47e373444432278985e8eee495

Add the gist to your project and call it:
`RepoDbMapper.MapTablesAndColumns(NameCasing.SnakeCase);
`

**Comment by mikependon** [comment]
Awesome editions you made, let me assess if we can consider putting your code in the core of RepoDb. Seems to be awesome.

As you mentioned about latest beta release, it is now supporting a feature called Implicit Mapping in which it allows you to map the following via class mappers.

- Class Name
- Property Name
- Primary
- Identity
- Type Maps
- Property Handlers

Still I am waiting an update to a guy that would contribute a class called ClassMap<T> or FluentMapper<T>, that utilizes the mapper classes I developed.

In anyway, please feel free to explore the [Implicit Mapping](http://repodb.net/feature/implicitmapping) from the official site.

The actual thread can be found at #415 .

**Comment by mikependon** [comment]
I am planning to open this one as for-grabs.

@lauw - I would assume that the Attributes has a higher precedence than using the Mappers as it is explicitly being annotated. Btw, supporting a Table and Column data annotation seems to be very easy in RepoDb. I can guide you 2 liner changes to add the support for this, but you have to write Unit Test (and maybe Integration Tests).

Are you open to make a PR for this? The changes is on the following code lines.

- ClassMappedNameCache - https://github.com/mikependon/RepoDb/blob/44deec8192d718898e53e75bd19770922afdeb2b/RepoDb.Core/RepoDb/Extensions/DataEntityExtension.cs#L39
- ProperyMappedNameCache - https://github.com/mikependon/RepoDb/blob/44deec8192d718898e53e75bd19770922afdeb2b/RepoDb.Core/RepoDb/Extensions/PropertyInfoExtension.cs#L84

**Comment by lauw** [comment]
@mikependon Great! :) I'm willing to take a look at it later this week, will first see if it doesn't cost too much time with the tests. This wasn't the reason I made the mapper though, it was mostly to support snake_case and I needed a way to annotate my db objects.

**Comment by mikependon** [comment]
@lauw - what you had done is a really cool stuff. No need for a rush for now, there are current activities on the library when it comes to Implicit Mapping, as you mentioned above (you need to reference the latest). But TBH, there is one user that approached me about snake casing support - and I find it not really a common case, but it seems.

Would you be able to save your gist for future PR here? I am thinking to integrate that snake_case logic you did for Implicit Mapping (once the PR for FluentMapper<T> and ClassMap<T> is finish). We can discuss how to move forward.

**Comment by mikependon** [comment]
> I'm willing to take a look at it later this week, will first see if it doesn't cost too much time with the tests.

Well, the tests are not that extensive, you may have to extend these 2 unit tests files.
- [ClassMapperTest](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.UnitTests/Mappers/ClassMapperTest.cs)
- [PropertyMapperTest](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.UnitTests/Mappers/PropertyMapperTest.cs)

And may create additional integration test that has a completely the same contents, except that you are using the `Table` and `Column` attribute rather than `Map`. Here is the [integration test](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/ObjectMappingTest.cs) that you can copy over. TBH, I did the same with [implicit mapping test](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/ImplicitMappingTest.cs).

**Comment by mikependon** [comment]
@lauw - hey mate, are you still open for a PR of this? :)

**Comment by mikependon** [comment]
This is now fixed via PR #435. This will be available on the next beta RepoDb >= v1.11.1-beta2.

@cwaldron - please do let me know if you need a beta build right away.

**Comment by mikependon** [comment]
Just added an extensive Integration Tests for this. The tests can be found [here](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/DataAnnotationMappingTest.cs).

In addition, the Unit Tests for `Key/Primary` and `Table/Column/Map` collisions has also been added/extended.

- [ClassMapperTableAttributeTest](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.UnitTests/Mappers/ClassMapperTableAttributeTest.cs)
- [PropertyMapperColumnAttributeTest](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.UnitTests/Mappers/PropertyMapperColumnAttributeTest.cs)
- [KeyAttributeTest](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.UnitTests/Attributes/KeyAttributeTest.cs)
- [ColumnAttributeTest](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.UnitTests/Attributes/ColumnAttributeTest.cs)
- [TableAttributeTest](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.UnitTests/Attributes/TableAttributeTest.cs)

**Comment by mikependon** [comment]
The fix is now available in version RepoDb v1.11.1.

**Comment by mikependon** [comment]
The latest release of RepoDb is now including this request. Please install the version 1.11.2.

With this, I am closing this one now. Just revert if you have questions.
