### ISSUE TITLE
[Question] RepoDb.PostgreSql

### ISSUE THREAD

**Issue by andreas-soroko** [mikependon/RepoDB#366]
The lib was added below the "fully supported databases" but the lib was not published yet. 
any plans here or just forgot to publish the lib ?

![image](https://user-images.githubusercontent.com/47380084/71959548-47d24d00-31f3-11ea-829b-cec4c37ccc48.png)

![image](https://user-images.githubusercontent.com/47380084/71959484-24a79d80-31f3-11ea-8db6-516d4f15b8f6.png)

**Comment by mikependon** [comment]
The only DB that is not yet brought to the Production. We are now finalizing the list of items for PostgreSql. To be more realistic on our side, we are aiming to deploy this on end of this month January 2020.

**Comment by andreas-soroko** [comment]
Is there a  list what is missing/not working ? and/or is it possible to get a "beta" package ?

**Comment by mikependon** [comment]
When do you need it?

**Comment by andreas-soroko** [comment]
we are currently evaluate if repodb does fit for us, currently we are just using postgres dbs so... 
if you think that the package is ready for beta tests, we would like to help & test it. 

also is there a possibility to add
- Resolver for column names ?  
- converter for types ? ( something like "Dapper.SqlMapper.TypeHandler" )

**Comment by mikependon** [comment]
Thank you for that. Let us finalize all the Unit Tests and Integration Tests first before issuing the BETA. We are keen on promoting this internally to always have it delivered first before even the BETA. So, if you could wait a little bit.

Yes, the converter is feasible via *Resolver*. Are you aiming the items below?

We have these implementations already.

### PostgreSql:

Not yet final.

- [PostgreSqlConvertFieldResolver](https://github.com/mikependon/RepoDb/blob/master/RepoDb.PostgreSql/RepoDb.PostgreSql/Resolvers/PostgreSqlConvertFieldResolver.cs)
- [DbTypeToPostgreSqlStringNameResolver](https://github.com/mikependon/RepoDb/blob/master/RepoDb.PostgreSql/RepoDb.PostgreSql/Resolvers/DbTypeToPostgreSqlStringNameResolver.cs)

### For Others

- [SqlServer](https://github.com/mikependon/RepoDb/tree/master/RepoDb.Core/RepoDb/Resolvers) - and also [this](https://github.com/mikependon/RepoDb/tree/master/RepoDb.Core/RepoDb/_SqlServer/Resolvers).
- [SqLite](https://github.com/mikependon/RepoDb/tree/master/RepoDb.SqLite/RepoDb.SqLite/Resolvers) - a good example is [this](https://github.com/mikependon/RepoDb/blob/master/RepoDb.SqLite/RepoDb.SqLite/Resolvers/SqLiteConvertFieldResolver.cs).
- [MySql](https://github.com/mikependon/RepoDb/tree/master/RepoDb.MySql/RepoDb.MySql/Resolvers)

**Comment by andreas-soroko** [comment]
> So, if you could wait a little bit.

sure

> Yes, the converter is feasible via Resolver. Are you aiming the items below?
> We have these implementations already.

close, but i cant convert a jsonb column into a class, right ?

**Comment by mikependon** [comment]
Ah, I got you now. On this case, it is not supported. It is also a good case to somehow support a resolver during the process of transformation (by ingesting the resolver and defined the return .NET CLR type of that target column). I will take note of this.

> But honestly, that is already pre-discussed making the version 2.0 of RepoDb to be JSON compliant.  That will handle this scenario as well.

I hope that it is not a big factor at your end to consider using RepoDb.

**Comment by mikependon** [comment]
> close, but i cant convert a jsonb column into a class, right ?

Is this really a common scenario? I now have a solution to this (in my mind), but I need to think whether this is really a very common scenario so I could support this soon.

Thank you for your insights.

**Comment by andreas-soroko** [comment]
> Is this really a common scenario?

for us, yes ( i think for others also when is see the issue comments from others mappers. some orm mapper like dapper, EF Core support type converter ) 
the benefit is 
- we dont need to manually convert a string into a class to use it. 

our biggest problem with most mapper are, they support converter but not for enums ( although there are solutions from the community )

our problem with the most orm mapper are: 
- dapper 
--> does support converter -> great
--> does not support enum mappings ( as string instead of ints ) out of the box -> need to use .ToString ( open Issue since 2015,  )

- dapper + OrmMapper
--> does support converter -> great
--> no chance to use enums without backing field

- ef core
--> is able to do booth, but there we are struggling with other things..

- linq2db
--> supports converter
--> same problem with enums ( open Issue since 2015 )

**Comment by mikependon** [comment]
Thanks for the comments. I will place this is a feature for RepoDb. It is easy! :)

Ensure to include you on that discussion and reference this issue.  Thanks for this input and cheers!

**If I could comment on your last comment.**

> no chance to use enums without backing field

Enum is an existing feature of RepoDb, the article can be seen [here](https://github.com/mikependon/RepoDb/wiki/Working-with-Enumerations).

**Comment by mikependon** [comment]
This is now deployed in a pre-release version of RepoDb (please see [RepoDb.PostgreSql v1.0.0-beta1](https://www.nuget.org/packages/RepoDb.PostgreSql/1.0.0-beta1)).

Would you be able to play around with it? Thanks!

**Comment by mikependon** [comment]
The version 1.0.0 is now available.

**Comment by andreas-soroko** [comment]
thanks!

**Comment by mikependon** [comment]
Please do let us know if you have questions or problems. We would assume, you have a lot as it is an initial release. You can reach directly via Gitter chat for fast replies.
