### ISSUE TITLE
Request: Create a NerdDinner Application that is being run by RepoDb.

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#368]
Link: https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/nerddinner/introducing-the-nerddinner-tutorial

**Comment by mikependon** [comment]
Here is the story @vivencio2.

**Comment by vivencio2** [comment]
Alright @mikependon . I'll be using this sample (https://github.com/csharpfritz/sample-NerdDinner) as this is the closest I get of NerdDinner implementation in dotnet core.

Btw, how can I assign this issue to me?

**Comment by mikependon** [comment]
Thanks. Just revert if you need some help implementing it.

**Comment by mikependon** [comment]
Any news on this?
