### ISSUE TITLE
Question: Is there a way to get the model after Insert?

### ISSUE THREAD

**Issue by andreas-soroko** [mikependon/RepoDB#383]
currently `InsertAsync` returns just the Id, is it possible to get also the complete Model ? 

 scenario: 
```sql
create table my_model {
   id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
   is_active BOOLEAN NOT NULL DEFAULT true
}
```

```csharp
class MyModel
{
    public Guid Id { get; set; }
    public bool IsActive { get; set; }
}
...
//currently 
var model = new MyModel(); 
model.Id = await repo.InsertAsync(model);

// would be great 
var model = new MyModel(); 
model.Id = await repo.InsertAsync(new MyModel());

// workaround
var model = new MyModel(); 
model.Id = await repo.InsertAsync(new MyModel());
model = await repo.Query(....)
```

**Comment by mikependon** [comment]
The model you passed is the one stands as truth. The id is automatically set back to the model itself. In this case, you do not need to make an additional round trip. But, if the instance you inserted is different from the model you are intend to (like your example 2), then you are required a round trip. It also same if you are using a table-based calls.

**Comment by andreas-soroko** [comment]
oh sorry, the example were wrong ( and doesnt make sense ... ) 

```csharp
class MyModel
{
    public Guid Id { get; set; }
    public bool IsActive { get; set; }
}
...
//currently 
var model = new MyModel(); 
await repo.InsertAsync(model);
Assert.True(model.IsActive); // is not 

// workaround
var model = new MyModel(); 
await repo.InsertAsync(model );
model = await repo.Query(....)
Assert.True(model.IsActive); // yeay 

// would be great 
var model = await repo.InsertAsync(new MyModel());
Assert.True(model.IsActive); // yeay 
```

are there any plans to support this case in the future ?

**Comment by mikependon** [comment]
> // workaround
> var model = new MyModel(); 
> await repo.InsertAsync(model );
> model = await repo.Query(....)
> Assert.True(model.IsActive); // yeay 

In your case, there is no reason to get the refreshed data actually. The *IsActive* column is not nullable and it will always save the record in the DB based on the values of the properties of your model.

Why do you expect a *True* in your assertion if you save the *Model.IsActive* value as *False*? Was it because the the *IsActive* column is defaulted to *True*?

**Comment by andreas-soroko** [comment]
> The IsActive column is not nullable

oh, yeah ups - imagine it would be nullable

> Was it because the the _IsActive_ column is defaulted to _True_?

yep

**Comment by mikependon** [comment]
This will not be supported and it is purposely in design. For now, you can do round-trip if you think the entity is not updated from the DB.

**Comment by andreas-soroko** [comment]
Okay thanks :+1:
