### ISSUE TITLE
Feature: Introduce PostgreSql support to NpgsqlDbType.

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#390]
**Descriptions**

A developer must be able to pass the correct PostgreSql DB Type. Let us say the user would like to make sure the the column Customer.ExtraInfo below is passed as a NpgsqlDbType.Json type.

```csharp
public class Customer
{
	public int Id { get; set; }
	...
	[NpgsqlTypeMap(NpgsqlDbType.Json)]
	public string ExtraInfo { get; set; }
}
```

If ever the user set the value of DbType, it is still not colliding.

As per Shay (the author of Npgsql library), this setting must be explicitly set as Npgsql is using the NpgsqlDbType property instead (over DbType).

**Extent of the changes**

The changes must be happened in RepoDb.PostgreSql and RepoDb.Core only.

Assessment: **_Minor_**

**Acceptance Criteria**

All existing Integration Tests and Unit Tests must be passed for all libraries and extensions.

**Comment by mikependon** [comment]
@ffandreassoroko - tagging you here.

**Comment by mikependon** [comment]
The fix for this is now available at [RepoDb.PostgrelSql v1.0.3](https://www.nuget.org/packages/RepoDb.PostgreSql/1.0.3).

To fix your JSON mapping, simply add the '' attribute in your property. See sample code snippets below.

```csharp
private class EntityModel
{
	public System.Int64 Id { get; set; }
	[NpgsqlTypeMap(NpgsqlDbType.Json)]
	public System.String ColumnJson { get; set; }
}
```

Please revert if you have questions.

FYI @ffandreassoroko.

**Comment by andreas-soroko** [comment]
Is there also a global option like TypeMap ? 
`TypeMapper.Map(typeof(DateTime), DbType.DateTime2);`

Edit: 
works when i set the attribute on the Property (for jsonb ), but what can i do for Enums ?

**Comment by mikependon** [comment]
For the global options, no. That is not introduced due to the fact that RepoDb.Core could not reflect the classes in the RepoDb.PostgreSql namespaces.

I am trying to put everything in the compiler to compile AOT so the overall performance will not be affected, the only way I can do it is through attribute.

**Comment by mikependon** [comment]
> but what can i do for Enums ?

Can you share a sample code?

**Comment by andreas-soroko** [comment]
> For the global options, no. 

:( okay! 

> Can you share a sample code?

see here #388, does not make any difference if i use `TypeMap(DbType.String)` or not, the exceptions occurs everytime (#367 `column "pg_type" is of type enum_test but expression is of type text`, `...is of type integer`)


Edit: 
i think the difference between your enum tests and my one is this part
`CREATE TYPE enum_test AS ENUM ('test1', 'test2')`


Edit: 
and before we are getting the next problem: do you know about the PgName attribute ?
https://www.npgsql.org/doc/types/enums_and_composites.html

**Comment by mikependon** [comment]
It should be fixed now and I already deployed the fix for that. Also, all the "Integration Tests" are passing.

Links: https://github.com/mikependon/RepoDb/blob/master/RepoDb.PostgreSql/RepoDb.PostgreSql.IntegrationTests/EnumTests.cs

I made this comment already.

> Deployed. Kindly update your RepoDb.Core version to v1.10.8.

--------------

Let us say you have a table named CompleteTable with column Id (LONG) and Hand (Text) and a model like below.

```csharp
[Map("CompleteTable")]
public class PersonWithText
{
	public System.Int64 Id { get; set; }
	public Hands? ColumnText { get; set; }
}
```

The it will just work without doing anything into it.

--------------

Are you still encountering the problem even with the latest release?

**Comment by andreas-soroko** [comment]
> Are you still encountering the problem even with the latest release?

yes,
- RepoDb -> 1.10.9
- RepoDb.PostgreSql -> 1.0.3

`Npgsql.PostgresException : 42804: column "pg_type" is of type enum_test but expression is of type text`


did you read my edit ? 

> Edit:
> i think the difference between your enum tests and my one is this part
> CREATE TYPE enum_test AS ENUM ('test1', 'test2')

**Comment by mikependon** [comment]
I just refresh and I have the 'edit' now. I need to look at it first.

**Comment by mikependon** [comment]
Been on a very busy days in my organization. Anyway, I had never looked at this yet. Is this very important in your case, or is this something I can look in the next couple of days?

I am on a middle of bulk operations development :).

**Comment by mikependon** [comment]
I will create separate issue for the issue you mentioned. Closing this one now.
