### ISSUE TITLE
Bug: Enum Bug

### ISSUE THREAD

**Issue by sellig** [mikependon/RepoDB#400]
Test failed if Enum property is not null

```csharp
public class PersonWithText
        {
            public System.Int64 Id { get; set; }
            public System.Guid SessionId { get; set; }
            public Hands ColumnNVarChar { get; set; }
        }
```

If the **ColumnNVarChar** in table **CompleteTable** is set as not Allow Null,  the test (and others) **TestInsertAndQueryEnumAsText** failed with 
"No coercion operator is defined between types 'System.String' and 'RepoDb.SqlServer.IntegrationTests.EnumTests+Hands'"

**Comment by mikependon** [comment]
Underneath, this might be related to #401 and #402.

**Comment by mikependon** [comment]
The fix has been pushed to beta2 of v1.10.11.

```csharp
> Install-Package RepoDb -version 1.10.11-beta2
```

The version updates to `RepoDb.SqlServer` and `RepoDb` will soon to be released. For now, please install this beta2. Cheers!

**Comment by sellig** [comment]
Thank you Michael.

**Comment by mikependon** [comment]
Please revert and feel free to re-open this if the fix has not addressed your issue. Will look at your other issue on the next beta release.
