### ISSUE TITLE
Request: RepoDb.SqlServer project cleaning

### ISSUE THREAD

**Issue by sellig** [mikependon/RepoDB#406]
In RepoDb.SqlServer project setting change Pathl for XML documentation else cannot build the project, the path is local to your machine (C:\Users\MichaelP)
```csharp
Could not write to output file 'C:\Users\MichaelP\Source\Repos\GitHub\RepoDb\RepoDb.SqlServer\RepoDb.SqlServer\RepoDb.SqlServer.xml
```
Change it in a folder inside the solution ?

**Comment by mikependon** [comment]
Oh, thanks for this. I am happy if you can make the PR for this :)

**Comment by mikependon** [comment]
Closing this after your PR.
