### ISSUE TITLE
Bug: Truncates string and bytes

### ISSUE THREAD

**Issue by ghost** [mikependon/RepoDB#423]
I can see that strings/binary gets truncated at 8000 chars/bytes

Use nvarchar(max) and varbinary(max)

Can I avoid that?

**Comment by mikependon** [comment]
Was not it a default behavior of chars/bytes? I am away for now from my PC, but will do look at this soon.

**Comment by mikependon** [comment]
Would you be able to share your model and your schema? I will play around with it.

**Comment by ghost** [comment]
Maybe it's defaulting in RepoDb.SqlServer/RepoDb.SqlServer/DbHelpers/SqlServerDbHelper.cs

```
   private int? GetConvertedSize(string type, int size)
        {
            return (size == -1) ? 8000 : size;
        }
```
No problem, just need to save a file as bytes or base64 string and 8000 bytes are to little.

But really like what you have created, very clever and easy to understand :-)

Prefer this over EF Core any time. 
Way to much magic happens in EF Core for me to feel calm...

**Comment by ghost** [comment]
Basically just any string in the model:

Property
`public byte[] RawDocumentData { get; set; }`
SQL
`[RawDocumentData] VARBINARY(max)  NOT NULL,`

or

Property
`public string RawDocumentData { get; set; }`
SQl
`[RawDocumentData] NVARCHAR(max)  NOT NULL,`

When I give RawDocumentData a large string or byte array, they gets truncated to 8000 chars/bytes in SQL Server.

**Comment by mikependon** [comment]
Just verified this bug. Will issue a fix on this soon. It will be a part of version >= 1.11.0-beta5.

**Comment by mikependon** [comment]
This issue has been fixed and will be part of the next release (actual, alpha or beta). You are correct on the code-lines where you lead me on the DbHelper of SQL Server. The reason for that was the historic approach on the statement Preparation which always requires the sizes to be in-placed. It may be failing with SDS, but not on MDS.

My integration tests are all pointed to MDS and by removing the introduced lines (size of 8K at the DbHelper) does not give an error anymore. Hope that explains!

Will close this issue once the solution is deployed.

**Comment by ghost** [comment]
That just great, thank you so much!

Do you have an ETA on a alpha/beta release in Nuget? 
Else I can just build it my self so no hurry :-)

Sorry to ask but what does SDS and MDS correlate to? Can't quess it my self and Google can't help so it make sense :o)

**Comment by mikependon** [comment]
The ETA will depends on the existing discussion on the other issues #415. I need to bring this feature on v1.11.0 - so do your reports.

The SDS and MDS are the SQL Server providers (drivers) we used.
SDS = System.Data.SqlClient
MDS = Microsoft.Data.SqlClient

**Comment by ghost** [comment]
Arh of course, thanks for explaining :-)

I'll keep an eye that issue.

Have fun...!

**Comment by mikependon** [comment]
@Kodestuen - if you can manage building a new binary for yourself, then that is not a problem. But will definitely update this incident once it is deployed.

**Comment by mikependon** [comment]
This is now a part of the latest release [RepoDb.SqlServer v1.0.7](https://www.nuget.org/packages/RepoDb.SqlServer/1.0.7).

```csharp
> Install-Package RepoDb.SqlServer -version 1.0.7
```
