### ISSUE TITLE
Documentation copy paste mistake

### ISSUE THREAD

**Issue by TwentyFourMinutes** [mikependon/RepoDB#424]
Not sure where to post issues regarding to the website and its docs, but whatever.

Over on https://repodb.net/feature/classmapping#primary-mapping under Primary Mapping, the guide quotes:
```cs
PropertyMapper.Add<Customer>(e => e.Id);
```  
However it should really be:
```cs
PrimaryMapper.Add<Customer>(e => e.Id);
```

**Comment by mikependon** [comment]
Hey, thank you for this report. It could be a typo error on this newest page we had for the site. The feature is still in beta phase.

In anyway, here is the actual [site](https://github.com/mikependon/RepoDb.NET) in which you can simply do PR if you wish to. But I will handle this case myself later.

**Comment by mikependon** [comment]
The fix has been deployed. Closing this one now.
