### ISSUE TITLE
Question: Why are the contributions not showing - Report to Github

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#431]
@guy-lud - thinking why your [contributions](https://github.com/mikependon/RepoDb/pull/425) are not showing up directly on RepoDb. I would expect that you must be on the [contributors](https://github.com/mikependon/RepoDb/graphs/contributors) tab. TBH, both you and one more contributor are not reflecting here.

I tried using Desktop Github to see your contributions and it is reflecting there.

![image](https://user-images.githubusercontent.com/591015/81145535-bbece980-8f76-11ea-9fea-5ef14bcb66ef.png)

But visiting the actual [ClassMap](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb/ClassMap.cs) and [PrimaryOptions](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb/PrimaryOptions.cs) files doesn't reflect you. See below.

![image](https://user-images.githubusercontent.com/591015/81144532-8f37d280-8f74-11ea-97ef-81983e8e9fd9.png)

![image](https://user-images.githubusercontent.com/591015/81144595-b7bfcc80-8f74-11ea-9550-526c3109c07c.png)

And that goes with the other files as well (ie: [IdentityOptions](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb/IdentityOptions.cs), [PropertyOptions](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb/PropertyOptions.cs), etc).

**Comment by guy-lud** [comment]
@mikependon , are you asking me?

**Comment by mikependon** [comment]
@guy-lud yes by that time. But seems I know the reason already. I think it is related to the account you used when pulling the request.
