### ISSUE TITLE
Bug: insert<T> issue - parameter 'xxx' already added

### ISSUE THREAD

**Issue by fake-fur** [mikependon/RepoDB#432]
hi mike

do you have any idea why this would be happening? i have a model class that throws an exception on insert saying "parameter 'xxx' has already been defined / added" - but of course it hasn't and it is a single insert of a single model

using mysql 5.7 btw
thanks for any ideas you may have

**Comment by mikependon** [comment]
For fast fix, would you be able to share your table schema and your class model? I will try to simulate.

**Comment by fake-fur** [comment]
happy to but is it possible to email you a zip or something?

**Comment by fake-fur** [comment]
[clients.zip](https://github.com/mikependon/RepoDb/files/4588869/clients.zip)

**Comment by mikependon** [comment]
Thanks. I will do check this one this coming weekend or Friday. Would that be okay?

**Comment by fake-fur** [comment]
yes of course - thanks so much :)

**Comment by fake-fur** [comment]
more info:
mysql connector 8.0.20
mysql server 5.7

i replaced an `"insertAll<T>(list-of-T's)`" that failed reliably, with a loop that does raw sql insert statements one at a time (could do a batch but this was quicker for a test) and it works fine

the bug seems to be that "'name' parameter is already added" (but it can be a diff column is already added on another model) - which i think might be in the query builder where is builds a field list from the model

not sure if this helps but i might have to look into writing a new querybuilder if i cannot find a solution soon

:)

**Comment by mikependon** [comment]
Will look at this issue soon. Will revert to you ASAP

**Comment by fake-fur** [comment]
thanks so much

**Comment by fake-fur** [comment]
so more info: the reading of meta data from the information_schema has a syntax error in it: this is what is logged in mysql error log:
```
SELECT COLUMN_NAME AS ColumnName
	            , CASE WHEN COLUMN_KEY = 'PRI' THEN 1 ELSE 0 END AS IsPrimary
                , CASE WHEN EXTRA LIKE '%auto_increment%' THEN 1 ELSE 0 END AS IsIdentity
                , CASE WHEN IS_NULLABLE = 'YES' THEN 1 ELSE 0 END AS IsNullable
                , DATA_TYPE AS ColumnType /COLUMN_TYPE AS ColumnType/
                , CHARACTER_MAXIMUM_LENGTH AS Size
                , COALESCE(NUMERIC_PRECISION, DATETIME_PRECISION) AS `Precision`
                , NUMERIC_SCALE AS Scale
                , DATA_TYPE AS DatabaseType
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE
	            TABLE_NAME = 'syncchecksums'
            ORDER BY ORDINAL_POSITION
```
but this bit:

`/COLUMN_TYPE AS ColumnType/`

 looks like a failed comment and when i comment it the query runs just fine

was this a tired copy / paste error maybe?
:)

**Comment by mikependon** [comment]
currently looking on this one.

**Comment by mikependon** [comment]
> /COLUMN_TYPE AS ColumnType/

It is in purpose that this line of code is commented and this one is working on my end. The line of the code can be seen [here](https://github.com/mikependon/RepoDb/blob/19f386132613c32759678387d1e3da1d989cd2fd/RepoDb.MySql/RepoDb.MySql/DbHelpers/MySqlDbHelper.cs#L57).

**Info:**
- MySql.Data (>= 8.0.19)
- RepoDb (>= 1.10.11)
- RepoDb.MySql (v 1.0.9)
- **MySql (v 8.0.18)**

I will try to see the other issue you reported instead, not this syntax issue.

**Comment by mikependon** [comment]
Hi, this seems to be working on my side. I tried the `Query`, `QueryAll`, `Insert` and `InsertAll` operations with the models and schemas you shared.

**Info:**
- MySql.Data (>= 8.0.19)
- RepoDb (>= 1.10.11)
- RepoDb.MySql (v 1.0.9)
- **MySql (v 8.0.18)**

Solution/Project: [SimulateRepoDbIssue432.zip](https://github.com/mikependon/RepoDb/files/4599232/SimulateRepoDbIssue432.zip)

Local Results: [Issue 432 Result.txt](https://github.com/mikependon/RepoDb/files/4599243/Issue.432.Result.txt)

I am now suspecting the version of MySql in your part. As I remember, some of the syntaxes I had written is for MySql (>= 8.0.x) - it was explained it my old documentation in ReadTheDocs, whereas not in RepoDb.NET.

Is it correctly understood that you are running **MySql (5.7.X)**?

**Comment by fake-fur** [comment]
yes we are stuck on mysql v5.7.xx

thing is it worked fine with connector 8.0.19 and broke at connector 8.0.20 with same database version

**Comment by mikependon** [comment]
Okay, then let me debug using the local solutions I had of RepoDb and RepoDb.MySql with updated version of Connector to 8.0.20. Maybe I can replicate it there. This will not take long, will revert ASAP.

**Comment by fake-fur** [comment]
or we could make a legacy 5.7.x compatible querybuilder maybe for a longer term solution when there is some time? either way thanks so much - next time i'm in denmark i owe you a good few beers :)

**Comment by mikependon** [comment]
Thanks for the beers soon! :) I tested it using the **MySql.Data (8.0.20)** and it is working there. I also tried running the Integration Tests on my DEV machine and all are passing.

![image](https://user-images.githubusercontent.com/591015/81412449-27d07d00-9144-11ea-9cb8-f1b4b461e9b7.png)

**Comment by mikependon** [comment]
Would you be able to share me the result of the following?

**Retrieving the model fields.**

```csharp
var fields = FieldCache.Get<Models.Client>().AsList();
```

**Retrieving the database fields.**

Make sure to change the `connectionString`.

```csharp
using (var connection = new MySqlConnection("Server=localhost;Database=RepoDb;Uid=user;Pwd=Password123;"))
{
	var dbFields = DbFieldCache.Get(connection, "clients", null).AsList();
}
```

Lastly, for the fun of it, would you execute the code below and see if the generated SQL Statement is correct?

```csharp
using (var connection = new MySqlConnection("Server=localhost;Database=RepoDb;Uid=user;Pwd=Password123;"))
{
	var builder = connection.GetStatementBuilder();
	var dbFields = DbFieldCache.Get(connection, "clients", null).AsList();
	var fields = FieldCache.Get<Models.Client>().AsList();
	var insertStatement = builder.CreateInsert(new QueryBuilder(),
		ClassMappedNameCache.Get<Models.Client>(),
		fields,
		dbFields.FirstOrDefault(df => df.IsPrimary),
		dbFields.FirstOrDefault(df => df.IsIdentity),
		null);
}
```

The expected output would be.

```
INSERT INTO `clients` ( `guid`, `notes`, `servicenotes`, `medicalhistory`, `espsitecode`, `site`, `referredby`, `active`, `cardcode`, `organisation`, `name`, `title`, `firstname`, `lastname`, `classificationcode`, `categorycode`, `listclientloyaltycode`, `description`, `origin`, `activesince`, `firstvisit`, `retainer`, `representative`, `subscriptionvalue`, `subscriptionends`, `applysalestax`, `balance`, `contact`, `accounts`, `operator1`, `operator2`, `owner1`, `owner2`, `mailinglist`, `status`, `physicaladdress`, `physicalstreet`, `physicalarea`, `physicalcity`, `physicalcountry`, `physicalcode`, `postaladdress`, `postaldetails`, `postalarea`, `postalcity`, `postalcountry`, `postalcode`, `telephonehome`, `telephonework`, `telephone1`, `telephone2`, `home`, `callbox`, `office`, `cellphone`, `fax`, `modem`, `email`, `web`, `calldate`, `called`, `lastvisit`, `frequency`, `lastcharge`, `totalspent`, `promomiles`, `account`, `complimentary`, `picturepath`, `tracking`, `nextvisit`, `appointmentgroupstr`, `missedappointments`, `staff`, `staff1`, `staff2`, `staff3`, `sex`, `birthdate`, `occupation`, `spouse`, `children`, `salestax`, `salestaxnumber`, `enableearnmiles`, `settings`, `listswversionguid`, `clientimagepath`, `emergencycontactperson`, `emergencycontactnumber`, `id`, `sync_action` ) VALUES ( @guid, @notes, @servicenotes, @medicalhistory, @espsitecode, @site, @referredby, @active, @cardcode, @organisation, @name, @title, @firstname, @lastname, @classificationcode, @categorycode, @listclientloyaltycode, @description, @origin, @activesince, @firstvisit, @retainer, @representative, @subscriptionvalue, @subscriptionends, @applysalestax, @balance, @contact, @accounts, @operator1, @operator2, @owner1, @owner2, @mailinglist, @status, @physicaladdress, @physicalstreet, @physicalarea, @physicalcity, @physicalcountry, @physicalcode, @postaladdress, @postaldetails, @postalarea, @postalcity, @postalcountry, @postalcode, @telephonehome, @telephonework, @telephone1, @telephone2, @home, @callbox, @office, @cellphone, @fax, @modem, @email, @web, @calldate, @called, @lastvisit, @frequency, @lastcharge, @totalspent, @promomiles, @account, @complimentary, @picturepath, @tracking, @nextvisit, @appointmentgroupstr, @missedappointments, @staff, @staff1, @staff2, @staff3, @sex, @birthdate, @occupation, @spouse, @children, @salestax, @salestaxnumber, @enableearnmiles, @settings, @listswversionguid, @clientimagepath, @emergencycontactperson, @emergencycontactnumber, @id, @sync_action ) ; SELECT LAST_INSERT_ID() AS `Result` ;
```

**Comment by fake-fur** [comment]
will do now but this line of code:

`DATA_TYPE AS ColumnType /*COLUMN_TYPE AS ColumnType*/`

shows up in the mysql error log as:

`DATA_TYPE AS ColumnType /COLUMN_TYPE AS ColumnType/`

which fails to run

**Comment by fake-fur** [comment]
ok all the things worked as expected, except the insert query should not have @id and @sync_action - those are not in the table and are why i asked for an [Ignore] attribute

**Comment by mikependon** [comment]
The library is intelligent enough to ignore the fields that are not aligned with the database. The codes I shared you above is just generating the `Insert` SQL statement based on the list of fields you passed (without the additional layer of checking).

To help you understand, the `CommandTextCache` is the cacher of the Command Texts and does the trick [here](https://github.com/mikependon/RepoDb/blob/1b90ddae55e8b57de6369b6d159b8557a9ad0d55/RepoDb.Core/RepoDb/CommandTextCache.cs#L226). In which it calls the `GetActualFields` method [here](https://github.com/mikependon/RepoDb/blob/1b90ddae55e8b57de6369b6d159b8557a9ad0d55/RepoDb.Core/RepoDb/CommandTextCache.cs#L660).

 That is the reason why the `Ignore` attribute has been removed. :)

**Comment by fake-fur** [comment]
i thought so when i saw the list of columns you pull from the information_schema but i thought i would just check ;)

**Comment by mikependon** [comment]
I will conclude this issue as "Working as Expected". Can I close now? Thanks

**Comment by fake-fur** [comment]
well it doesn't work for me so how would i proceed now?

**Comment by mikependon** [comment]
Have you tried this in you local machine?

https://github.com/mikependon/RepoDb/files/4599232/SimulateRepoDbIssue432.zip

**Comment by fake-fur** [comment]
let me try that now

it doesn't even compile for me :(

**Comment by mikependon** [comment]
That contains the models and schemas you shared with a very thin code implementations. Make sure to restore the Nuget Package before running (and you need to be in VS 2019).

**Comment by fake-fur** [comment]
ahhhhhh you have mysql data 8.0.19 - i cannot install that - i have 8.0.20 which is where the error starts showing - i am unable to downgrade that package according to vs2019

**Comment by mikependon** [comment]
Okay, then your last resort is to debug/trace it yourself. To help you with, you have to implement the tracer.

```csharp
public class CustomTrace : ITrace
{
    public void AfterQuery(TraceLog log)
    {
        // Some implementations here
    }

    public void BeforeQuery(CancellableTraceLog log)
    {
        // Some implementations here
    }

    ...
}
```

Then inject the `CustomTrace` class when you call the `Insert` operation (inside the `saveToDb` method your `Client` class).

```csharp
recordno = Convert.ToInt32((ulong)conn.Insert<Client>(this), trace: new CustomTrace());
```

Then add a breakpoint in the `BeforeInsert` method.

Here is the reference [feature](http://repodb.net/feature/tracing) that you can follow.

Lastly, please share me the content of the `log.Statement` and a screenshot of the `log.Parameter`.

**Comment by fake-fur** [comment]
ok will do - thanks again so much for your time and help - really appreciated

**Comment by mikependon** [comment]
Btw, if you install the MySql.Data 8.0.20, it will automatically be resolved by VS.

**Comment by fake-fur** [comment]
yes but the 8.0.20 is what causes the problem to appear and it is not possible to downgrade to 8.0.19 so i am stuck with this problem

**Comment by mikependon** [comment]
Just do implement the Tracer and that will give you the full picture of what really happens.

**Comment by fake-fur** [comment]
ok

**Comment by mikependon** [comment]
How about manually copying the `MySqlDbHelper` class (can be found [here](https://github.com/mikependon/RepoDb/blob/master/RepoDb.MySql/RepoDb.MySql/DbHelpers/MySqlDbHelper.cs)) into your solution, remove the syntax error in the SQL text and reinject in your code?

Use the code below to inject it.

```csharp
DbHelperMapper.Add(typeof(MySqlConnection), new ModifiedMySqlDbHelper(), true);
```

The same method is called inside the `MySqlBootstrap.Initialize()`.

Note: You can also debug the codes in your custom DB helper.

**Comment by fake-fur** [comment]
so do i have to implement all 6 million interface methods to write the trace class??

i will try using a custom dbhelper

**Comment by mikependon** [comment]
Implementing a trace is very direct and is very easy. Just create a class that implements the `ITrace` interface. Implement the methods and simply comment the defaultly generated `NotImplementedException` codes.

Then inject your custom trace class when you call the operation (ie: `connection.QueryAll<T>(trace: new CustomTrace());`).

And I suggest I think you need both :)

**Comment by fake-fur** [comment]
will do thanks - sorry for my lack of C# skills

**Comment by fake-fur** [comment]
i think i found the bug - you do not mention table_schema in the query to get columns, this one:

```
SELECT COLUMN_NAME AS ColumnName
	            , CASE WHEN COLUMN_KEY = 'PRI' THEN 1 ELSE 0 END AS IsPrimary
                , CASE WHEN EXTRA LIKE '%auto_increment%' THEN 1 ELSE 0 END AS IsIdentity
                , CASE WHEN IS_NULLABLE = 'YES' THEN 1 ELSE 0 END AS IsNullable
                , DATA_TYPE AS ColumnType /COLUMN_TYPE AS ColumnType/
                , CHARACTER_MAXIMUM_LENGTH AS Size
                , COALESCE(NUMERIC_PRECISION, DATETIME_PRECISION) AS `Precision`
                , NUMERIC_SCALE AS Scale
                , DATA_TYPE AS DatabaseType
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE
	            TABLE_NAME = 'syncchecksums'
            ORDER BY ORDINAL_POSITION
```

so when we have 30 of the same databases called something different, we get multiple versions of the columns which is the exact error - you have to use "and table_schema='database-name'"

then it works

**Comment by mikependon** [comment]
Hmmm. That make sense! I will do update soon or feel free to issue a PR. For now, keep your custom DB helper in your solution. Cheers

**Comment by fake-fur** [comment]
i don't seem to have permissions to add a pull request?

**Comment by mikependon** [comment]
I had added you as collaborator.

**Comment by mikependon** [comment]
Fixed by the user itself via PR #433 - will be a part of RepoDb.MySql > v1.9.0.

Please do let me know if you need a Beta for this, otherwise I will release this together with other enhancements.

**Comment by fake-fur** [comment]
i would love a beta so i can get the app deployed to our testers - thanks so much for all your help and guidance :)

**Comment by mikependon** [comment]
Will issue you a beta later for this fix.

**Comment by mikependon** [comment]
The fix has been deployed via RepoDb.MySql (v1.0.10-beta1). The package can be found [here](https://www.nuget.org/packages/RepoDb.MySql/1.0.10-beta1).
