### ISSUE TITLE
Request: Document strategies for integration tests with RepoDb

### ISSUE THREAD

**Issue by GeeWee** [mikependon/RepoDB#434]
Hey!
We're looking at implementing RepoDb in some of our projects, but I'm not seeing what the optimal strategy for integration testing is.

Optimally we'd like to, in our tests:
- Spin up a new database at the Setup stage
- Add some stuff to it, and test some logic
- Tear down the database afterwards

Is this outside the scope of RepoDb? I can't seem to find any sort of logic that deals with actually creating/tearing down databases. Would you recommend using a third party library for the setup/teardown step?
I think what I'm looking for is a guide akin to [this one](https://www.davepaquette.com/archive/2016/11/27/integration-testing-with-entity-framework-core-and-sql-server.aspx), which is for EF-Core, just for RepoDb.

**Comment by mikependon** [comment]
@GeeWee - TBH, the spinning-up and tearing-down the DB in every instance of Integration Tests would be tedious if you are to use RepoDb. Definitely, you are aiming the `Migrate` feature of EF which I am shunning RepoDb on implementing such features. I would highly recommend you use EF instead to simplify your work.

Though @rdagumampan has a library that could do the migration for you and if you're interested, such library is good to use but you have to write SQLs yourself. The migration does not derived from the models.

You may I ask me how did I do the Integration Tests in RepoDb, I created it myself and the implementations can be found [here](https://github.com/mikependon/RepoDb/blob/master/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/Setup/Database.cs). Then on every test, I call it in the `Setup()` method and `Clean()` method (like [this](https://github.com/mikependon/RepoDb/blob/ca9b58df36fc9d2675c63fdd4d64546e3afc1d69/RepoDb.Core/RepoDb.Tests/RepoDb.IntegrationTests/Operations/SqlConnectionOperationsTest.cs#L23)).

**Comment by mikependon** [comment]
Can this be closed now?

**Comment by GeeWee** [comment]
Yes. The answer is fine, and I'm sure someone else with the same problem can find this issue. Closing.
