### ISSUE TITLE
Force HTTPS on Documentation site

### ISSUE THREAD

**Issue by GeeWee** [mikependon/RepoDB#452]
A lot of the links to Repodb.net aren't https, which leads to insecure connections, and an ugly padlock in the address bar. It might give people the wrong first impression
![image](https://user-images.githubusercontent.com/6381792/83761021-0943a000-a676-11ea-9d80-97141b7bcc73.png)

As Repodb.net is hosted as a Github page, enforcing HTTPS redirection should be as simple as checking a checkbox. Instructions are [here](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)

I've confirmed the site still works under https, by just manually prepending `https://` it to the url.

**Comment by mikependon** [comment]
Can you enable it as a collaborator?

**Comment by mikependon** [comment]
Done enabling https for the site. Thank you for this report :)

**Comment by GeeWee** [comment]
I wasn't able to enable it, but awesome that you did!
Closing.
