### ISSUE TITLE
UpdateAsync on Sqlite

### ISSUE THREAD

**Issue by gtejeda** [mikependon/RepoDB#461]
Hey guys, I just did my very first repository and everything was working perfecting until I got to the update part... I Inserted 4 records with this code:  

        public async Task<string> Insert(Entry entry)
        {
            using (var connection = new SQLiteConnection(ConnectionString))
            {
                return await connection.InsertAsync<Entry, string>(entry);
            }
        }
all perfect...
but then I try to update a single one with this code:

        public async Task Update(Entry entry)
        {
            using (var connection = new SQLiteConnection(ConnectionString))
            {
                await connection.UpdateAsync(entry);
            }
        }

All records get updated (as if I was doing and Update All), I repeated this about 5 times, even deleted the database and retried... I must be missing something, but for the life of me I can't see what it is!

Any ideas?
G

**Comment by mikependon** [comment]
Does the ID is not colliding? Can you try call like below?

`connection.UpdateAsync(entry, entry.Id);`

**Comment by gtejeda** [comment]
Well... I feel silly now :(
you were totally right, my CREATE TABLE script had not auto-generation in place, so, I wasn't sending the Id "trusting" the auto-generation.
your comment made me realized I wasn't sending the Id and when fixed, everything is working perfectly!
I'm happy, thanks again @mikependon, you rock man!

**Comment by mikependon** [comment]
Glad it works on your end then! Just feel free to revert anytime if any problem exists.

**Comment by mikependon** [comment]
Btw, I noticed it earlier that your ID is of type string. It should not be identity then?

**Comment by gtejeda** [comment]
Sorry for the late reply, came to ask a question and only now realized of this message.
Yes, I tend to stay away from db generated stuff and tend to use guids for my ids :)

**Comment by mikependon** [comment]
I am closing this issue now. Please feel free to reopen if you think this is not yet done and/or completed.
