### ISSUE TITLE
Question: Not getting Caching to work

### ISSUE THREAD

**Issue by gtejeda** [mikependon/RepoDB#462]
Hi @mikependon  and guys,
My generic repository is working beautifully (including batch and async operations), but I just realized I'm not getting cached data for some reason.

First I was using a simplified version of the generic repo you showed me like this:
`public class GenericRepository<T>: IGenericRepository<T> where T: Entity
    {
        readonly string ConnectionString;

        public GenericRepository(IConfiguration configuration)
        {
            ConnectionString = configuration.GetConnectionString("LanguageConnectionString");
        }
        public async Task<T> Get(string Id)
        {
            using (var connection = new SQLiteConnection(ConnectionString))
            {
                return (await connection.QueryAsync<T>(x => x.Id == Id)).FirstOrDefault();
            }
        }
......
}`

I added the cachedKey to this and couldn't get it to work, so I switched to the BaseRepository implementation but still nothing...

`public class CachedRepository : BaseRepository<Entry, SQLiteConnection>, ICachedRepository
    {
        public CachedRepository(IConfiguration configuration): base(configuration.GetConnectionString("LanguageConnectionString"))
        {
        }
        public async Task<Entry> Get(string Id)
        {
            using (var connection = new SQLiteConnection(ConnectionString))
            {
                var expiration = 60 * 12;
                var cachedKeyId = "Entry" + Id;
                var qna = (await connection.QueryAsync<Entry>(x => x.Id == Id, 
                            cacheKey: cachedKeyId)).FirstOrDefault();
                return qna;
            }
        }
        public async Task<IList<Entry>> GetAll()
        {
            using (var connection = new SQLiteConnection(ConnectionString))
            {
                var ms = new MemoryCache();
                var Id = "AllCachedEntries";
                var expiration = 60 * 12;
                var qnalist = (await connection.QueryAllAsync<Entry>(cacheKey: Id)).ToList();

                return qnalist;
            }
        }
    }`

I know I'm doing something wrong, but It is really escaping me.

Your help again is greatly appreciated,
Thanks!
Geo

**Comment by mikependon** [comment]
Since you already switched to BaseRepository, then you do not need to open a new connection. Instead, simply use the base methods. Call it directly like `base.Query()`. If you are opening a new connection, please bare in mind that it is a lower level implementation, so you have to maintain your own `ICache` there. Whereas in `BaseRepository` and `DbRepository` it is handled internally. That is on design.

Here is the link: https://repodb.net/feature/caching

**Comment by gtejeda** [comment]
Yup!!!
you were right on the money again.
even easier with baseRepository!

Thanks @mikependon

**Comment by mikependon** [comment]
Please be reminded of the difference between the `BaseRepository` and `DbRepository`. The first one is for entity-based repository and the latter one is for generic repository. Means, in the `DbRepository`, you can use multiple entity together.

We usually use the `BaseRepository` if we are only to work with single table. Let us say table `Customer` and we named the repository as `CustomerRepository`.

We used the `DbRepository` as shared/generic repository. Let us say you have a database named Northwind, then we usually name the repository as `SharedRepository` or `NorthwindRepository` itself.

**Comment by mikependon** [comment]
I am closing this issue now. Please feel free to reopen if you think this is not yet done and/or completed.
