### ISSUE TITLE
Bug?: SqlException: Incorrect syntax near ')'

### ISSUE THREAD

**Issue by nunomcardoso** [mikependon/RepoDB#463]
Greetings.

I came across this error/bug (?) a few times already:
When I call Query() in **BaseRepository<TEntity, TDbConnection>**:
```c#
var collection = new List<int>(); // Count = 0
return Query(e=> collection.Contains(e.Attribute));
```

If the collection is empty it throws this exceptions:
```c#
SqlException: Incorrect syntax near ')'.
Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
```

The SQL code (grabbed from SQL Server Profiler) being generated is:
```sql
SELECT [Attribute], [OtherAttribute] FROM [Table1] WHERE ([Attribute] IN ()) ;
```
Had this issue in March and took this screenshot back then: [https://i.imgur.com/ekmP9RS.png](https://i.imgur.com/ekmP9RS.png)

Is there any solution other than this:
```c#
var collection = new List<int>(); // Count = 0
if(!collection.Any()) 
    return Enumerable.Empty<T>();
return Query(e=> collection.Contains(e.attribute)) 
```

Thanks!

**Comment by mikependon** [comment]
Never I simulated this one yet, but it seems that the collection is empty, so the array parameter is not constructed properly during the query statement creation of the query builder.

The fix is to add a condition in your side before you call the method, however a proposal would be good for this as you are the actual user with real use-case (itself).

Do you want the library to throw you an empty exception or should I skip the execution?

**Comment by nunomcardoso** [comment]
I don't mind adding the condition.

But I think the library should skip the query execution since it would prevent this situations.
The code should have the same behavior with or without items. 

Skip would be ideal.

Thanks!

**Comment by mikependon** [comment]
Thank you for your answer and also for reporting this case. We will assess how to fix this together with your proposed solution. For now, just leave this open.

**Comment by mikependon** [comment]
The fix: It would throw an exception if the list is empty. By having this behavior, we are ensuring that the invalid call will be noticed and fixed by the developer itself, rather than silently skipping the execution. I hope this would work on your end.

**Comment by sellig** [comment]
I will better assume that the RpoDb is enought smart to not append the 'WHERE ([Attribute] IN ()) ' if the list is empty.
It's not an error from the developer.

**Comment by mikependon** [comment]
@sellig - thank you for the push back. Without appending the supposed `WHERE` would trigger an unexpected behavior (i.e: it will return all the records). If we are to call the `BETWEEN`, we are also throwing an exception if the value of the array is more than 2. In anyway, I think, I will just ignore the execution or will just execute it but by having a 'FALSE' expression like `(WHERE 1 = 0)` or something like that.

**Comment by mikependon** [comment]
Btw, just to let you know, EF is doing exactly the same as I tested it now.

```
> SELECT [p].[Id], [p].[Age], [p].[CreatedDateUtc], [p].[DateOfBirth], [p].[ExtendedInfo], [p].[IsActive], [p].[Name] FROM [Person] AS [p] WHERE CAST(1 AS bit) = CAST(0 AS bit)
```

**Comment by sellig** [comment]
I will prefer your implementation having a 'FALSE' expression and so return no record.

**Comment by mikependon** [comment]
I had issued a beta release for you at [RepoDb 1.11.4-beta3](https://www.nuget.org/packages/RepoDb/1.11.4-beta3). Kindly upgrade your copy by simply installing such version.

```
> Install-Package RepoDb -version 1.11.4-beta3
```

**Comment by mikependon** [comment]
@nunomcardoso and @sellig , I am closing this issue now. Please revert if you have questions with regards to this issue. Thanks
