### ISSUE TITLE
Question: ExecuteQuery stored procedure 

### ISSUE THREAD

**Issue by MSMSalim** [mikependon/RepoDB#474]
Hi,

Am spiking repodb and was wondering if we can use async for executing stored procedure with ExecuteQuery?

Thanks

**Comment by mikependon** [comment]
Yes. All methods has equivalent 'Async' methods. Though here is the 'Sync' [documentation](https://repodb.net/operation/executequery). Here is the actual [code-line](https://github.com/mikependon/RepoDb/blob/a9a22722fb23a63724dcf53e479d6be3d7610693/RepoDb.Core/RepoDb/Extensions/DbConnectionExtension.cs#L359) for that.
