### ISSUE TITLE
Singular model name and plural table name is not working with SQL Server.

### ISSUE THREAD

**Issue by Arnab-Developer** [mikependon/RepoDB#480]
If my model name is 'Student' and table name is 'Students' then the QueryAll, Query, Insert, Update and Delete methods are not working. Table names are normally plural and model name is normally singular. I am using SQL Server. This is supported by Entity Framework as well. Is there any way so that we can do this with RepoDb?

**Comment by mikependon** [comment]
Please use the following mapping.

Via [Fluent Mapping](https://repodb.net/feature/implicitmapping):

```csharp
FluentMapper
    .Entity<Student>()
    .Table("[dbo].[Students]", true);
```

Ensure that you call it on any bootstrapper you have (i.e.: `Startup()` method).

Or, via [Class Mapping](https://repodb.net/feature/classmapping):

```csharp
[Table("Students", "dbo")]
public class Student
{
    ...
}
```

**Comment by Arnab-Developer** [comment]
I am using ASP.NET Core application. Inside the ```Startup.cs``` ```Configure``` method I have done the following...

    SqlServerBootstrap.Initialize();
    FluentMapper.Entity<Student>().Table("Students");

...and it is working. 

https://github.com/Arnab-Developer/repodb-demo

Thanks.
