### ISSUE TITLE
Enhancement: Using async DbFieldCache

### ISSUE THREAD

**Issue by SergerGood** [mikependon/RepoDB#481]
A large number of asynchronous implementations use a synchronous DbFieldCache call because the calls are used through proxy classes (e.g. FunctionFactory, FunctionCache)

**Comment by mikependon** [comment]
@SergerGood - the [DbFieldCache.GetAsync](https://github.com/mikependon/RepoDb/blob/b1e0b5a9a0d9ec938a33688cefe20268d517d7e1/RepoDb.Core/RepoDb/Operations/DbConnection/UpdateAll.cs#L1035) is properly called in every Async operation. The calls inside the [FunctionFactory](https://github.com/mikependon/RepoDb/blob/b1e0b5a9a0d9ec938a33688cefe20268d517d7e1/RepoDb.Core/RepoDb/Reflection/FunctionFactory.cs#L119) is most likely taken on the cache (not really from the DB itself). Both the caching of the 'Async' and 'Sync' methods are same when it comes to the 'Key'. I would say that this should not be a concern.

**Comment by mikependon** [comment]
To explain further, when the actual asynchronous method (i.e.: `InsertAsync`, etc) is being called, it then calls the `DbFieldCache.GetAsync()` method first. That call caches the database fields of that target entity. Further call to the method `DbFieldCache.Get()` or `DbFieldCache.GetAsync()` will then take it from the cache and not to the DB, for as long the passed key is identitical.

**Comment by SergerGood** [comment]
OK, I understood.
And what about the chain of calls BulkDeleteAsync -> DataEntityDataReader -> DbFieldCache.Get

**Comment by mikependon** [comment]
I would say 'same' at all cases. This [line](https://github.com/mikependon/RepoDb/blob/395794f5ab453db587267f2e815d1daf47ae19a6/RepoDb.Extensions/RepoDb.SqlServer.BulkOperations/RepoDb.SqlServer.BulkOperations/System.Data.SqlClient/SqlConnection/BulkDelete.cs#L1253) for example is calling it first, then all the succeeding calls would be taken from the cache even by using the 'sync' or 'async' methods for as long the key is identitical. So this is on a least of the problem. But please do share the specific problem that we can fix if you saw it.

**Comment by SergerGood** [comment]
I'm talking about a call [1](https://github.com/mikependon/RepoDb/blob/395794f5ab453db587267f2e815d1daf47ae19a6/RepoDb.Extensions/RepoDb.SqlServer.BulkOperations/RepoDb.SqlServer.BulkOperations/System.Data.SqlClient/SqlConnection/BulkDelete.cs#L434) -> [2](https://github.com/mikependon/RepoDb/blob/395794f5ab453db587267f2e815d1daf47ae19a6/RepoDb.Extensions/RepoDb.SqlServer.BulkOperations/RepoDb.SqlServer.BulkOperations/System.Data.SqlClient/SqlConnection/BulkDelete.cs#L447) -> [3](https://github.com/mikependon/RepoDb/blob/395794f5ab453db587267f2e815d1daf47ae19a6/RepoDb/RepoDb/DataEntityDataReader.cs#L56) -> [4](https://github.com/mikependon/RepoDb/blob/395794f5ab453db587267f2e815d1daf47ae19a6/RepoDb/RepoDb/DataEntityDataReader.cs#L77)

**Comment by mikependon** [comment]
That is a bug and is a nice catch! There should be a call to the `DbFieldCache.GetAsync()` method before this [line](https://github.com/mikependon/RepoDb/blob/395794f5ab453db587267f2e815d1daf47ae19a6/RepoDb.Extensions/RepoDb.SqlServer.BulkOperations/RepoDb.SqlServer.BulkOperations/System.Data.SqlClient/SqlConnection/BulkDelete.cs#L447). The call should be like below.

```csharp
await DbFieldCache.GetAsync(connection, ClassMappedNameCache.Get<TEntity>(), transaction, true);
```

That is just a trick invocation to enable the cache in advance as I did the same with [here](https://github.com/mikependon/RepoDb/blob/395794f5ab453db587267f2e815d1daf47ae19a6/RepoDb.Core/RepoDb/Extensions/DbConnectionExtension.cs#L410). Though the correct way is to add a method named `Initialize()` and `InitializeAsync()` within the `DataEntityDataReader` class and explicitly call it.

Happy if you could do that for RepoDb :)

**Comment by mikependon** [comment]
Working on this now.

**Comment by mikependon** [comment]
@SergerGood - Thank you for your PRs. This enhancement is now a part of the latest release at [RepoDb.Core (v1.11.6)](https://www.nuget.org/packages/RepoDb/1.11.6),[RepoDb.SqlServer.BulkOperations (v1.0.13)](https://www.nuget.org/packages/RepoDb.SqlServer/1.0.13) and [RepoDb.SqlServer.BulkOperations (v1.0.14)](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.0.14).

**Comment by SergerGood** [comment]
@mikependon - Glad to do something useful. Thank you to.
