### ISSUE TITLE
An expression was expected after '('. on Initialize for ReporDB.SqlServer

### ISSUE THREAD

**Issue by vzaffiro** [mikependon/RepoDB#488]
Running through the Getting Started Guide and followed the below steps. 

1. Installed RepoDb.SqlServer(1.0.12) through Package Manager.
2. installed RepoDb.SqlServer.BulkOperations(1.0.13) 
3. in the package Manager Console run RepoDb.SqlServerBootstrap.Initialize();

Received the below error: 

`At line:1 char:38
+ RepoDb.SqlServerBootstrap.Initialize();
+                                      ~
An expression was expected after '('.
PM>`

**Comment by mikependon** [comment]
It seems you executed it in Package Manager Console. The code `RepoDb.SqlServerBootstrap.Initialize(); ` must be invoked in any of your starter class (i.e.: Startup.cs, Program.cs Main() method), not through the Package Manager Console.

**Comment by mikependon** [comment]
Hi @vzaffiro , do you still encounter the problem?

**Comment by mikependon** [comment]
Closing this one for now. Please feel free to open if you still have encountered a problem. Thanks!
