### ISSUE TITLE
Question: Question on how to convert query field and value to DbTypes for comparison

### ISSUE THREAD

**Issue by fenilrathod** [mikependon/RepoDB#491]
I am finding a way to convert/cast Query Field and it's value to DBType. This is needed while comparing Dates ignoring time. I guess it can be achieved if we cast field to date and compare afterwards.

There is a SqlServerConvertFieldResolver and it can be used for this. But it needs to be used along with custom statement builder. Is there any other simple way to just include casting requirements into QueryField directly?

**Comment by mikependon** [comment]
Do you really need to cast or just a type mapping? There is no way you can cast a `QueryField`, but it should be covered by type mapping if you do so. Have you tried the `TypeMap` atrribute decoration? Or the `TypeMapper.Add` or `FluentMapper.Type<TType>()` method.

**Comment by fenilrathod** [comment]
Basically I need all rows of given date. Database column gas date with
time. And I believe CAST as DATE needed to ignore time part of database
column having type DateTime.

Other workaround I just thought is to use Between operator and pass
QueryField value having dates along with time. Like 2020-07-28 00:00 to
2020-07-28 23:59. I will give it a try.

**Comment by mikependon** [comment]
Great. Now I fully understand your case. I think it's pretty normal to just use the expression-based query on your case, and/or if you're adventurous enough, diving into `QueryField` as you use now is much better.

Via Expression:

```csharp
var from = DateTime.UtcNow.AddMonths(-1).Date;
var to = DateTime.UtcNow;
using (var connection = new SqlConnection(ConnectionString))
{
     connection.Query<EntityModel>(e => e.DateTimeColumn >= from && e.DateTimeColumn <= to);
}
```

Or Via QueryField:

```csharp
var from = DateTime.UtcNow.AddMonths(-1).Date;
var to = DateTime.UtcNow;
using (var connection = new SqlConnection(ConnectionString))
{
     connection.Query<EntityModel>(new QueryField("DateTimeColumn", Operation.Between, new[] { from, to }));
}
```

That kind of query would give you the correct data from exactly a month from now (UTC).

**Comment by fenilrathod** [comment]
Right. I've used QueryField with Between operator and it is working fine. I was into more SQL scripting zone previously :) 
Thanks for your time!

**Comment by mikependon** [comment]
No worries and thanks for confirming. Closing this one for now.
