### ISSUE TITLE
Bug: Typed "UpdateAsync" fails for composite key table

### ISSUE THREAD

**Issue by asleire** [mikependon/RepoDB#493]
I am using package `FluentMigrator.Runner.SqlServer` version `3.2.7`

The following code:
```
IDbConnection db = ...;
                    
await db.UpdateAsync(
  dbo,
  d => d.SettingCollectionKey == collection.Key && d.Key == value.Key
);
```

<details><summary>`dbo` Model</summary>

```
    [Table("SettingCollectionValue")]
    internal class SettingCollectionValueDbo
    {
        public string? SettingCollectionKey { get; set; }

        public string? Key { get; set; }

        public string? Label { get; set; }

        public string? Value { get; set; }
    }
```
</details>

Fails with error `Microsoft.Data.SqlClient.SqlException (0x80131904): The variable name '@SettingCollectionKey' has already been declared. Variable names must be unique within a query batch or stored procedure.` 

A workaround is using the non-typed `UpdateAsync` overload
<details><summary>Workaround</summary>

```
await db.UpdateAsync(
    "SettingCollectionValue",
    new
    {
        dbo.Label,
        dbo.Value,
    },
    new[]
    {
        new QueryField("SettingCollectionKey", dbo.SettingCollectionKey),
        new QueryField("Key", dbo.Key),
    }
);
```
</details>

Possibly related: https://github.com/mikependon/RepoDb/issues/485

**Comment by mikependon** [comment]
Yes it is related to that issue. Though, it is known that composite key is not supported in RepoDb due to the constraints needed in other cases.

Anyway, I just tested this one, the Expression-based approach seems to have a bug. Have you tried the approach below? It should work at-least.

```
await db.UpdateAsync(
	dbo,
	new { collection.Key, value.Key }
);
```

I will do prioritize the Expression-based bug.

**Comment by asleire** [comment]
That's a much better workaround. Thanks!

**Comment by mikependon** [comment]
@asleire - thanks. Please do let me know if that works on your end.

**Comment by asleire** [comment]
It does work

**Comment by mikependon** [comment]
@asleire - though the composite keys is not supported in RepoDb, but the bug in relation to the targeted expression-based for composite keys has been fixed on the latest deployment ([RepoDb.SqlServer (v1.0.13)](https://www.nuget.org/packages/RepoDb.SqlServer/1.0.13)). Would you be able to validate on your side?

```
> Install-Package RepoDb.SqlServer -version 1.0.13
```

**Comment by asleire** [comment]
It works now. Thanks a ton! 

Great library by the way. Composite keys work fine when using `where`-objects and expressions. I haven't found other (small) libs that support it so easily

**Comment by mikependon** [comment]
You can read our limitations page to understand further the composite keys limitation. Thanks BTW

**Comment by asleire** [comment]
I understand the limitation in the case when there is a compound key seperate from the primary key. In my case the primary key is a compound key, so it should be possible for RepoDb to support that?

My use case is quite simple. I have two related entities:

```
class Collection {
  string id;
}

class CollectionItem {
 string collectionId;
 string itemId;
}
```
In my case it doesn't make sense to assign a globally unique ID to collection item. The item has no purpose outside the context of its Collection. It only needs to be unique within it's collection, so I've set the primary key to be a compound key `(collectionId, itemId)`

**Comment by mikependon** [comment]
I would say that if you are using 'dynamics' or 'QueryObjects', then that is supported. But by default, Fluent methods will not support that, specially the return value of the push operations. Such operation requires a scalar value on the resultsets. Though the data may be saved properly in the DB, but the returned ID will not be the value of the CompoundKey or CompositeKey.

**Comment by asleire** [comment]
One typically don't need identity columns when using a composite primary key. I pass pre-set values for `collectionId` and `itemId` when I insert.

`await db.InsertAsync(dbo, transaction: tx);` works as expected - all columns are set and I don't need any return value
`await db.UpdateAsync(dbo, transaction: tx);` however attempts to update all entries matching on `collectionId`, even though the primary key is (collectionId, itemId)
`await db.DeleteAsync(dbo, transaction: tx);` deletes all entries matching on `collectionId`, even though the primary key is (collectionId, itemId)

**Comment by mikependon** [comment]
Yes, the same problem as reported by the other guy in the other issue. I also explained such case in the limitation page. It can be fixed if you use an expression-based or QueryObjects, but you have to pass a value in the 'where' argument to both operations.

**Comment by asleire** [comment]
Yes, that is what I currently do. I was trying to explain that I don't understand why you can't support for instance `await db.DeleteAsync(dbo, transaction: tx);` when the dbo contains a _composite primary key_. The library already reads primary key from the table schema -- wouldn't it just be a matter of including all the primary key columns instead of the first one in the generated `where` filter? 

Of course I don't know the RepoDb internals, I'm just curious about the limitations-page statement: 
>  The default support to this will never be implemented as RepoDb tend to sided the other scenario that is forcefully eliminating this use-case.

**Comment by mikependon** [comment]
RepoDb does cache the PK per table and on each table, it assumes a single PK column (PrimaryKeyCache, PrimaryMapper, PrimaryResolver and etc). This pre-cached PK is used to determine the qualifiers. RepoDb uses this as well being a result value to the other usage like Insert, Merge and Upsert. When you have a composite and/or compound keys, you are require to pass 2 values while if it is a normal PK, you only pass 1. RepoDb however does not know how to map it based on its caching mechanism, though it can be called properly via dynamics, expression or query objects. I am also looking at the frequency of the use-case, passing a single scalar value is a very common use-case than having a composite and/or compound keys. I hope that explains.

**Comment by mikependon** [comment]
But of course, I also said "for now"! :)

**Comment by asleire** [comment]
Yup, thanks! So you _could_ support this if you wanted to. The limitation page made it sound like there was a restriction out of your control, which is what had me curious. :) 

Thanks again!

**Comment by mikependon** [comment]
That's what I said, I tend to support the other use-case that could eliminate this. How should I delete a row for composite keys and/or compound keys? Should I do it like below?

```csharp
connection.Delete<Person>(new [] { Value1, Value2 });
```

And how should I return the ID back for insert?

```csharp
var id = connection.Insert(new Person { Name = "John Doe" });
```

That's why I said it cannot be supported as it is a rarely case. Though, it needs an architectural change if I am to push it.

So the expression-based, dynamic-based and query-object-based would support it, like below.

```csharp
connection.Delete<Person>(e => e.Column1 == Value1 && e.Column2 == Value2);
```
