### ISSUE TITLE
Request: The switch from System.Data.SQLite.Core to Microsoft.Data.SQLite.Core is a pretty big breaking change

### ISSUE THREAD

**Issue by PrimaForge** [mikependon/RepoDB#497]
As soon as I tried to upgrade to RepoDb 1.0.15 and had to downgrade as I started to break stuff. Microsoft.Data.SQLite.Core is not as mature as System.Data.SQLite.Core and does not support some of its features at the moment such as (Case-sensitive parameter names) https://github.com/dotnet/efcore/issues/18861 nor does it support (Connection Pooling) https://github.com/dotnet/efcore/issues/13837 among other things.

Its just missing things that I and others are used to having, System.Data.SQLite.Core is just more mature and supports things not implemented in Microsoft.Data.SQLite.Core yet. 

Was just wondering the reason for this change and If there was a way I could use System.Data.SQLite.Core without having a dependency on Microsoft.Data.SQLite.Core?

**Comment by mikependon** [comment]
The old version is using only the `System.Data.SQLite`, not the `System.Data.SQLite.Core`. So that's something that we need to remove from the RepoDb versions specially that it is still referring the old EF library.

Yes, you may be able to use the `System.Data.SQLite.Core` still, but using your own bootstrap. Though I have not yet tested it, but that would still be the same.

But since the RepoDb version will be defaulted to `Microsoft.Data.SQLite.Core`, then there is always a reference towards that library. I hope you can live with it.

**How to initialize the `System.Data.SQLite.Core`?**

By default, you use to call the `RepoDb.SqLiteBootstrap.Initialize()`. This will only be defaulted to `Microsoft.Data.SQLite.Core`, to support the `System.Data.SQLite.Core`, you would need to the code below.

```csharp
// Map the DbSetting
DbSettingMapper.Add(typeof(SQLiteConnection), new SqLiteDbSetting(), true);

// Map the DbHelper
DbHelperMapper.Add(typeof(SQLiteConnection), new SqLiteDbHelper(), true);

// Map the Statement Builder
StatementBuilderMapper.Add(typeof(SQLiteConnection), new SqLiteStatementBuilder(), true);
```

Such calls equate the bootstrapper calls.

**Comment by PrimaForge** [comment]
Yes I am fine with that as dependency as long as I am still able to use System.Data.SQLite.Core which seems to be the case however, I am getting a exception on this line:

`StatementBuilderMapper.Add(typeof(SQLiteConnection), new SqLiteStatementBuilder(), true);`

Exception: System.NullReferenceException: 'The database setting cannot be null.'

I do have a custom SqliteDbSetting class

```
    public sealed class SqLiteDbSetting: BaseDbSetting
    {
        public SqLiteDbSetting()
        {
            AreTableHintsSupported = false;
            AverageableType = typeof(double);
            ClosingQuote = "]";
            DefaultSchema = null;
            IsDirectionSupported = false;
            IsExecuteReaderDisposable = true;
            IsMultiStatementExecutable = true;
            IsPreparable = true;
            IsUseUpsert = true;
            OpeningQuote = "[";
            ParameterPrefix = "@";
            SchemaSeparator = ".";
        }
    }
```

**Comment by mikependon** [comment]
@FutureTD - I am now simulating your use-case. Few moment please :) Thanks!

**Comment by mikependon** [comment]
@FutureTD - I think, it requires you to call the `RepoDb.SqLiteBootstrap.Initialize()` method first. That makes it a bug on the initialization.

**Comment by mikependon** [comment]
I think, I need to revert to use the `System.Data.SQLite.Core` instead as the other user has opened up the same issue as you. They also have referencing problem with the latest release. Would you be able to wait for the new release?

**Comment by PrimaForge** [comment]
Ah ok I just changed the line to:

`StatementBuilderMapper.Add(typeof(SQLiteConnection), new SqLiteStatementBuilder(new SqLiteDbSetting()), true);`

and the exception was gone

**Comment by PrimaForge** [comment]
Yes, I would be able to wait, thank you

**Comment by mikependon** [comment]
I saw that, but the problem is `MDS` made the breaking changes on the `.NET CLR Type` mapping. So there are coercion problem still. Unless your solution works, then I am fine retaining with `MDS`, otherwise I have to revert back to `SDS`.

**Comment by PrimaForge** [comment]
My project seems to work based on the little testing I did, However SDS is probably used more MDS so I don't know. However, Im not sure how switching to MDS will effect other users.

**Comment by mikependon** [comment]
A new release has been pushed. Please install the [RepoDb.SqLite (v1.0.16)](https://www.nuget.org/packages/RepoDb.SqLite/1.0.16).

```
> Install-Package RepoDb.SqLite -version 1.0.16
```

Both the 'SDS' and 'MDS' are referenced on the package. The same strategy has been made with RepoDb.SqlServer package. Up until the community decided in the near future, one may be eliminated soon. That's still unclear when.

**Comment by mikependon** [comment]
Have you tested your solution based on the latest release? Planning to close this ticket soon. Thanks

**Comment by PrimaForge** [comment]
Yes it works fine, Thanks for your hard work.

**Comment by mikependon** [comment]
@FutureTD , thank you for verifying the fix.
