### ISSUE TITLE
Sqlite MDS "No coercion operator" exception 

### ISSUE THREAD

**Issue by bcssov** [mikependon/RepoDB#513]
Not sure if you really consider this a bug. I've tried using the sample from this #437 issue and have switched to MDS in the sample:
```using (var connection = new SqliteConnection("Data Source=:memory:"))```

By running the sample the following exception is being thrown:
```No coercion operator is defined between types 'System.String' and 'System.DateTime'.'```

Using the default provider does not result in an exception. If I enable Automatic conversion, everything works. I'm merely reporting this as a secondary issue I discovered while trying to figure out my main problem.

**Comment by mikependon** [comment]
There are difference when it comes to `DateTime` in `MDS` and `SDS,` this is a part of the upgrades of `MDS`. Even in our Integration Tests, we purposely did it.

- [MdsCompleteTable.cs](https://github.com/mikependon/RepoDb/blob/master/RepoDb.SqLite/RepoDb.SqLite.IntegrationTests/Models/MdsCompleteTable.cs)
- [SdsCompleteTable.cs](https://github.com/mikependon/RepoDb/blob/master/RepoDb.SqLite/RepoDb.SqLite.IntegrationTests/Models/SdsCompleteTable.cs)

There is no way we can do this, but to use the `Automatic` conversion. Would you be able to that?

FYI: We are assessing whether we should enable the 'Automatic' conversion by default, same as the other ORM. We guess, being a strict in RepoDb is good, but it may trigger a lot of coercion problem to all systems that tries to move to this ORM (like your use-case).

**Comment by bcssov** [comment]
It's not a problem for me to use that, hence the reason why I mentioned that you might not be considering this as a bug. Feel free to close.

**Comment by mikependon** [comment]
@bcssov - we will as well place a section on README pertaining to COERCION if we end-up not enabling the `Automatic` conversion by default. Will close this ticket now. Thanks for reporting.
