### ISSUE TITLE
Enhancement: Add the dynamic ExecuteQuery method in the DbRepository.

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#517]
Add the `IDbConnection` extended method named `dynamic ExecuteQuery()` into the `DbRepository` object. This is to make the `DbRepository` object more align with the `IDbConnection` object extension methods.

Here is the `IDbConnection` signature.

```csharp
public static IEnumerable<dynamic> ExecuteQuery(this IDbConnection connection, string commandText, object param = null, CommandType? commandType = null, int? commandTimeout = null, IDbTransaction transaction = null);
```

**Comment by mikependon** [comment]
The fix is now available at [RepoDB v1.12.0-beta1](https://www.nuget.org/packages/RepoDb/1.12.0-beta1).

**Comment by gkn06** [comment]
@mikependon  Other `IDbConnection` extended method named `ExecuteQueryMultiple` is not yet added in the DbRepository. 
Is it possible to add that too?

Signature:
```csharp
public static QueryMultipleExtractor ExecuteQueryMultiple(this IDbConnection connection, string commandText, object param = null, CommandType? commandType = null, int? commandTimeout = null, IDbTransaction transaction = null);
```

**Comment by mikependon** [comment]
@gkn06 - absolutely. Would you be able to create a separate issue for this request for tracking purposes? Thanks
