### ISSUE TITLE
Request: Add caching for ExecuteQuery and ExecuteQuery<TEntity>

### ISSUE THREAD

**Issue by BieleckiLtd** [mikependon/RepoDB#522]
```
var users = connection.ExecuteQuery<User>("SELECT * FROM [dbo].[Users];");
var users = connection.ExecuteQuery<User>("SELECT * FROM [dbo].[Users];", cache: Cache, cacheKey: "AllUsers"); // no overload
```

**Comment by mikependon** [comment]
This has been discussed in the past internally, it is our intention to not support the cache in the result of `ExecuteQuery` operation. One of the reason is to avoid the collisions as cache item should be coupled to an `TEntity` type. This simple use-case could trigger a lot of undesired behavior, TBH.

Think of a single scenario like below. You execute a query and cache the result by passing your `cacheKey`.

```csharp
var users = connection.ExecuteQuery<User>("SELECT * FROM [dbo].[Users];", cache: Cache, cacheKey: "AllUsers");
```

But, you can also pass the same key even though you changed the SQL statement.

```csharp
var users = connection.ExecuteQuery<User>("SELECT * FROM [dbo].[Customers];", cache: Cache, cacheKey: "AllUsers");
```

Though, we know that we can use the SQL statement as the key for cache, but that is something up for discussion. Maybe we can start over on this request again.

**Comment by BieleckiLtd** [comment]
I thinks risk would not be different than what we currently can do with QueryAll for instance:
```
var users1 = connection.QueryAll(tableName: "[UsersTbl]", cache: Cache, cacheKey: "AllUsers");
var users2 = connection.QueryAll(tableName: "[UsersView]", cache: Cache, cacheKey: "AllUsers");
```

> we can use the SQL statement as the key for cache

That is even cooler idea, because `cacheKey: "AllUsers"` parameter won't be needed

**Comment by mikependon** [comment]
@BieleckiLtd - you might be correct as the `QueryAll` has been extended to support the `tableName` argument, up for upcoming release. I think, it is good to include this one if we are to make the next beta release. Atleast, your request is a bit perfect in our release timing.

**Comment by BieleckiLtd** [comment]
For me caching own queries would be a killer feature that Dapper doesn't have out of the box, and man, I just like writing my own sql.

**Comment by mikependon** [comment]
Thanks! Since this is also a part of our discussion historically (internally) and you requested it, I guess, we will include this on the next beta release. That is being said.

**Comment by mikependon** [comment]
Which do you like from the 2 below?

This one?

```csharp
var users = connection.ExecuteQuery<User>("SELECT * FROM [dbo].[Users];", cache: Cache, cacheKey: "AllUsers");
```

Or this one?

```csharp
var users = connection.ExecuteQuery<User>("SELECT * FROM [dbo].[Users];", cache: Cache, isCacheResult: <true|false>);
```

The latter one uses the SQL text as the cache key - in binary form. I prefer the first 1 for simplicity and uniformity.

**Comment by BieleckiLtd** [comment]
I think first is more self-explanatory

**Comment by mikependon** [comment]
Integration Test will soon to follow.

**Comment by mikependon** [comment]
@BieleckiLtd - The fix is now available at [RepoDB v1.12.0-beta1](https://www.nuget.org/packages/RepoDb/1.12.0-beta1) and [RepoDb.SqlServer v1.1.0-beta1](https://www.nuget.org/packages/RepoDb.SqlServer/1.1.0-beta1).

**Comment by mikependon** [comment]
Closing this ticket now. Kindly let us know if you still have questions and concerns. Thanks

**Comment by BieleckiLtd** [comment]
Works as expected. Much appreciated!
