### ISSUE TITLE
Request: Completely expose the 'fields' argument in the 'BatchQuery<T>', 'Query<T>', 'Insert<T>', 'Merge<T>' and 'Update<T>' operations (and all its Batch operations).

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#523]
As requested by the community from the GitterChat.

![image](https://user-images.githubusercontent.com/591015/90908741-0767be00-e3d5-11ea-8746-d33718a327d4.png)

**Comment by mikependon** [comment]
The fix is now available at [RepoDB v1.12.0-beta1](https://www.nuget.org/packages/RepoDb/1.12.0-beta1) and [RepoDb.SqlServer v1.1.0-beta1](https://www.nuget.org/packages/RepoDb.SqlServer/1.1.0-beta1). FYI: @alper-atay

**Comment by alper-atay** [comment]
> The fix is now available at [RepoDB v1.12.0-beta1](https://www.nuget.org/packages/RepoDb/1.12.0-beta1) and [RepoDb.SqlServer v1.1.0-beta1](https://www.nuget.org/packages/RepoDb.SqlServer/1.1.0-beta1). FYI: @alper-atay

Thanks. I think changed everything on DbStatute. Now can't compilable but will. Reworked my query system for operations. If nothing goes wrong, I'll finish the weekend. Finally I set up the structure in my mind.

**Comment by mikependon** [comment]
Closing this ticket now. Thanks!
