### ISSUE TITLE
Request: F# - Consider the Anonymous Types in the Query and QueryAll operation

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#536]
In C#, there is no way to inferred the anonymous types within the generic type argument when calling the generic methods (i.e: [ExecuteQuery&lt;TEntity&gt;(SQL)](https://repodb.net/operation/query), [Query&lt;TEntity&gt;(tableName)](https://repodb.net/operation/query),[QueryAll&lt;TEntity&gt;(tableName)](https://repodb.net/operation/queryall) and [QueryMultiple&lt;T1, T2, ..., T7&gt;](https://repodb.net/operation/querymultiple)).

However, in F# the call is possible. See the screenshot below, provided by @isaacabraham.

**Working Call:**

![image](https://user-images.githubusercontent.com/591015/91862515-5a136680-ec6e-11ea-930d-5d287a6cfaaf.png)

**Non-working Call:**

![image](https://user-images.githubusercontent.com/591015/91862555-68fa1900-ec6e-11ea-94de-3295a67b24ce.png)

This User Story will enable the library to consider the support to the Anonymous Types (or Anonymous Records) when calling the mentioned method above.

**Comment by mikependon** [comment]
**Note:** First screenshot works. Second one fails with "Value cannot be null (Parameter 'source')".

**Comment by mikependon** [comment]
The fix is now available at [RepoDb v1.12.0-beta2](https://www.nuget.org/packages/RepoDb/1.12.0-beta2).

**Comment by AngelMunoz** [comment]
Glad this was quickly implemented
I just tested it seems to work like a charm
![image](https://user-images.githubusercontent.com/8684875/91938424-39b8cb80-ecb1-11ea-9d9a-1e77ba3c49b3.png)

I'll let you know if I find any issues, also I'll try to send a PR to the F# sample later today with precisely this change

**Comment by mikependon** [comment]
@AngelMunoz - thanks! Yes, please do comments all the problems you found during your penetration tests on this User Story.

**Comment by mikependon** [comment]
Closing this ticket now. Thanks
