### ISSUE TITLE
Question: Specific Columns in Query<TEntity>

### ISSUE THREAD

**Issue by rapthi** [mikependon/RepoDB#545]
Hello,

In a DbRepository<SqlConnection>, I am trying to get a specific column. Here is the code :

```
public class PersonRepository : DbRepository<SqlConnection>, IPersonRepository
{
        public PersonRepository() 
            : base(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)
        { }

        public string GetName(int personId) 
        {
                var field = Field.Parse<Person>(e => new
               {
                     e.Name,
               });
               return Query<Person>(f => f.PersonId == personId, fields: field).FirstOrDefault();
        }
}
```

The "fields" param is not implemented apparently... But how can I achieve this?

Sorry, but the documentation didn't really help me for that...

Thanks for your help

**Comment by mikependon** [comment]
Thanks for reading the documentation, we tried to update it to the latest code we had. Anyway, it is implemented on the latest [beta releases](https://github.com/mikependon/RepoDb/blob/c59b4e3889be3ff3c3ac0cb1c4cabda7666f0e23/RepoDb.Core/RepoDb/Operations/DbConnection/Query.cs#L47) for the upcoming version `v1.12.0`. This is just newly released!

Would you be able to install the version [RepoDb v1.12.0-beta2](https://www.nuget.org/packages/RepoDb/1.12.0-beta2)?

```csharp
> Install-Package RepoDb -version 1.12.0-beta2
```

I would highly recommend to as well use the newly released beta package for the other DB provider libraries (i.e: [RepoDb.SqlServer](https://www.nuget.org/packages/RepoDb.SqlServer/1.1.0-beta1), [RepoDb.SqlServer.BulkOperations](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.1.0-beta1), etc).

**Comment by rapthi** [comment]
Thanks for your fast reply.

Updating the NuGet did the trick! Thank you so much!

**Comment by mikependon** [comment]
Hey @rapthi, we are closing this ticket for now. Please do let us know if there are any more problems. Thanks
