### ISSUE TITLE
Question: Oracle support

### ISSUE THREAD

**Issue by kbilsted** [mikependon/RepoDB#560]
Hi what is the current status with regards to supporting Oracle db? And what are the future plans ?

**Comment by mikependon** [comment]
Linking: #478 #459 

There has been a series of request in relation to this. Though it is not that difficult to extend the library for Oracle, but to be honest, this is not yet on the timeline as the other DB providers features are still on float.

As we are buying our time, and base on the current position of the library, we find it more important to stabilize the Bulk Operations of MySQL and PostgreSQL soon. Also, we are in the middle of assessment whether to fully introduce the JOIN support.

Though, this does not mean that we are not supporting the Oracle, we are planning it.

**Comment by rhuijben** [comment]
A little late response but I have a few things against Oracle working on https://github.com/ampscm/repodb
Help welcome to get this to fully supported and optimized.

Currently I'm focusing on 'working', but this will take a lot of testing to get this to fully supported like the very stable SqlServer and Postgresql implementations
