### ISSUE TITLE
Docs - Typo - Where to report this?

### ISSUE THREAD

**Issue by rledyard** [mikependon/RepoDB#608]
On the page https://repodb.net/operation/executequery,
in the "Typed Results" section, 
in the second code block, there is the line:
var names = connection.ExecuteQuery ... where the type "long" is used as TEntity.
I believe it should be "string" instead.

**Comment by mikependon** [comment]
Hey thanks, it is [here](https://github.com/mikependon/RepoDB.NET/blob/master/pages/operations/executequery.md). Glad if you could PR?

**Comment by rledyard** [comment]
Thanks Mike. I would have done a PR, but I didn't know where to find that page. Now I do :)

**Comment by mikependon** [comment]
@rledyard - no worries. Please do not hesitate to do a PR if you found some typo or even coding error on our samples. Thank you for reporting this incident.
