### ISSUE TITLE
Sql Server Authentication issue

### ISSUE THREAD

**Issue by TunayT** [mikependon/RepoDB#62]
"Server=.\SqlExpress;Database=TestDB;User Id=sa;Password=1" cannot connect to server.
But SqlConnection works with same connection string. When I debug, Password parameter is missing on RepoDb connection. Issue can depend be on Turkish language. We have I,İ,ı,i letters.

**Comment by mikependon** [comment]
Hi @TunayT , can you share some of the codes you used? Including the implementation of your from connectionstring initialization until the connection opening? Thanks!

**Comment by TunayT** [comment]
Here is the code, **thank you**.

        var conStr = @"Server=.\SqlExpress;Database=TestDB;User Id=sa;Password=1";
            using (SqlConnection con=new SqlConnection(conStr))
            {
                con.Open();
                con.Close();
            }
            //upto here no problem

            using (var con = new SqlConnection(conStr).EnsureOpen())
            {
                con.Insert<User>(new User()); //this is not work
            }

            //this is work
            conStr = @"Server=.\RSSQL;Database=DecorDB;Integrated Security=SSPI;";
            using (SqlConnection con = new SqlConnection(conStr))
            {
                con.Insert<User>(new User());
            }

**Comment by TunayT** [comment]
var conStr = @"Server=.\SqlExpress;Database=TestDB;User Id=sa;Password=1";
        using (SqlConnection con=new SqlConnection(conStr))
        {
            con.Open();
            con.Close();
        }
        //upto here no problem

        using (var con = new SqlConnection(conStr).EnsureOpen())
        {
            con.Insert<User>(new User()); //this is not work
        }

        //this is work
        conStr = @"Server=.\RSSQL;Database=TestDB;Integrated Security=SSPI;";
        using (SqlConnection con = new SqlConnection(conStr))
        {
            con.Insert<User>(new User());
        }

**Comment by mikependon** [comment]
The 'EnsureOpen()' method is being called inside 'Insert' operation as well. But thank you for this, I will get back to this issue once I can isolate this on my 'DEV' environment. We will get back to you ASAP.

**Comment by mikependon** [comment]
Would you mind share here the exact exception details (Exception.Message) you are struggling into?

**Comment by TunayT** [comment]
**here it is, thank you.**
[Exception.txt](https://github.com/RepoDb/RepoDb/files/2608155/Exception.txt)

**And as you can see, Password is missing here.**

![resim](https://user-images.githubusercontent.com/45233308/48904616-fe4c6480-ee6f-11e8-90bb-44b93f009775.png)

**Comment by mikependon** [comment]
Thank you, this info is enough now for us to be able to investigate the case. We will get back to you late today (GMT).

**Comment by TunayT** [comment]
Thank you very much. This is not urgent for me now, it will be important when I finish my project.
My version is 1.6.4.0

**Comment by mikependon** [comment]
@TunayT - this scenario is by designed in purpose as per Microsoft. In short, this is not an issue.

See the explanation here: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/protecting-connection-information

Just to let you know, I spent a little time for this issue. I was a bit busy earlier, but your issue can be fixed by simply persist the security information. See below.

![image](https://user-images.githubusercontent.com/591015/48917675-02ee3880-eec3-11e8-9ee0-1a6d3eb281da.png)

I hope that solves your problem.

**Comment by TunayT** [comment]
Thank you very much, yes this solution is enough for me.
