### ISSUE TITLE
Enhancement: Add the dynamic ExecuteQueryMultiple method in the DbRepository

### ISSUE THREAD

**Issue by gkn06** [mikependon/RepoDB#630]
@mikependon 
Other `IDbConnection` extended method named `ExecuteQueryMultiple` is not yet added in the `DbRepository`.
Is it possible to add that too?

Signature:
```csharp
public static QueryMultipleExtractor ExecuteQueryMultiple(this IDbConnection connection, string commandText, object param = null, CommandType? commandType = null, int? commandTimeout = null, IDbTransaction transaction = null);
```
Related to #517 

Thanks a lot!

**Comment by mikependon** [comment]
@gkn06 - your request is now available in the master branch, but TBH, I had not tested it yet. Would you like to have a beta release and test it?

**Comment by mikependon** [comment]
This is now deployed at [RepoDB v1.12.5-beta1](https://www.nuget.org/packages/RepoDb/1.12.5-beta1). Can you upgrade and test it there? Thanks

**Comment by gkn06** [comment]
@mikependon Sure. I will test it & let you know asap.

**Comment by gkn06** [comment]
@mikependon I tested it. Its working perfect 👍.

**Comment by mikependon** [comment]
Thanks, closing this ticket now.

**Comment by mikependon** [comment]
By the way, ensure to always dispose the instance of QueryMultipleExtractor after used so the underlying DbDataReader and DbConnection will also be disposed.

**Comment by gkn06** [comment]
Thanks much @mikependon
