### ISSUE TITLE
Bit / Boolean handling

### ISSUE THREAD

**Issue by Olli64** [mikependon/RepoDB#632]
Hey!

I updated from 1.11.6 to 1.12.4 and .SqlServer from 1.0.13 to 1.1.1 and for some reason even if I set my property to True and check it in debugger that its true before insert, it sets it as false to database.
Is this known bug or?

I can try and put up a simple project to reproduce this if needed.

**Comment by mikependon** [comment]
Hey @Olli64 , yeah, can you give me a small application that simulate this?

**Comment by Olli64** [comment]
Thanks for quick reply @mikependon !
Actually did the test project and it works just fine,
Then deleted repodb and sqlserver extension from my project and reinstalled and now everything works fine. weird.

Will reopen if it appears again! sorry for this!

**Comment by mikependon** [comment]
Thanks. Please be reminded that you need to upgrade both the SQL Server and the Bulk Operations extensions as some signatures are needed to be on track. From where you jump the versions between 1.11.x and 1.12.x, you are in between of the major updates we made in relation to the Core Compiler. There, we rewrote the overall compiler, so any discrepancy could be a result of that update.

In our case, we made all the unchanged Unit and Integration Tests passed in the new compiler so any use-cases that are already covered are not affected, but we also did some updates on top of that could fix more scenarios.

In anyway, please do not hesitate to revert anytime with the steps on how to replicate the said issue.
