### ISSUE TITLE
Request: Do not crash if on empty enumerable on bulk operation 

### ISSUE THREAD

**Issue by Swoorup** [mikependon/RepoDB#635]
RepoDb should probably do a noop if the user passes an empty enumerable to operation such as `InsertAll`.

Currently it throws an exception: `The entities must not be empty.`

**Comment by mikependon** [comment]
The fix is now available at version >= [RepoDb.SqlServer.BulkOperations v1.1.2-beta1](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.1.2-beta1). Kindly upgrade your copy.

**Comment by Swoorup** [comment]
@mikependon hmm, thank you. Is this fixed for all integration ie npgsql including?

**Comment by mikependon** [comment]
Batch yes, but bulk is only on SqlServer.

**Comment by mikependon** [comment]
The fix for this is to throw an exception if you are passing an empty list and/or enumerables. Such scenario has been applied to the BulkOperation as well. Though, if you think a no operations are the correct fix, then I can adjust it.

**Comment by mikependon** [comment]
TBH, removing a throwing of exception would change the behavior, but of course, it could always be changed as you wish.

**Comment by Swoorup** [comment]
I personally think it should be a noop, since now the user must check if they are passing an empty enumerable or not. But it's not the end of the world.

For bulk/batch operation it seems valid to pass empty array.

**Comment by mikependon** [comment]
Okay, then I have to revert the Integration Tests and modify the code that checks the nullability.

**Comment by mikependon** [comment]
The removal of the validation is now available at [RepoDb v1.12.5-beta3](https://www.nuget.org/packages/RepoDb/1.12.5-beta3) and [RepoDb.SqlServer.BulkOperations v1.1.2-beta2](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.1.2-beta2).

**Comment by mikependon** [comment]
Closing this one now.
