### ISSUE TITLE
BulkDeleteAsync takes empty DateTime into account

### ISSUE THREAD

**Issue by stefandevo** [mikependon/RepoDB#641]
My understanding was that the BulkDeleteAsync looked at the PrimaryKey, so I created a list with only the PK values.
However, for SQL Server, it fails when the entity contains DateTime fields which are not initialised and therefore have the min date value for .net; but this minimum is invalid for SQLServer.
Not sure how this is used; when I just initialised all DateTime fields for the entity with DateTime.Today, my records get deleted.

**Comment by mikependon** [comment]
> My understanding was that the BulkDeleteAsync looked at the PrimaryKey, so I created a list with only the PK values.

Yes, this is correct. Is that not working in your side?

Also, I need more context here. Is your PK a Date Time field?

Lastly, if you intend to use an uninitialized DateTime, can you set it to type Nullable DateTime and set it to NULL before sending?

**Comment by stefandevo** [comment]
No this is not working.

Consider following example:

```
public class RepLandingPageStatistic
{
		public string LandingPageStatisticId { get; set; }

		public string LandingPageId { get; set; }

		public DateTime PageView { get; set; }
}
```

The `LandingPageStatisticId` is my PK. The `PageView` is a mandatory field in the DB, that's why it is not a nullable field.

So bulkInsert, bulkMerge etc all works Wonderfull, but if I want to bulkDelete, and I only set the `LandingPageStatisticId` to a value,  the BulkDelete fails because of the `PageView` is set to a default which is "too low" for SQLServer.

So I now do 

```
		public DateTime PageView { get; set; } = DateTime.Today; //needed for bulk delete

```

and then the BulkDelete works.

**Comment by mikependon** [comment]
Okay, I thought you passed a list of PK (as in an Array of String) for LandingPageStatisticId. In anyway, thanks for creating this issue. We will look at this and it will be a part of the next version if it is a valid issue. Hope you are not block.

**Comment by mikependon** [comment]
@stefandevo - the overloaded method that accepts the list of the entities is not suite for your use-case. You are correct that you need to provide values to the PageView column in order for it to be Bulk-Inserted into the pseudo-temp table, and that is on purpose for the usage of Bulk-Delete. Therefore, we instead highly recommend to you that you should use the overloaded method that accepts the array of the primary keys (`IEnumerable<object> primaryKeys`). This would somehow invalidate this request, as we speak. I hope you are okay with that.

**Comment by stefandevo** [comment]
Ok, just for my knowledge, if I only provide the PKs, no temp table will be created for the Delete? Because, the fact that the DateTime is a non-nullable field, the issue will stay the same. Or when providing PKs only, there is no temp table?

**Comment by mikependon** [comment]
There is still a temporary table because of the following:

- SQL Server only allows 2100 parameters, whereas you may pass more than that
- It is leveraging thr BulkInsert and does the DELETE JOIN SQL to ensure that Bulk Processing is done atomic

It will not trigger a problem is because, the temporary table to be created will only contains the PK column and not all the fields. So the operation is very minimal, yet performant and efficient.

**Comment by stefandevo** [comment]
Ok thanks for this insight! Then indeed the list of PK's is better than adding the complete entity with the default values!
It might be a good idea to add to the documentation as well.
I will close it now.

**Comment by mikependon** [comment]
Sure, we will do add this - I will create and relate it here soon.
