### ISSUE TITLE
Bug: System.Data.SqlClient.SqlException: 'Column name 'ID' does not exist in the target table or view.'

### ISSUE THREAD

**Issue by nandaccio** [mikependon/RepoDB#651]
Something weird is happening with:

```
         using (var connection = new SqlConnection(ConnectionString))
            {
                var mappings = new List<BulkInsertMapItem>
                {
                    new BulkInsertMapItem("TransactionID", "TransactionID"),
                    new BulkInsertMapItem("DateCreated", "DateCreated"),
                };

                mergedRows = await connection.BulkMergeAsync<Transaction>(data, mappings: mappings).ConfigureAwait(false);
            }
```

The call to BulkMergeAsync fails because, according to RepoDB: "Column name 'ID' does not exist in the target table or view".
But the ID field (primary key, identity) is available in the Transaction class:

```
[Map("[dbo].[Transactions]")]
    public class Transaction
    {
        [Primary, Identity, Map("ID")]
        public long ID { get; set; }

        public long TransactionID { get; set; }

        public DateTime DateCreated { get; set; }
```

and in the database itself:
![repodb1](https://user-images.githubusercontent.com/13116598/100474521-18655100-30e1-11eb-8eb9-b3efe920e6f2.png)

This exception was originally thrown at this call stack:
    System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
    System.Data.SqlClient.SqlInternalConnection.OnError(System.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
    System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, bool, bool)
    System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, out bool)
    System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(System.IAsyncResult, string, bool)
    System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(System.IAsyncResult)
    System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(System.IAsyncResult)
    System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(System.IAsyncResult, System.Func<System.IAsyncResult, TResult>, System.Action<System.IAsyncResult>, System.Threading.Tasks.Task<TResult>, bool) in FutureFactory.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    ...
    [Call Stack Truncated]

**Comment by mikependon** [comment]
Hey, would you be able to share your table schema as well? TY

**Comment by mikependon** [comment]
Thank you for reporting this issue. We have replicated this internally using the [RepoDb v1.12.5-beta3](https://www.nuget.org/packages/RepoDb/1.12.5-beta3) and [RepoDb.SqlServer.BulkOperations v1.1.2-beta2](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.1.2-beta2).

**Schema:**

```
USE [DemoRepoDB]
GO

/****** Object:  Table [dbo].[Transactions]    Script Date: 12/1/2020 10:15:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Transactions](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[TransactionId] [bigint] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
 CONSTRAINT [PK_Transactions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
```

**Models:**

```csharp
using RepoDb.Attributes;
using System;

namespace BulkInsertWithMappingTest.Models
{
    [Map("[dbo].[Transactions]")]
    public class Transaction
    {
        [Primary, Identity, Map("ID")]
        public long ID { get; set; }

        public long TransactionID { get; set; }

        public DateTime DateCreated { get; set; }
    }
}
```

**Main:**

```csharp
using BulkInsertWithMappingTest.Models;
using Microsoft.Data.SqlClient;
using RepoDb;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace BulkInsertWithMappingTest
{
    class Program
    {
        static void Main(string[] args)
        {
            SqlServerBootstrap.Initialize();
            Test().Wait();
            Console.ReadLine();
        }

        static async Task Test()
        {
            using (var connection = new SqlConnection("Server=.;Database=DemoRepoDB;Integrated Security=SSPI;"))
            {
                var mappings = new List<BulkInsertMapItem>
                {
                    new BulkInsertMapItem("TransactionId", "TransactionId"),
                    new BulkInsertMapItem("DateCreated", "DateCreated"),
                };
                var data = new List<Transaction>
                {
                    new Transaction { TransactionID=1, DateCreated=DateTime.UtcNow },
                    new Transaction { TransactionID=2, DateCreated=DateTime.UtcNow },
                    new Transaction { TransactionID=3, DateCreated=DateTime.UtcNow },
                };
                var mergedRows = await connection.BulkMergeAsync<Transaction>(data, mappings: mappings).ConfigureAwait(false);
                Console.WriteLine($"Merged rows = {mergedRows}");
            }
        }
    }
}
```

**Comment by mikependon** [comment]
Though, as per our investigation, the correct way of fixing it is to always add all the properties of the model/entity when defining the mappings. This issue exists because the model/entity has many properties and the defined target columns in the table are only 2, it is because of the mappings you defined.

We will handle this internally so it would be a seamless experience from the users, but while waiting for the fix, please use that as an alternative fix for your case.

**Comment by mikependon** [comment]
The fix is now available at [RepoDb.SqlServer.BulkOperations v1.1.2-beta3](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.1.2-beta3).

**Comment by mikependon** [comment]
Closing this ticket now.

**Comment by nandaccio** [comment]
I confirm that v1.1.2-beta3 solves this issue.

Thanks!
