### ISSUE TITLE
@myParameter=default is creating the error "expects the parameter '@myParameter', which was not supplied"

### ISSUE THREAD

**Issue by Jmaharman** [mikependon/RepoDB#653]
I'm using this library from F#, and generally things are behaving as expected.

However I've just come up against this issue, and I'm not sure if it's a library problem or a SQL problem.

Essentially I have an anonymous record which has parameter that is nullable<int64>, the SQL executes and returns the error message as described above.

I profiled the execution to see what was being sent in, and that's where I notice this "default" syntax, which I've not seen before.

There could be a number of things going on here, my first instinct was that the library wasn't handling nullable<int64> appropriately, which seemed unlikely to me. However on seeing the SQL, it feels like it's doing something, but I don't know what that is?

```sql
exec sp_executesql N'INSERT INTO [dbo].[MyTable] ( [CreatedById], [CreatedOn], [HeadOfficeId], [OfficeBranchId] ) VALUES ( @CreatedById, @CreatedOn, @HeadOfficeId, @OfficeBranchId ) ; SELECT CONVERT(INT, SCOPE_IDENTITY()) AS [Result] ;',N'@HeadOfficeId bigint,@OfficeBranchId bigint,@CreatedById bigint,@CreatedOn datetime',
@HeadOfficeId=18,
@OfficeBranchId=default,
@CreatedById=291,
@CreatedOn='2020-11-28 18:31:18.003'
```

This is an amended version of the query to make it more palatable, but it has the core information I think is relevant.

Any thoughts?

I've been using the library for 3 weeks now, I'm impressed but what I've seen so far and the docs have been great.

Thanks in advance

**Comment by mikependon** [comment]
It seems to be an issue in the lib, though I have not yet investigated it. The line below seems to be not valid.

```
@OfficeBranchId=default,
```

Would you be able to share a code snippet of how did you call the operation?

**Comment by Jmaharman** [comment]
This is a cut down version of it for you:

```
let newRecord =
  {|
      CreatedById = 1
      CreatedOn = DateTime.Now
      HeadOfficeId = Nullable<int64>(18L)
      OfficeBranchId = Nullable<int64>()
  |}

printf "%A" newRecord

RepoDb.SqlServerBootstrap.Initialize();

async {
    use connection = (new SqlConnection("[Connection]"))
    let! _ = connection.OpenAsync() |> Async.AwaitTask
    let! id =
        connection.InsertAsync("[dbo].[MyTable]", newRecord) |> Async.AwaitTask

    printf "New ID: %d" id

    return id
} |> Async.RunSynchronously
```

**Comment by mikependon** [comment]
Cool, thinking to make a release on the next 2 weeks. Can you wait for that? Hope, you had an alternative for now.

**Comment by Jmaharman** [comment]
Yea I can wait, thank you for your time and great library!

**Comment by mikependon** [comment]
@Jmaharman, I had tested this one using my own simulation and it seems to be working with SQL Server using the [RepoDb v1.1.1](https://www.nuget.org/packages/RepoDb.SqlServer/1.1.1). Can you validate this on your own and/or maybe replicate it?

**Note:** It works with or without the `Id` column from the `TestTable` table.

**Table Schema:**

```
CREATE TABLE [dbo].[TestTable]
(
	/* [Id] [bigint] IDENTITY(1,1) NOT NULL, */
	[CreatedById] [int] NOT NULL,
	[CreatedOn] [datetime2](7) NOT NULL,
	[HeadOfficeId] [bigint] NULL,
	[OfficeBranchId] [bigint] NULL,
	/* CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED ([Id] ASC) ON [PRIMARY] */
) ON [PRIMARY];
GO
```

**Main:**

```fsharp
// Learn more about F# at http://fsharp.org

open System
open RepoDb
open Microsoft.Data.SqlClient

[<EntryPoint>]
let main argv =

    let newRecord =
      {|
          CreatedById = 1
          CreatedOn = DateTime.Now
          HeadOfficeId = Nullable<int64>(18L)
          OfficeBranchId = Nullable<int64>()
      |}

    printf "%A" newRecord
    
    RepoDb.SqlServerBootstrap.Initialize();
    
    // Sync
    use connection = (new SqlConnection("Server=.;Database=TestDB;Integrated Security=SSPI;"))
    let id = connection.Insert<int>("[dbo].[TestTable]", newRecord)
    Console.WriteLine(id.ToString())

    // Async
    async {
        use connection = (new SqlConnection("Server=.;Database=TestDB;Integrated Security=SSPI;"))
        let! _ = connection.OpenAsync() |> Async.AwaitTask
        let! id2 = connection.InsertAsync<int>("[dbo].[TestTable]", newRecord) |> Async.AwaitTask
    
        Console.WriteLine(id2.ToString())
    
        return id
    } |> Async.RunSynchronously

    0
```

**Profiler Result (with `Id` column):**

```
exec sp_executesql N'INSERT INTO [dbo].[TestTable] ( [CreatedById], [CreatedOn], [HeadOfficeId], [OfficeBranchId] ) VALUES ( @CreatedById, @CreatedOn, @HeadOfficeId, @OfficeBranchId ) ; SELECT CONVERT(BIGINT, SCOPE_IDENTITY()) AS [Result] ;',N'@CreatedById int,@CreatedOn datetime,@HeadOfficeId bigint,@OfficeBranchId bigint',@CreatedById=1,@CreatedOn='2020-12-01 21:39:13.817',@HeadOfficeId=18,@OfficeBranchId=NULL
```

**Profiler Result (without the `Id` column):**

```
exec sp_executesql N'INSERT INTO [dbo].[TestTable] ( [CreatedById], [CreatedOn], [HeadOfficeId], [OfficeBranchId] ) VALUES ( @CreatedById, @CreatedOn, @HeadOfficeId, @OfficeBranchId ) ; SELECT NULL AS [Result] ;',N'@CreatedById int,@CreatedOn datetime,@HeadOfficeId bigint,@OfficeBranchId bigint',@CreatedById=1,@CreatedOn='2020-12-01 21:36:45.830',@HeadOfficeId=18,@OfficeBranchId=NULL
```

**Actual Result:**

```fsharp
{ CreatedById = 1
  CreatedOn = 12/1/2020 9:44:49 PM
  HeadOfficeId = 18L
  OfficeBranchId = null }1
2

C:\Users\MichaelP\Source\Repos\DefaultParameterFSharpTest\DefaultParameterFSharpTest\bin\Debug\netcoreapp3.1\DefaultParameterFSharpTest.exe (process 20908) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by Jmaharman** [comment]
I've run your example, and just like you I found that worked fine.

I then went back into the codebase where the issue arose and undone my work around, but I can't get the problem to arise again in that either(!).

I'll close the issue and if it comes up again I'll make sure I repro it in a separate repo and provide that as an example.

Sorry for your wasting your time :(

**Comment by mikependon** [comment]
No worries and thanks for verifying.
