### ISSUE TITLE
[Bug]RepoDb.IntegrationTests.Types.Strings.TestSqlConnectionStringsCrud test fail

### ISSUE THREAD

**Issue by fredliex** [mikependon/RepoDB#659]
- version: lastest master (0be471d75fc7e456fe4a38b4f0cdf9dab8bd7fa2)
- project: RepoDb.IntegrationTests
- class: RepoDb.IntegrationTests.Types.Strings
- method: TestSqlConnectionStringsCrud

```
  訊息: 
    Assert.AreEqual failed. Expected:<ÀÆÇÈËÌÏÐÑÒØÙÜÝÞß>. Actual:<AACEEIIDNOOUUYTs>. 
  堆疊追蹤: 
    SqlConnectionStringsTest.TestSqlConnectionStringsCrud() 行 54
```

`RepoDb.IntegrationTests.Helper.GetUnicodeString`
```
  public static string GetUnicodeString()
  {
    return "ÀÆÇÈËÌÏÐÑÒØÙÜÝÞß";
  }
```

is string `ÀÆÇÈËÌÏÐÑÒØÙÜÝÞß` is encoding error??

the below test case have some error
`TestSqlConnectionStringsCrud`
`TestSqlConnectionStringsCrudAsync`
`TestSqlConnectionStringsCrudViaAsyncViaTableName`
`TestSqlConnectionStringsCrudViaTableName`
`TestSqlConnectionStringsMappedCrud`
`TestSqlConnectionStringsMappedCrudAsync`

**Comment by fredliex** [comment]
Perhaps the collate should be specified when `RepoDb.IntegrationTests.Setup.CreateDatabase` creates the database.
like this
```sql
create database RepoDb collate Danish_Norwegian_CS_AI
```

Is the collate `Danish_Norwegian_CS_AI`?

**Comment by mikependon** [comment]
Well it seems to me that collate should not matter here. AppVeyor for example runs in US and has no problem. I guess this is more about localization thing, though I have not yet revisited this as of writing this.

**Comment by fredliex** [comment]
After verification.
Found that the SQL Server's default collate `SQL_Latin1_General_CP1_CI_AS` can pass the test.
My local database collate `Chinese_Taiwan_Stroke_CI_AS` failed the test.

It doesn't matter, I will change the collate of my local database to match the test case.

The above information let you know.

thank you.

**Comment by mikependon** [comment]
Thanks for verifying this on your end.
