### ISSUE TITLE
Bug: BulkInsert with mappings

### ISSUE THREAD

**Issue by SpaceOgre** [mikependon/RepoDB#668]
I might be misunderstanding something about BulkInsert with mappings so I would like to know how to do this scenario with RepoDb and BulkInsert :)

Following class to insert:
```c#
public abstract record Customer
{
	public int Id { get; init; }
	abstract public CustomerType CustomerTypeId { get; }
	public string CustomerNumber { get; init; }
}

public record PrivateCustomer : Customer
{
	public override CustomerType CustomerTypeId => CustomerType.Private;
	public string SocialSecurityNumber { get; init; }
	public string FirstName { get; init; }
	public string LastName { get; init; }
	public string ChangedBy { get; init; }
}
```

To table
```sql
CREATE TABLE dbo.PrivateCustomer
(
  [CustomerId] int NOT NULL FOREIGN KEY REFERENCES dbo.Customer(Id) PRIMARY KEY CLUSTERED
  , [SocialSecurityNumber] varchar(100) NULL
  , [FirstName] nvarchar(100) NULL
  , [LastName] nvarchar(100) NULL
  , [ChangedBy] nvarchar(100) NULL
  , [SysStartTime] datetime2 GENERATED ALWAYS AS ROW START HIDDEN NOT NULL
  , [SysEndTime] datetime2 GENERATED ALWAYS AS ROW END HIDDEN NOT NULL
  , PERIOD FOR SYSTEM_TIME (SysStartTime,SysEndTime))
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.PrivateCustomerHistory));
```

So the Id property in the base Customer class should be inserted into the CustomerId column in db.

I'm trying this:
```c#
var mappings = new List<BulkInsertMapItem>();
mappings.Add(new BulkInsertMapItem("Id", "CustomerId"));

var insertedRows2 = await connection.BulkInsertAsync(privateCustomers, mappings: mappings, transaction: transaction);
```

But I'm getting: `There are no field(s) found for this operation.`

I have look in the source code and this part looks a bit weird to me:
```c#
IEnumerable<Field> entityFields = type.IsDictionaryStringObject() ? GetDictionaryStringObjectFields(((entities != null) ? entities.FirstOrDefault() : null) as IDictionary<string, object>) : FieldCache.Get(type);
IEnumerable<Field> enumerable = dbFields?.Select((DbField dbField) => dbField.AsField());
_ = DateTime.UtcNow;
if (entityFields?.Any() ?? false)
{
	enumerable = enumerable.Where((Field e) => entityFields.Any((Field f) => string.Equals(f.Name, e.Name, StringComparison.OrdinalIgnoreCase)));
}

if (mappings == null)
{
	mappings = enumerable?.Select((Field f) => new BulkInsertMapItem((entityFields?.FirstOrDefault((Field ef) => string.Equals(ef.Name, f.Name, StringComparison.OrdinalIgnoreCase)))!.Name ?? f.Name, f.Name));
}
else
{
	enumerable = enumerable.Where((Field e) => mappings.Any((BulkInsertMapItem m) => string.Equals(m.SourceColumn, e.Name, StringComparison.OrdinalIgnoreCase)));
}

if (enumerable == null || !enumerable.Any())
{
	throw new MissingFieldException("There are no field(s) found for this operation.");
}
```

So the mapping is used after entityFields are checked against dbFields. In my case this means that the Id property is not in `enumerable` when the mapping is done.

I'm just missing what mappings are for? And if so is there some way for me to solve it without manually mapping using a DataTable for instance?

Edit:
---
I have tried with both 1.1.1 and 1.1.2-beta3

**Comment by mikependon** [comment]
Hey, I had simulated this one and it is working on our end, with the scripts/impl below.

**Schema:**

```csharp
CREATE TABLE [dbo].[People](
	[PeopleId] [bigint] NOT NULL,
	[Name] [nvarchar](32) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
	[CustomerType] [int] NULL,
	[CustomerStatus] [nvarchar](32) NULL,
	[CreatedDateUtc] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[PeopleId] ASC
)
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[People] ADD  CONSTRAINT [DF_People_CreatedDateUtc]  DEFAULT (getutcdate()) FOR [CreatedDateUtc]
GO
```

**Models:**

```csharp
public class Person
{
    public long Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public DateTime CreatedDateUtc { get; set; } = DateTime.UtcNow;
}
```

**Mapping**:

```csharp
RepoDb.SqlServerBootstrap.Initialize();
RepoDb.FluentMapper
    .Entity<Person>()
    .Table("[dbo].[People]")
    .Column(e => e.Id, "PeopleId", true);
```

When I remove the mapping, the exception is thrown like below.

```
Microsoft.Data.SqlClient.SqlException: 'Cannot insert the value NULL into column 'PeopleId', table 'DemoRepoDB.dbo.People'; column does not allow nulls. INSERT fails.
The statement has been terminated.'
```

We will try simulate your inheritance scenario... 1/2

**Comment by mikependon** [comment]
There you go, I replicated it with the models below.

```csharp
public class BasePerson
{
    public long Id { get; set; }
    public DateTime CreatedDateUtc { get; set; } = DateTime.UtcNow;
}

public class Person : BasePerson
{
    public string Name { get; set; }
    public string Address { get; set; }
}
```

The issue is, it seems the mapping is not being applied on the inherited properties.

**Comment by mikependon** [comment]
Related to #666

**Comment by mikependon** [comment]
@SpaceOgre  - FYI in relation to the `mappings` argument, if this is defined, the bulk operation will utilize only the fields defined on the mapping, ignoring the other fields from both table and entity model.

**Comment by SpaceOgre** [comment]
Ah I have not tried the FluentMapper for it. Good to know it should work when the inherited properties problem is fixed. 

But I still feel like the BulkInsert mapping is not working as intended?

This is how it looks for me (without any fluent mappings) in the code sample from my post above. 
**Entityfields**
* Id
* CustomerTypeId
* CustomerNumber
* SocialSecurityNumber
* FirstName
* LastName
* ChangedBy

**enumerable (dbfields)**
* CustomerId
* SocialSecurityNumber
* FirstName
* LastName
* ChangedBy

After this part:
```c#
if (entityFields?.Any() ?? false)
{
	enumerable = enumerable.Where((Field e) => entityFields.Any((Field f) => string.Equals(f.Name, e.Name, StringComparison.OrdinalIgnoreCase)));
}
```
**enumerable**
* SocialSecurityNumber
* FirstName
* LastName
* ChangedBy

So neither Id or CustomerId is available when the mappings is applied later. Should not the mapping be part of the selection with and OR or something like it? Because now mappings can only be used on properties/columns that allready exists in both entity and DB. So like I could map LastName to FirstName. But I can't really see a use case for it.

I might be totally of base here and miss something obvious or just not understand the feature.

Atm it seems like these are the options available atm:
* Use FluentMapper
* Add extra properties to the class that match the destination DB table
  * `public int Customer ID => Id;` I have done this atm and it works.
* Create a new class or DataTable to mapp properties

It would be nice to be able to use mappings for it to.

**Comment by mikependon** [comment]
@SpaceOgre - you are correct, there is an issue to the `mappings` of the bulk operations in this case. What you had pin-pointed in terms of code level is the root cause of the problem (see [here](https://github.com/mikependon/RepoDB/blob/2236ee665fcea01684aa410d573bea0d0fbaa654/RepoDb.Extensions/RepoDb.SqlServer.BulkOperations/RepoDb.SqlServer.BulkOperations/Base/BulkInsert.cs#L99)), as you mentioned, it is pre-eliminating the fields from the source table. And, we will fix this :)

On the other hand, I hope you understand that mapping is "all or nothing", means, if you use the `mapping` argument, the mentioned fields on that argument will only be used, eliminating the others.

Btw, when do you need the fix? I can issue a beta ASAP.

**Comment by SpaceOgre** [comment]
Totally get that mappings is all or nothing 👍 
I'm thinking of making a method to get Mappings based on entity (something like you do in the insert) and then just replace what I need. Hmm this might be a nice method for RepoDb to provide since you already have the codebase for it ;) 

On Monday would be nice, but no rush I can work around it.

**Comment by mikependon** [comment]
if you do not know yet, the classes `FieldCache`, `PropertyCache`, `ClassMappedNameCache`, `PropertyMappedNameCahe` and method `PropertyInfo.GetMappedName()` are powerful if you know how to combine it with `FluentMapper` class. You can always iterate the result snd call the proper mapping methods from the mapper.

**Comment by SpaceOgre** [comment]
Awesome will play around with them :)

**Comment by mikependon** [comment]
This is now available on version [RepoDb.SqlServer.BulkOperations v1.1.2-beta4](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.1.2-beta4).
