### ISSUE TITLE
System.Data.SqlClient.SqlException: 'Column name 'ID' does not exist in the target table or view.'

### ISSUE THREAD

**Issue by nandaccio** [mikependon/RepoDB#669]
Hi,

with reference to issue #651, it seems that the problem still persists. I updated RepoDB to v1.12.5-beta4 and this is my test table:

```sql
CREATE TABLE [dbo].[Transactions](
	[TransactionID] [bigint] NULL,
	[DateCreated] [datetime] NULL,
	[Action] [nvarchar](max) NULL,
	// Other fields have been removed for the sake of simplicity
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_RawTransactionsTest] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```
and the corresponding class:

```csharp
 [Map("[dbo].[Transactions]")]
 public class Transaction
    {
        [Primary, Identity, Map("ID")]
        public long ID { get; set; }
        public long TransactionID { get; set; }
        public DateTime DateCreated { get; set; }
        public string Action{ get; set; }
// Other fields have been removed for the sake of simplicity
}
```

BulkInsertAsync works as expected:
```
await connection.BulkInsertAsync<Transaction>(data).ConfigureAwait(false)
```

but 

```sql
 var mappings = new List<BulkInsertMapItem>
                       {
                           new BulkInsertMapItem("TransactionID", "TransactionID"),
                           new BulkInsertMapItem("DateCreated", "DateCreated"),
                           new BulkInsertMapItem("Action", "Action"),
                       };

                mergedRows = await connection.BulkMergeAsync<Transaction>(data, mappings: mappings).ConfigureAwait(false);
```

and

```
                mergedRows = await connection.BulkMergeAsync<Transaction>(data).ConfigureAwait(false);
```

both fail with:

System.Data.SqlClient.SqlException: 'Column name 'ID' does not exist in the target table or view.'

**Important:** 
data is a DataTable that actually does **not** contain an ID field as ID is a "[ID] [bigint] IDENTITY(1,1)" key available only on the database.

Is it possible with RepoDB to insert, possibly with bulk operations, ONLY those records with a specific combination of values (example: TransactionID, Action, DateCreated) that is not found on the database?

**Comment by mikependon** [comment]
@nandaccio - hey, I could not replicate this issue using the [RepoDb v1.12.5-beta4](https://www.nuget.org/packages/RepoDb/1.12.5-beta4) and [RepoDb.SqlServer.BulkOperations v1.1.2-beta3](https://www.nuget.org/packages/RepoDb.SqlServer.BulkOperations/1.1.2-beta3) versions.

Here I attached the project solution ([BulkInsertWithMappingTest.zip](https://github.com/mikependon/RepoDB/files/5683242/BulkInsertWithMappingTest.zip)), the one I used on the investigation. Would you be able to check it there and revert to me if you encountered the problem on your side?

FYI: I am planning to make a new beta very soon, so I am happy to include this if this is really an issue.

**Comment by mikependon** [comment]
Ping?

**Comment by mikependon** [comment]
Closing this ticket for now. Please revert if this is still not working on your side by simply commenting and re-opening this issue.
