### ISSUE TITLE
Bug: RepoDb.SqlServer Enum picking up 2 types when upgraded from 1.1.1 -> 1.1.2

### ISSUE THREAD

**Issue by simmohall** [mikependon/RepoDB#736]
### Bug Description

When running a query using an enum in the WHERE clause, if I use 2 enum values, the first uses INT and the second uses the STRING value

**Exception Message:**

No exception from RepoDb, but the underlying SQL fails as it can't convert the column to 2 different data types

Generated T-SQL example
exec sp_executesql N'SELECT [source_system], [incoming_payload], [Id], [correlation_id], [event_type], [external_ticket_id], [internal_ticket_id], [created_timestamp], [arrival_timestamp], [completion_timestamp], [retries_remaining], [last_retry_timestamp], [Status], [error_description] FROM [incoming_event_queue] WHERE (([Status] = @Status) OR ([Status] = @Status_1)) ;',N'@Status int,@Status_1 nvarchar(4000)',@Status=0,@Status_1=N'awaiting_retry'

```csharp
exception in T-SQL when manually executing the run SQL. 
Msg 245, Level 16, State 1, Line 10
Conversion failed when converting the nvarchar value 'awaiting_retry' to data type int.
```

**Schema and Model:**
create table incoming_event_queue(id int, status int)

```csharp
_localDbContext.Connection.Query<IncomingQueueEvent>(e => e.Status == EventStatus.queued || e.Status == EventStatus.awaiting_retry)
```

And also the model that corresponds the schema.

```csharp
[Map("incoming_event_queue")]
public class IncomingQueueEvent
{
public int Id { get; set; }
[TypeMap(DbType.Int32)]
public EventStatus Status { get; set; }
}

public enum EventStatus
    {
        queued = 0,
..
awaiting_retry = 4
}
}
```

**Library Version:**

Example: RepoDb v1.12.5 and RepoDb.SqlServer v1.1.2

(note: this worked ok in v1.1.1

**Comment by mikependon** [comment]
Yeah, there were PRs in relation to this and we had introduced this [logic](https://repodb.net/feature/enumeration#default-conversion). So this might had affected this.

But is very recommended to not use the `TypeMap` if you are using the model-based operation like `Query`. Would you be able to remove the `TypeMap` decoration from your model? RepoDB understand it and it will do the job for you.

Of course, unless otherwise you are not using the model-based operations like `Execute<Methods>`.

**Comment by mikependon** [comment]
Hopefully, that would work, but if that recommendation doesn't fix that, then we will investigate this further and revert back to you. Plus, we will also guard this with the Integration Tests.

**Comment by simmohall** [comment]
Thanks for the quick reply! I will move to that recommendation and report back shortly

**Comment by simmohall** [comment]
Thanks, i've removed the TypeMap. It then goes back to the default string conversion which i was trying to avoid. But from reading that link - i've now set Converter.EnumDefaultDatabaseType = DbType.Int32 and now it is correctly using ints for the enum.
Thanks :)

**Comment by mikependon** [comment]
It is still a bug as having a forced attribute `TypeMap` should be the one prevail at all cost. Can we leave this one open so I can track?

**Comment by simmohall** [comment]
sure - reopening for tracking
