### ISSUE TITLE
Bug: DataEntityDataReader documentation has not been updated after the optimizations

### ISSUE THREAD

**Issue by NicoKno** [mikependon/RepoDB#737]
### Bug Description

I just wanted to report, that this snippet from the documentation isn't working. Because Execute Reader returns a IDataReader and ToEnumerable takes a DbDataReader which seems to not be interchangable.

```csharp
using (var connection = new SqlConnection(connectionString))
{
    using (var reader = connection.ExecuteReader("SELECT * FROM [dbo].[Person];"))
    {
        var people = DataReader.ToEnumerable(reader);
        // Do the stuffs for 'people' here
    }
}
```

**Library Version:**

RepoDb v1.12.X and RepoDb.SqlServer v1.1.2

**Comment by SimonCropp** [comment]
@NicoKno do you want to have a go at submitting a PR to fix it?

**Comment by NicoKno** [comment]
Sure, I will. I first had to figure out how to do it correctly.

**Comment by mikependon** [comment]
@NicoKno - I just revisited this one. The `ExecuteReader` returns an instance of `DbDataReader`. If you are using the SQL Server via SDS/MDS, it returns the `SqlDataReader` which also implements the `DbDataReader`. Which DB Provider are you using?

**Comment by NicoKno** [comment]
I am using System.Data.SqlClient. 

ExecuteReader returns IDataReader:
[ExecuteReader](https://github.com/mikependon/RepoDB/blob/99ddd32bdf3ef59903eb57cefc4063a1c0595fba/RepoDb.Core/RepoDb/Extensions/DbConnectionExtension.cs#L1044)

ToEnumerable takes a DbDataReader:
[ToEnumerable](https://github.com/mikependon/RepoDB/blob/4361bebbcb947340ad1bc614b652e69fdc628be0/RepoDb/RepoDb/Reflection/DataReader.cs)

I got it working for my case. But I have to cast to DbDataReader.

I will submit a PR.

**Comment by mikependon** [comment]
Cool. Then I compared the different thing then. I used to compare the `ToEnumerable` from the `DbCommand.ExecuteReader()`, not the `RepoDB.ExecuteReader()`. Thanks for this clarity. 😄
