### ISSUE TITLE
Question: Generate Pocos

### ISSUE THREAD

**Issue by myalo** [mikependon/RepoDB#751]
Hello
Do you have or can recommend a generator that can generate Classes based on tables / Views / Stored procedures in the MS Sql Database?
Thanks

**Comment by mikependon** [comment]
Yes, I am in collaboration with @ErikEJ using his [EF Power Tools](https://github.com/ErikEJ/EFCorePowerTools/issues). It is strongly recommended.

Our [request](https://github.com/ErikEJ/EFCorePowerTools/issues/558) has just been completed.

**Comment by ErikEJ** [comment]
I will try to create a wiki post  called something like: "Generating pure POCO classes"

**Comment by ErikEJ** [comment]
Only remaining issue is to avoid Navigation properties.

**Comment by ErikEJ** [comment]
Latest daily build of EF Core Power Tools includes the following features, that should help with "pure POCO" code generation:
* Experimental support for nullable reference types, use `"UseNullableReferences": true` in efpt.config.json to enable 
* Experimental support for entity classes without constructor (so you can manage all constructors in a partial class), use `"UseNoConstructor": true` in efpt.config.json to enable 
* Experimental support for entity classes without navigations & constructor (for pure POCO classes for use with RepoDB, Dapper etc.), use `"UseNoNavigations": true` in efpt.config.json to enable 

https://github.com/ErikEJ/EFCorePowerTools/wiki/Release-notes

**Comment by myalo** [comment]
> I will try to create a wiki post called something like: "Generating pure POCO classes"
I downloaded v 2.5.454, used the reverse engineer, and received EF type of POCOS. 
How can I create **PURE** POCOs as I am not using EF at all and just need the members?
Thanks

**Comment by ErikEJ** [comment]
@myalo You need the latest daily build, then follow the release notes in the link above.

**Comment by ErikEJ** [comment]
Published a wiki post: https://github.com/ErikEJ/EFCorePowerTools/wiki/Generate-POCO-classes-for-use-with-micro-ORMs

**Comment by mikependon** [comment]
Thanks a lot @ErikEJ for this support. I will share your tool to PHINUG as well.

**Comment by mikependon** [comment]
Closing this one now.

**Comment by myalo** [comment]
Thanks
