### ISSUE TITLE
Question: How do I do BulkInsert to table with Identity column and suplie the values myself?

### ISSUE THREAD

**Issue by SpaceOgre** [mikependon/RepoDB#754]
Hi,

I'm trying to BulkInsert to a table that have an Identity column, but I don't want the database to add the value during the BulkInsert but I want to add it from code.

First I just tried to use
```c#
await connection.ExecuteNonQueryAsync("SET IDENTITY_INSERT dbo.Customer ON", transaction: transaction);
```
before I do the BulkInsert but that did not work. So I tried to pass in `SqlBulkCopyOptions.KeepIdentity` but then the database just creates the values. 

If I use them together then it just complains that with IDENTITY_INSERT ON a value needs to be suplied.

Is this possible to do with RepoDb and I'm just missing something or is it not possible?

**Comment by mikependon** [comment]
Use the options Identity Insert.

**Comment by mikependon** [comment]
Had you tried by simply setting the `options` to `KeepIdentity` without enabling the Identity Insert to ON?

**Comment by SpaceOgre** [comment]
Hi, yeah I tried to only use that as well 😢
Not sure if it could have anything to do with that the class is abstract? 

I will try more tomorrow now that I know that it should work

**Comment by mikependon** [comment]
I am pretty sure we have done this, but it seems there is no Integration Tests written for this scenario. Let me check and get back to you soon.

**Comment by mikependon** [comment]
@SpaceOgre - after my verification today, this is working by simply setting the `options` to `KeepIdentity` without tweaking anything on the underlying table.

Schema:

```
USE [TestDB]
GO

/****** Object:  Table [dbo].[Person]    Script Date: 1/26/2021 10:01:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Person](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](128) NOT NULL,
	[DateOfBirth] [datetime] NULL,
	[Age] [int] NULL,
	[ExtendedInfo] [nvarchar](max) NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDateUtc] [datetime2](5) NOT NULL,
 CONSTRAINT [PK__Person__3214EC0721084EB2] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Person] ADD  CONSTRAINT [DF_Person_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO

ALTER TABLE [dbo].[Person] ADD  CONSTRAINT [DF_Person_CreatedDateUtc]  DEFAULT (getutcdate()) FOR [CreatedDateUtc]
GO
```

Model:

```csharp
public class Person
{
    public long Id { get; set; }
    public string Name { get; set; }
    public DateTime DateOfBirth { get; set; }
    public int Age { get; set; }
    public string ExtendedInfo { get; set; }
    public bool IsActive { get; set; }
    public DateTime CreatedDateUtc { get; set; }
}
```

Yield:

```csharp
static IEnumerable<Person> GetPeople(int count = 1000)
{
    for (var i = 0; i < count; i++)
    {
        yield return new Person
        {
            Id = i,
            Name = $"Name{i}",
            Age = i,
            DateOfBirth = DateTime.UtcNow,
            ExtendedInfo = $"ExtendedInfo{i}",
            IsActive = true,
            CreatedDateUtc = DateTime.UtcNow
        };
    }
}
```

Call:

```csharp
using (var connection = new SqlConnection("Server=.;Database=TestDB;Integrated Security=SSPI;"))
{
    connection.Truncate("Person");
    var people = GetPeople(1000).AsList();
    people.ForEach(p => p.Id = p.Id + 1000); // Add 1000 on each Id
    var result = connection.BulkInsert(people, options: SqlBulkCopyOptions.KeepIdentity);
    people = connection.QueryAll<Person>().AsList(); // This one returns the property values
}
```

SQL Server actual query result is below.

![image](https://user-images.githubusercontent.com/591015/105905232-7ac7c880-6022-11eb-9796-06112ec34726.png)

**Comment by SpaceOgre** [comment]
Tested it more today and it works as it should.

It was my fault... I did `&` instead of `|` for my SqlBulkCopyOptions so instead of getting CheckConstraints and KeepIdentity I got Default.

**Comment by SpaceOgre** [comment]
Sorry for wasting your time :(

**Comment by mikependon** [comment]
No worries mate! 😄 @SpaceOgre  - I am glad that it works in your side now and happy as well that I had to buy my own time last night for this. Do not hesitate to file an issue moving forward.
