### ISSUE TITLE
Question: ulid type converter 

### ISSUE THREAD

**Issue by aminparsa18** [mikependon/RepoDB#760]
i am using https://github.com/Cysharp/Ulid as identity type for entities.
it has built in converter for ef core and dapper
trying to run a query with repo db i get following message:

"Expression of type 'System.Ulid' cannot be used for parameter of type 'System.Object' of method 'System.String ToString(System.Object)' (Parameter 'arg0')"

how can i implement appropriate conversion?

**Comment by mikependon** [comment]
It seems to me a customized thing. With this, you need to handle that via [Property Handler](https://repodb.net/feature/propertyhandlers).

**Comment by mikependon** [comment]
Sample implementation.

```csharp
public class UlidPropertyHandler : IPropertyHandler<string, Ulid>
{
	public Ulid Get(string input, ClassProperty property)
	{
		/* return string to ulid */
	}

	public string Set(Ulid input, ClassProperty property)
	{
		/* return ulid to string */
	}
}
```

In your class.

```csharp
public class MyClass
{
	...
	
	[PropertyHandler(typeof(UlidPropertyHandler))]
	public Ulid UlidProperty { get; set; } 
	
	...
}
```

Or via [FluentMapper](https://repodb.net/mapper/fluentmapper).

```csharp
FluentMapper.Entity<MyClass>().PropertyHandler<UlidPropertyHandler>(e => e.UlidProperty);
```

**Comment by aminparsa18** [comment]
Great.Thanks

**Comment by mikependon** [comment]
Is it working in your side now?
