### ISSUE TITLE
Bug: Generic EntityRepository.GetConnection() throws system exception

### ISSUE THREAD

**Issue by richardy706** [mikependon/RepoDB#764]
I am using the EntityRepository<TEntity, TDbConnection> which I copied from [gist.github.com/mikependon](https://gist.github.com/mikependon/b409cc549052e2b5d77574e2b0948c3b) as base class for a repository.
This line
````csharp
connection = Activator.CreateInstance<TDbConnection>();
````
Is throwing a system exception.  
I am using RepoDB.SqlServer v1.1.3 in a .Net 5 solution.  The class is constructed using dependency injection.  I have verified that the class is constructed with the proper settings (connection string).

**Exception Message:**

      Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnection..ctor()
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)

**Comment by richardy706** [comment]
Turns out I was calling into the repository from a Blazor WASM page - which of course one cannot do.  Works fine once I got the methods executing on the server.  Sorry for the inconvenience.

**Comment by mikependon** [comment]
No worries and thanks for sleuthing around. 😄
