### ISSUE TITLE
Question: Does it make sense to use scoped connection instead of transient?

### ISSUE THREAD

**Issue by not-authorized** [mikependon/RepoDB#774]
The question relates to the Repository feature. [It is recommended to register the repository with AddTransient.](https://repodb.net/feature/repositories#update-2)

Why not allow all repository instances to use a single connection within a single request?

**Comment by mikependon** [comment]
Yeah, it all depends on your scenario. We are actually using Singleton but we used the connection-based repostiory mostly (over BaseRepsitory and DbRepository).
