### ISSUE TITLE
Enhancement: Add support of NpgsqlDbType in FluentMapper

### ISSUE THREAD

**Issue by not-authorized** [mikependon/RepoDB#775]
It would be helpful to have the ability to define PostgreSQL database type mappings using FluentMapper so that it will be possible to keep the domain model clean and without Npgsql and RepoDB dependencies.

```csharp
FluentMapper
    .Entity<Account>()
    .DbType(e => e.Profile, NpgsqlDbType.Jsonb);
```

**Comment by not-authorized** [comment]
Do you mind resolve this issue?

**Comment by mikependon** [comment]
Thanks for the follow-up. I had tried to look at this historically and the solution is a bit different than what you expect.

As per our analysis, the `NpgsqlDbType` is not a part of the library, in which we can't pass it like you propose above. It will only be visible if you have the `Npgsql` driver referenced.

We will queue this one up on our feature development.

Below might be the proposal and this is solving a bit general concern of placing the attributes in the command object.

```csharp
FluentMapper
    .Entity<Entity>()
    .CommandAttribute(e => e.Property, "PropertyName", "Value");
```

In your case, it could be like below.

```csharp
FluentMapper
    .Entity<Account>()
    .CommandAttribute(e => e.Profile, "NpgsqlDbType", NpgsqlDbType.Jsonb);
```

The value will be attributed to the actual `DbCommand` object, it is true whether you are using the SDS/MDS, MySQL, PostgreSQL and/or SQLite driver.

I know that it is okay to the end-user for as long the solution is working.

But, I am more concern on the development experience and I would like to get the feedback as early as now, is the approach feasible with you?

**Comment by not-authorized** [comment]
Yes, the approach you suggested will work for me.

**Comment by not-authorized** [comment]
Any updates on this issue?

**Comment by mikependon** [comment]
@not-authorized thanks for the follow-up, this has been queued as we prioritized the other. Also, I have been on a busy schedules recently after the series of demoes. Would you be able to wait for our next major release? It will cover this request.

FYI: We are doing a lot of minor releases, this will not be included there.

To be frank, the timeline of the major release is at least a month. Hope that is okay with you?

**Comment by not-authorized** [comment]
Thank you for the update. Looking forward to the next release.

**Comment by mikependon** [comment]
It is been a tough last 6 months. We have a recent updates that covers the placement of the property attributes.

This concerns will be fixed by this: https://repodb.net/attribute/npgsql/npgsqldbtype

**Comment by mikependon** [comment]
It is not available on the latest version of [RepoDb.PostgreSql](https://www.nuget.org/packages/RepoDb.PostgreSql/1.1.4).
