### ISSUE TITLE
Bug: SQLite Identity field cannot identified

### ISSUE THREAD

**Issue by davidrot** [mikependon/RepoDB#790]
### Bug Description

Repodb cant determine the IdentityField in the sqlite table when create statement is using " around column names. If using the sql statement below, the code is returning ""Id"" (see picture). This is resulting in issue in BaseStatementBuilder.CreateInsert(), the insertableFields is not excluding the id field. 

If you tell me how a potential fix would look like I can prepare a PR.

![repodb](https://user-images.githubusercontent.com/5358167/111299759-9b8ac280-8650-11eb-8186-95c4c9a4270b.png)

**Exception Message:**

None

**Schema and Model:**

Please share to us the schema of the table (not actual) that could help us replicate the issue if necessary.

Not working:

```csharp
CREATE TABLE "User"(
"Id" INTEGER PRIMARY KEY AUTOINCREMENT,
"Username" text,
"Password" text,
"Email" text,
"CreationDate" DATETIME,
"ModificationDate" DATETIME,
"Disabled" integer NOT NULL DEFAULT '0',
"DisabledDate" DATETIME
);
```

Working
```
CREATE TABLE User(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Username text,
Password text,
Email text,
CreationDate DATETIME,
ModificationDate DATETIME,
Disabled integer NOT NULL DEFAULT '0',
DisabledDate DATETIME
);
```

And also the model that corresponds the schema.

```csharp

public class User
{
    [Identity]
    public long Id { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Email { get; set; }
    public DateTime CreationDate { get; set; }
    public DateTime ModificationDate { get; set; }
    public bool Disabled { get; set; }
    public DateTime? DisabledDate { get; set; }
}

var connectionString = $"Data Source=\"MemoryDb\"; Mode=Memory; Cache=Shared";
var sut = new UserRepository(connectionString);

var item = sut.Insert(new User { Username = "UnitTest" + new Random().Next(0,100000) });


```

**Library Version:**

Example: RepoDb v1.12.7 and RepoDb.SqLite v1.1.3

**Comment by mikependon** [comment]
What a catch. Yeah, it sounds to me that the fix can be found [here](https://github.com/mikependon/RepoDB/blob/f7c473ceb7ef37dc1decc55c377c1969e0135cca/RepoDb.SqLite/RepoDb.SqLite/DbHelpers/SqLiteDbHelper.cs#L155). Most likely, within the [ParseTableFieldsFromSql](https://github.com/mikependon/RepoDB/blob/f7c473ceb7ef37dc1decc55c377c1969e0135cca/RepoDb.SqLite/RepoDb.SqLite/DbHelpers/SqLiteDbHelper.cs#L192) method, or just simply follow the code.

**Comment by mikependon** [comment]
What a findings! Thanks for this. 😄 

Yeah, it sounds to me that the fix can be found [here](https://github.com/mikependon/RepoDB/blob/f7c473ceb7ef37dc1decc55c377c1969e0135cca/RepoDb.SqLite/RepoDb.SqLite/DbHelpers/SqLiteDbHelper.cs#L155). Most likely, within the [ParseTableFieldsFromSql](https://github.com/mikependon/RepoDB/blob/f7c473ceb7ef37dc1decc55c377c1969e0135cca/RepoDb.SqLite/RepoDb.SqLite/DbHelpers/SqLiteDbHelper.cs#L192) method, or just simply follow the code.

**Comment by mikependon** [comment]
The fix has been introduced and it will be available on the next release. Please do let me know if you need a beta release for this.
