### ISSUE TITLE
Enumeration doc error

### ISSUE THREAD

**Issue by gloriousjob** [mikependon/RepoDB#800]
For https://repodb.net/feature/enumeration, the PropertyHandler section has an error. The first method is:
public Gender? Get(string input, ClassProperty property)

But I got an interface not implemented error when I tried to use this as a base. I think the intent here is Set instead of Get:
public Gender? Set(string input, ClassProperty property)

**Comment by mikependon** [comment]
Thank you for this report. Yeah, you are correct, we made a typo there.

We had updated the doc to inherit the interface like this `IPropertyHandler<string, Gender?>`, not like this `IPropertyHandler<Gender?, string>`.
