### ISSUE TITLE
Where is FluentMapper located?

### ISSUE THREAD

**Issue by codeweb** [mikependon/RepoDB#824]
I read all documentation but I can't find this topic (maybe it can be added).
I'm developing Asp.Net Core Web Api in C# using a class library containing all my classes and interfaces.
I need to map class properties to database columns because they have different names. I read about decorations but RepoDb is not linked in class library, so I chose to use FluentMapper.
FluentMapper code is located in `Startup.cs` after `SqlServerBootstrap.Initialize();` ? Or where?
If yes, I have many tables to set, so can i specify another class to call from Startup.cs to do all the work?
Thanks

**Comment by mikependon** [comment]
We strongly suggest that you create a customized initializer method/class within your main project (the one that references your "class library that contains all the models/interfaces"). On this initializer method/class, call the RepoDB bootstrapper method (`SqlServerBootstrap.Initialize()`) and also all the [Implicit Mapings](https://repodb.net/feature/implicitmapping) done via `FluentMapper` class. In this case, you just need to reference the core library (RepoDB) in your main project line.

If however you separated the infrastructure (i.e.: Repositories, ORM) on an another class library, ensure that you reference the RepoDB library there and expose a static class that is callable by your main project line.

In the Startup.cs, simply call your initializer method/class, the one that initializes RepoDB and all its mapping.

Hope this helps!

**Comment by codeweb** [comment]
My repos and interfaces implementations are in main project. In the class library there model and interface classes.
So you suggest adding in Startup.cs a DbInitializer class as:
```
public class DatabaseInitializer
{
        public DatabaseInitializer()
        {
        }

        public void Init()
        {
            SqlServerBootstrap.Initialize();
            FluentMapper....
        }
}
```

**Startup.cs**
```
public void ConfigureServices(IServiceCollection services)
{
   ...
   DatabaseInitializer di = new DatabaseInitializer();
   di.Init();
}
```

I suggest to add the example of calling FluentMapper in `Implicit Mappings` documentation link.

**Comment by mikependon** [comment]
I am hoping that [this](https://repodb.net/feature/implicitmapping#fluent-mapping) is the one you are looking?

**Comment by codeweb** [comment]
Yes but the method call is missing.

**Comment by mikependon** [comment]
@codeweb - apology for returning to you a bit late. We will consider placing the requested snippets on the documentation as you requested. In anyway, do you still have problems here on the other side?

**Comment by codeweb** [comment]
I solved. Thanks
