### ISSUE TITLE
Question: Can BulkInsert be used to insert into a temp table?

### ISSUE THREAD

**Issue by casperOne** [mikependon/RepoDB#831]
Currently, I am creating a temp table on an open connection, like so:

```
// Create the temp table.
string sql = $@"

--- Cleanup
drop table if exists #ids

create table #ids (
    externalDomain nvarchar(100), 
    externalDomainId nvarchar(100),
    primary key clustered (externalDomain, externalDomainId)
)
";

// Execute.
await conn.ExecuteAsync(sql).ConfigureAwait(false);
```

Once that is done, I want to bulk insert into that table.  I create an `IEnumerable<T>` first, like so:

```
// Map the ids.
var ids = native.Select(n => new { 
    externalDomain = n.Item.ExternalDomain,
    externalDomainId = n.Item.ExternalDomainId 
});
```

And then I call `BulkInsertAsync` like so on the open connection:

```
// Write the external domain and IDs to the table.
await conn
.BulkInsertAsync(
    "#ids", 
    ids,
    batchSize: p.BatchSize,
    cancellationToken: cancellationToken
)
.ConfigureAwait(false);
```

However, I get a `RepoDb.Exceptions.MissingFieldsException` with the following message:

```
There are no database fields found for table '#ids'. Make sure that the target table '#ids' is present in the database and/or at least a single field is available.
```

I suspect this is because of the fact that it's a temp table.

That said, is there a way for a call to `BulkInsertAsync` to insert into a temp table that was created on the same open connection?

**Comment by mikependon** [comment]
Yeah, we have done it many times already, the bulk insert is working with the temporary tables (# or ##).

Anyway, did you use the same connection object when creating the temporary tables and when bulk inserting into it?

Note: Temporary tables are contextual, so closing the connection directly would also delete the temporary tables under that connection object on the underlying data source (at least for SQL Server).

**Comment by casperOne** [comment]
> Yeah, we have done it many times already, the bulk insert is working with the temporary tables (# or ##).
> 
> Anyway, did you use the same connection object when creating the temporary tables and when bulk inserting into it?
> 
> Note: Temporary tables are contextual, so closing the connection directly would also delete the temporary tables under that connection object on the underlying data source (at least for SQL Server).

@mikependon Yes, we are using the same opened connection (without closing it).  I'll try and reproduce consistently, and close this for now.

**Comment by daaleonardo** [comment]
Hello,

I know this question has been closed but I'm having a similar issue.
I figured out that I can use BulkInsert right after a:
'''
"SELECT * FROM ##TempTable"
'''

But if I don't I'm getting the same error:
'''
There are no database fields found for table '#ids'. Make sure that the target table '#ids' is present in the database and/or at least a single field is available.
'''

Thanks in advance.

**Comment by daaleonardo** [comment]
Hello,

I know this question has been closed but I'm having a similar issue.
I figured out that I can use BulkInsert right after a:
`SELECT * FROM ##TempTable`

But if I don't I'm getting the same error:
`There are no database fields found for table '#ids'. Make sure that the target table '#ids' is present in the database and/or at least a single field is available.`

Thanks in advance.

**Comment by daaleonardo** [comment]
Hello,

I know this question has been closed but I'm having a similar issue.
I figured out that I can use BulkInsert right after a:
SELECT * FROM ##TempTable

But if I don't I'm getting the same error:
There are no database fields found for table '##TempTable'. Make sure that the target table '##TempTable' is present in the database and/or at least a single field is available.

Thanks in advance.

**Comment by daaleonardo** [comment]
Hello,

I know this question has been closed but I'm having a similar issue.
I figured out that I can use BulkInsert right after a:
```
SELECT * FROM ##TempTable
```
But if I don't I'm getting the same error:
```
There are no database fields found for table '##TempTable'. Make sure that the target table '##TempTable' is present in the database and/or at least a single field is available.
```

Thanks in advance.
