### ISSUE TITLE
please tell me how to use mariadb

### ISSUE THREAD

**Issue by seongguk92** [mikependon/RepoDB#847]
I want to use the mariadb query 'select *from table'
_[dbo]. is required for it to work._

There is no database setting mapping found for 'MySql.Data.MySqlClient.MySqlConnection'

let me use mariadb...

**Comment by mikependon** [comment]
This usually happens if you call an operation but has missed calling the initializer in the first place. Can you please check if the calls to the MySqlBootstrap.Initialize() method has ever been took place.

**Comment by seongguk92** [comment]
Sorry..
even if applied (**MySqlBootstrap.Initialize() method**)
It's still popping up.

**10.4.12-MariaDB**
~~~
  var result = connection.ExecuteQuery("SELECT * FROM `table`;");
~~~

{"There is no database setting mapping found for 'MySqlConnector.MySqlConnection'. Make sure to install the correct extension library and call the bootstrapper method. You can also visit the library's installation page (http://repodb.net/tutorial/installation)."}

**Comment by mikependon** [comment]
It sounds an outlier to me, and what is difficult is the fact that we only have the MySQL environment and not the MariaDB environment for testing. I had personally tested it there and everything works fine. The only thing that I can replicate this is when I missed calling the initialization method. Can you share me your code instead?

**Note:** Good if you can share a RepoDb stack trace or some information if you had debugged it already.

**Comment by seongguk92** [comment]
Thanks for your help.
https://repodb.net/tutorial/get-started-mysql
