### ISSUE TITLE
Enhancement: Remove System.Data.SqlClient reference from RepoDB.SqlServer

### ISSUE THREAD

**Issue by Dean-NC** [mikependon/RepoDB#857]
### Describe the enhancement

Since RepoDB.SqlServer already has a reference to Microsoft.Data.SqlClient, it would be nice to not also have a reference to System.Data.SqlClient. Currently, the output (bin) folder of an application using RepoDB.SqlServer will have assemblies and dependencies for both Microsoft.Data.SqlClient AND System.Data.SqlClient.

**Comment by mikependon** [comment]
This is true and I agree to this as well. Though it is easy to remove the references towards the SDS, but it is not as simple as that. We are afraid that we might affect some of the users if we are to remove this without the proper acceptance from the community.

Maybe, I will bring this question to the community itself and will ensure this will be implemented on the next releases.

**Comment by mikependon** [comment]
The System.Data.SqlClient will be removed on the next version of RepoDb.SqlServer (or > [v1.1.4](https://www.nuget.org/packages/RepoDb.SqlServer/1.1.4)).
