### ISSUE TITLE
Is BulkMerge supposed to *update* records based on the qualifier(s)?

### ISSUE THREAD

**Issue by nandaccio** [mikependon/RepoDB#860]
I populate a table with:

var merged = await database.BulkMergeAsync(entities, qualifiers: p => new { p.ReferenceNumber, p.Account }, hints: SqlServerTableHints.TabLock, bulkCopyTimeout: 0).ConfigureAwait(false);

And adding new records based on the qualifiers (ReferenceNumber and Account) works as expected.

But when I have entities with the same combination of ReferenceNumber and Account in "entities" (=input data), with UPDATED values for other columns, I would expect to see those changes in the database as well. That's not the case, changes are ignored.

Is my understanding wrong?

**Comment by mikependon** [comment]
With your explanation, it should update the values of the other fields for as long the 2 qualifiers you mentioned (ReferenceNumber and Account) is equating to it.

> But when I have entities with the same combination of ReferenceNumber and Account in "entities" (=input data), with UPDATED values for other columns, I would expect to see those changes in the database as well. That's not the case, changes are ignored.

Did you use same entity models but with a different set of array values? Or did you use the dynamic approach?

**Comment by nandaccio** [comment]
Thank you Mike.

I just did some more tests: it actually works if the schema does not change.
My initial tests were done in the following scenario:

* Data has been inserted using BulkMerge(Async)
* Then a new column was added to the table (and to the model, of course)
* Data was then re-processed with the purpose of populating the new column as well (initially null)

After completing the re-processing I would have expected to have the same data as before PLUS the new column populated with the additional information coming from the source.

Actually the new column was not updated, it remained filled with NULLs instead of getting updated with the additional data.

**Comment by mikependon** [comment]
OK. You know, RepoDB is fast because of its caching mechanism, but it also comes with some penalties that requires some deep understanding on the caching mechanism.

Try to see if the clearing the cache via DbFieldCache.Flush() helps? It might be that you maybe need to call both the PropertyCache.Flush(), FieldCache.Flush() as well (after modifying the Schema).

**Comment by nandaccio** [comment]
Thank you! You answered my initial question and BulkMergeAsync works as expected, for sure when schema does not change.
I will perform further tests (also with PropertyCache.Flush(), FieldCache.Flush()), but since question was answered I will mark this one as "Closed".

Thanks :)
