### ISSUE TITLE
Request: Separate the SqLite Nuget Library into 2

### ISSUE THREAD

**Issue by mikependon** [mikependon/RepoDB#880]
### Describe the request

The RepoDb.SqLite library is refencing both the [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite/) and [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core/) Nuget Packages.

In order for RepoDB to be more clean and simple, we will be separating the RepoDB package into 2 (dedicated to each).

Conversation Link: https://twitter.com/mike_pendon/status/1436431940152926209

### Proposed Nuget Package Names:

- RepoDb.SqLite.Microsoft - for [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite/)
- RepoDb.SqLite.System - for [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core/), though, we are thinking to still retain this to [RepoDb.SqLite](https://www.nuget.org/packages/RepoDb.SqLite).

**Comment by bgrainger** [comment]
The proposed names seem fine, although I would suggest correcting the casing to Sqlite (.NET naming guidelines) or SQLite (official DB name). 

"SqLite" follows neither convention.

**Comment by cajuncoding** [comment]
It's great to separate them, and names seem fine... but I think it would be very confusing to retain the legacy `RepoDb.SqLite` package name; it seems like it will be very confusing to have 3 different packages, of which 2 are the same and/or even more confusing, one is not the same but without explicit details in the name.

If three versions are needed then all three packages should have similarly explicit/helpful names.

**Comment by mikependon** [comment]
@cajuncoding - If we decided to retain the RepoDb.SqLite, then we will only create the RepoDb.SqLite.Microsoft and not creating the RepoDb.SqLite.System.

But, it sounds to me that separating them completely are much more cleaner, which I also think that it will be the direction to proceed. Ofcourse, considering the name casing suggested by @bgrainger .

**Comment by cajuncoding** [comment]
👍 Yeah, the explicit named packages are cleaner so devs aren't left confused.
