### ISSUE TITLE
Question: Is there any hope that BulkInsertAsync will support IAsyncEnumerable?

### ISSUE THREAD

**Issue by Xhanti** [mikependon/RepoDb#904]
Hi,

Is there any hope that BulkInsertAsync will support IAsyncEnumerable?

Regards

**Comment by mikependon** [comment]
Sounds a good suggestion. IAsyncEnumerable is on our plan and we will consider this. If you can make a story (issue), then it most likely you started the conversation out of it, though I can also create soon. 🚀

**Comment by Xhanti** [comment]
Hi, I just wanted to know if you guys were considering. I use your library when import some massive files and recently moved it to using IAsyncEnumerable i had to convert it to IEnumerable to keep using repo db and i didn't like. But it sounds like you guys have a plan. I can add a story issue

**Comment by mikependon** [comment]
@SergerGood - you initially introduced the IAsyncEnumerable, can you help me on this?

**Comment by SergerGood** [comment]
@mikependon Yes, sure. I'll see what i can do
