### ISSUE TITLE
Expression tree or QueryField for QueryAll/QueryAllAsync

### ISSUE THREAD

**Issue by Dean-NC** [mikependon/RepoDb#933]
Why is there not Expression tree or QueryField for the QueryAll/QueryAllAsync methods ??

Is ExecuteQuery() the only way to select multiple records with a where condition?

Thanks.

**Comment by Dean-NC** [comment]
OK, I see that Query() is where you can not only get single but also multiple rows by using an Expression tree or QueryField(s).  It looks like the purpose of QueryAll is when you truly want all rows.
Correct?

**Comment by mikependon** [comment]
Yes, that is the purpose of QueryAll. Use the Query method instead. It accepts either of the Anonymous, QueryGroup/QueryField or Expression Tree as the parameters.

Reason: Method overloaded collisions and forcing the Query method without a parameter is seems not practical by the name itself.

**Comment by Dean-NC** [comment]
Great, thanks.
