### ISSUE TITLE
Question: How does one trace *Async methods?

### ISSUE THREAD

**Issue by richardy706** [mikependon/RepoDb#945]
The ITrace interface does not include any of the async methods.  Is this because tracing does not work async or can these async methods be added to the interface?

**Comment by mikependon** [comment]
Hi, the `Async()` methods are part of the tracing. The same methods are being invoked with the awaited results from the asynchronous methods. Here is a code for [QueryAll](https://github.com/mikependon/RepoDB/blob/76affb998905fa8dde5c5679cb0a7eea38d60063/RepoDb.Core/RepoDb/Operations/DbConnection/QueryAll.cs#L739), and you can see [here](https://github.com/mikependon/RepoDB/blob/76affb998905fa8dde5c5679cb0a7eea38d60063/RepoDb.Core/RepoDb/Operations/DbConnection/QueryAll.cs#L719) that we have awaited such result.

**Comment by mikependon** [comment]
I will consider as a missing piece on the implementation if one would really like to work with asynchronous all the way. You might be interested on sharing your thoughts on this #941.

**Comment by mikependon** [comment]
The fixes to this will be available on the next version > RepoDB v1.12.10.
