### ISSUE TITLE
Is there a way to implement optimistic concurrency using RepoDB?

### ISSUE THREAD

**Issue by mediasystems-ch** [mikependon/RepoDb#947]
I am currently in the process of switching from Entity Framework to RepoDB in my project and have encountered a problem: the lack of support for optimistic concurrency. Optimistic concurrency is a basic requirement in a system that stores data in a relational database and I absolutely need this feature. Is there a solution to implement optimistic concurrency the same or similar way as in Entity Framework when using RepoDB? I am aware that RepoDB is a lightweight ORM. But there has to be a way  to implement that, in my opinion. Even if this feature is not implemented in RepoDB, it should be possible to implement it sowehow by myself. The question is: how?

In Entity Framework I'm using this property declaration to enable optimistic concurrency:

[Timestamp]
public byte[] RowVersion { get; set; }

If possible, I don't want to introduce two different classes for reading from and writing entities to the database in my project. That would be a pretty big overhead.

For example, would be there a way in RepoDB to influence the creation of the SqlCommand for inserting and updating? Any other ideas?

Any help would be greatly appreciated!

**Comment by mikependon** [comment]
Only for the SQL parameters. Can this [blog](https://repodb.net/blogs/repodb/2021/09/29/repodb-property-attributes/) help?

**Comment by mikependon** [comment]
The [FluentMapping](https://repodb.net/feature/implicitmapping) and the [PropertyHandler](https://repodb.net/feature/propertyhandlers) seems can handle your case. But, I will read about the optimistic query and further understand it before suggesting any relevant solutions to you.

You can read more about the features of RepoDB from [here](https://repodb.net/feature).

**Comment by mediasystems-ch** [comment]
Thank you for the suggestions. I have roughly skimmed the contents and I am not sure if this will help me. Here again the exact requirements for the support of optimistic concurrency:

- When inserting, the property RowVersion (byte[]) must be ignored completely.
- When querying, the field content from the database must be supplied in this property.
- When updating the entity, another condition must be added to the WHERE clause: RowVersion = @RowVersion.
- If the number of affected records is 0 when updating, a specific exception must be thrown or this case must be detected otherwise.

Can these requirements be met with the use of PropertyValueAttribute, PropertyHandler or FluentMapping? Is there a way to ignore a property when inserting?  Is there a way to add another condition when updating? If yes, how?

**Comment by mediasystems-ch** [comment]
I have just seen that there is a way to add a condition to the WHERE clause when updating an entity:

`var rowsAffected = connection.UpdateAll<Person>(persons, qualifiers: (p => new { p.Id, p.RowVersion }));`

This works so far. However, I have not found an overload of the Update() extension method where I can specify a qualifiers expression. I would imagine it like this:

`var rowsAffected = connection.Update<Person>(person, qualifiers: (p => new { p.Id, p.RowVersion }));`

Is that not possible?

Now the only remaining problem is that the RowVersion must be ignored when inserting. Is there a possibility?

**Comment by mikependon** [comment]
Everything can be achieved easily.

> When inserting, the property RowVersion (byte[]) must be ignored completely.

Yes, you can utilize the`fields` argument like [this](https://repodb.net/operation/insert#specific-columns). Only the list of fields passed on this argument will be a part of the operation. In your case, you can pass all the fields except for the `RowNumber` column.

Note: You can use the [FieldCache](https://repodb.net/cacher/fieldcache#usability) object to extract all the fields from the entities.

> When querying, the field content from the database must be supplied in this property.

This is given on the normal fetch operations (Query, QueryAll, ExecuteQuery).

> When updating the entity, another condition must be added to the WHERE clause: RowVersion = @RowVersion.

This can be simply achieved by passing an expression like this.

```csharp
connection.Update<Entity>(entity,` e => e.ColumnId == 1 && e.RowVersion == "Value");
```

It is like Entity Framework.

You can also pass an anonymous types or QueryField/QueryGroup object in the what/where argument. Through these objects, everything can be handled.

> If the number of affected records is 0 when updating, a specific exception must be thrown or this case must be detected otherwise.

The Update and UpdateAll operations return an integer value that corresponds to the count of the affected rows. You can handle throwing an exception afterwards.

**Comment by mediasystems-ch** [comment]
Thank you for the suggested solutions. It works now. As suggested, I use the FieldCache to get a list of the fields, remove the field which contains the RowVersion and then pass it as "fields" parameter in the Insert method:

`var fields = FieldCache.Get(Entity).ToList();`

`var id = (int)sqlConnection.Insert<Entity>(entity: entity, fields: fields);`

I forgot to mention that I have to do the exact same thing when updating. After updating, I check the return value (affected rows) and I throw an exception if necessary. That's all.

Thanks for your help! :-)

**Comment by mediasystems-ch** [comment]
ahh... one more thing: is there a way to return all or only certain data from the affected record in the same request to the database when inserting and updating? Since the RowVersion is only incremented on the server, an additional round-trip would be necessary to fetch this information.

**Comment by mikependon** [comment]
@mediasystems-ch - first, the entity that you had sent to the database when calling the Insert/Update operation is the latest and the updated one, of course, unless you have a computed columns like row-version that is happening on the server. In this sense, no, there is no other way except do a re-query of the target rows.

Note: There was a religious discussion pertaining to this (in the past), but decision is not to include this for the performance POV.
