### ISSUE TITLE
Bug: NullReferenceException when used from different thread

### ISSUE THREAD

**Issue by Dean-NC** [mikependon/RepoDb#948]
### Bug Description
I have a singleton class that holds a reference to another class (a variable called _service).  In the singleton class, I have a System.Threading.Timer that runs and uses the reference to _service to call a method on _service, that looks like:
```csharp
public async Task SomeMethod()
{
   using var connection = new Microsoft.Data.SqlClient.SqlConnection(dbConnString);
   await connection.OpenAsync();

   var requests = await connection.QueryAsync<DataRecord>(x => x.CompletedTime == null && x.ReceiveTime < DateTime.Now.AddHours(-1.5));
}
```

The timer callback method:
```csharp
private void TimerTick(object state)
{
    _service.SomeMethod().Wait();
}
```

From somewhere else in the same singleton class, I also call:
```csharp
await _service.SomeMethod()
```
**which works fine**.  But, when the timer callback calls _service.SomeMethod(), the line: connection.QueryAsync() throws a NullReferenceException.  When the exception happens, I verified that RepoDb.SqlServerBootstrap.IsInitialized is true. 

**Exception Message:**
NullReferenceException

TargetSite: Void <GetFields>b__0(RepoDb.QueryGroup)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

Stacktrace:
   at RepoDb.QueryGroup.<>c__DisplayClass59_0.<GetFields>b__0(QueryGroup queryGroup)
   at RepoDb.QueryGroup.<>c__DisplayClass59_0.<GetFields>b__0(QueryGroup queryGroup)
   at RepoDb.QueryGroup.<>c__DisplayClass59_0.<GetFields>b__0(QueryGroup queryGroup)
   at RepoDb.QueryGroup.GetFields(Boolean traverse)
   at RepoDb.QueryGroup.Fix()
   at RepoDb.QueryGroup.Parse[TEntity](Expression`1 expression)
   at RepoDb.DbConnectionExtension.ToQueryGroup[TEntity](Expression`1 where)
   at RepoDb.DbConnectionExtension.QueryAsync[TEntity](IDbConnection connection, Expression`1 where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)

**Model:**
```csharp
[Map("MyTable")]
public class DataRecord
{
    public int Id { get; set; }
    public string Client { get; set; }
    public DateTime ReceiveTime { get; set; }
    public DateTime? CompletedTime { get; set; }
}
```

**Library Version:**
RepoDb v1.12.9 RepoDb.SqlServer v1.1.4
Microsoft.Data.SqlClient v3.0.1

**Comment by mikependon** [comment]
We will look on this issue and if verified, will be a part of the next release. Do you have any timeline for this issue to get fixed? Thank you for reporting this issue.

**Comment by Dean-NC** [comment]
Thanks for looking into it. I've committed to providing this functionality to my customer, but I can hold off for a brief/little while.

**Comment by mikependon** [comment]
Hi @Dean-NC , we could not replicate this issue. Here we attached a small project for you to play and replicate this based on your scenario.

[Issue948.zip](https://github.com/mikependon/RepoDB/files/7748292/Issue948.zip)

Would you be able to update this and revert to us?

**Note:** We tested on the versions you mentioned and also to the latest version we had as of writing this (RepoDb v1.12.10-beta4, RepoDb.SqlServer v1.1.5-beta4, RepoDb.SqlServer.BulkOperations 1.1.6-beta2). We also tested on the latest main branch and everything works fine.

**Comment by Dean-NC** [comment]
@mikependon Thanks for the update. I've tested my code with the latest RepoDB and also updated Microsoft.Data.SqlClient to 4.0, and the error is no longer happening. It might have been a fix in Microsoft SqlClient.
