### ISSUE TITLE
Bug: RepoDB doesn't merge correct after altering a column

### ISSUE THREAD

**Issue by Bygdrift** [mikependon/RepoDb#966]
### I run this:

```
SqlServerBootstrap.Initialize();
using (var cnt = new SqlConnection(connectionString))
{
    cnt.ExecuteNonQuery("DROP TABLE IF EXISTS example");
    cnt.ExecuteNonQuery("CREATE TABLE example(Id int NOT NULL PRIMARY KEY, Data nvarchar(1));");
    cnt.Merge("example", new { Id = 1, Data = "a" });  //Adds a row
    cnt.ExecuteNonQuery("ALTER TABLE example ALTER COLUMN Data nvarchar(10);\n ALTER TABLE example ADD Name nvarchar(10);");
    cnt.Merge("example", new { Id = 1, Data = "Word", Name = "Peter" });  //Updates the same row
};
```

Result: `Id = 1 Data = "Wo", Name = NULL`

Expected: `Id = 1 Data = "Word", Name = "Peter"`

So RepoDB doesn't know that I have altered two columns. Is there a Flush() or Refresh(), so I can tell RepoDB that I have made changes? Or can I write my changes into RepoDB? Or is it a bug?

**Library Version:**

Example: RepoDb.SqlServer.BulkOperations v1.1.5

**Comment by mikependon** [comment]
Exactly, there is a report that is identical to this recently. Our suggestion is that, you flush the cachers of both the `DbField` and `Field` objects.

If you have modify the table that also changed the`Primary/Identity`, then we also suggest that you flush them all before calling the `Merge` operation again.

Below are the code.

```csharp
DbFieldCache.Flush(); // Remove all the cached DbField
FieldCache.Flush(); // Remove all the cached DbField
IdentityCache.Flush(); // Remove all the cached DbField
PrimaryCache.Flush(); // Remove all the cached DbField
```

We have plenty of cache objects [here](https://repodb.net/cacher), just be aware of which object to flush. This is not hurting your application and will only have a minor hit on your performance (in general). Therefore, on this advance scenario, it is recommended.

**Comment by Bygdrift** [comment]
Perfect - it worked - thank you so much!

**Comment by mikependon** [comment]
Glad to hear it works on your side.
