### ISSUE TITLE
Mapping Resultset fields to Custom Types

### ISSUE THREAD

**Issue by pmarflee** [mikependon/RepoDb#977]
By default, RepoDB maps SQL Server database fields to their CLR equivalent (int -> Int32, varchar -> String etc.)

Is there a way to tell RepoDB to map a field to a different, custom type?

For instance, let's say I have a stored procedure resultset which contains a field named 'BookingID' (int, not null).  I want RepoDB to create an instance of the following type instead of Int32 when mapping the resultset information to instances of my Model classes:

```
public record BookingId(int Value);

public class MyModel
{
    public BookingId BookingId {get; init; }
}

```

I'm presently doing this mapping by hand.  Can I configure RepoDB to do it automatically?

**Comment by mikependon** [comment]
It is not automatic, but RepoDB does support this scenarios through [PropertyHandler](https://repodb.net/feature/propertyhandlers). Sound like this is something what you are looking.

```csharp
// Target Type
public record Booking(int Value);

// Model
public class MyModel
{
	public Booking BookingId {get; set; }
}

// Handler
public class BookingPropertyHandler : IPropertyHandler<int, Booking>
{
	public Booking Get(int input, ClassProperty property) =>
		new Booking(input);

	public int Set(Booking input, ClassProperty property) =>
		input.Value;
}

// Mapping (Implicit)
FluentMapper
	.Entity<MyModel>()
	.PropertyHandler<BookingPropertyHandler>(e => e.BookingId);

// Mapping (Explicit)
public class MyModel
{
	[PropertyHandler(typeof(BookingPropertyHandler))]
	public Booking BookingId {get; set; }
}
```

**Comment by pmarflee** [comment]
Thanks, this worked.  I had to add a

`.Column(e => e.BookingId, "[bkgBookingID]")`

rule to my Fluent Mapping configuration, as there is a mismatch between the database field and the C# class property names.  Can this be combined into my .PropertyHandler rule?  I can see there are many overloads of .PropertyHandler, but I don't know if there is one I can use.

**Comment by mikependon** [comment]
Mismatch of naming? No, you should use the `Column` method when defining the mapping for column, it is designed for that.  The `PropertyHandler` is only for mapping the property handlers. What you did actually is really correct.

**Comment by pmarflee** [comment]
Thanks.  One more question: I have another record type 'Currency', defined like this:

`    public record Currency(int Id, string? Code = null, string? Sign = null);`

I can use a PropertyHandler to create an instance of Currency on my model if my database resultset only contains a single field like 'CurrencyID'.  However, I have some stored procedures that also return 'CurrencyCode' and 'CurrencySign'.  Can I still use the same PropertyHandler to pick up the values of these fields when creating the 'Currency' instance?  Or would I need to define a ClassHandler instead and do the work of creating the instance in there (this is what I am currently doing)?

    public class MonthEndOutstandingPaymentClassHandler : IClassHandler<MonthEndOutstandingPayment>
    {
        public MonthEndOutstandingPayment Get(MonthEndOutstandingPayment entity, DbDataReader reader)
        {
            entity.Currency = new Currency((int)reader["CurrencyID"], (string)reader["curCode"]);
            entity.Supplier = new Supplier((int)reader["supSupplierID"], (string)reader["supName"]);

            return entity;
        }

        public MonthEndOutstandingPayment Set(MonthEndOutstandingPayment entity)
        {
            return entity;
        }
    }

**Comment by mikependon** [comment]
The property handler is being executed in every property of the entity that has been hydrated from the database, therefore, it is not advisable to put it on this area. This is also true to a class handler.

Let us say, if you have 300 rows in the resultset, then the class handler will be invoked 300 times as well. It is not advisable to execute the SP 300 times. We are not recommending this approach.

---

However, if the Currency is not really changing much (or somewhat like a static table), then I suggest you implement the caching and it is safe to use it on the ClassHandler. See below.

```csharp
public class MonthEndOutstandingPaymentClassHandler : IClassHandler<MonthEndOutstandingPayment>
{
	private static ICache _memoryCache = new MemoryCache(); // This should be injected
	private string _connectionString = "<Your connection string>"; // Use your repository

	public MonthEndOutstandingPayment Get(MonthEndOutstandingPayment entity,
		DbDataReader reader)
	{
		// This should not be a problem since it is a cache
		var currency = GetCurrency(Convert.ToInt32(reader["CurrencyID"])); // GetCurrencyFromStoredProcedure
		entity.Currency = currency;

		return entity;
	}

	public MonthEndOutstandingPayment Set(MonthEndOutstandingPayment entity)
	{
		return entity;
	}

	private Currency GetCurrency(int currencyId)
	{
		using (var connection = new <Sql|Npgsql>Connection(_connectionString))
		{
			return connection.Query<Currency>(currencyId,
			cacheKey: $"Currency-{currencyId}", // CacheKey
			cache: _memoryCache); // Actual Cache object
		}
	}

	private Currency GetCurrencyFromStoredProcedure(int currencyId)
	{
		using (var connection = new <Sql|Npgsql>Connection(_connectionString))
		{
			return connection.ExecuteQuery<Currency>("EXEC sp_GetCurrency",
				new { CurrencyId = currencyId },
				cacheKey: $"Currency-{currencyId}", // CacheKey
				cache: _memoryCache); // Actual Cache object
		}
	}
}
```

**Comment by pmarflee** [comment]
I think you've misunderstood my question.  I'm not calling another stored procedure to fetch the currency information.  The currency information is being returned by the same stored procedure that gets the details of outstanding payments.  So there's only 1 stored procedure being invoked.

The output of the stored procedure looks something like this:

- supSupplierID (int)
- supName (varchar)
- CurrencyID (int)
- curCode (varchar)
- Cost (money)
- CostOriginal (money)
- Outstanding (money)

And my C# models look like this:

```
    public record Currency(int Id, string? Code = null, string? Sign = null);

    public record Supplier(int Id, string? Code = null, string? Name = null, string? Description = null);

    public class MonthEndOutstandingPayment
    {
        public Supplier Supplier { get; init; } = default!;
        public Currency Currency { get; init; } = default!;
        public decimal Cost { get; init; }
        public decimal CostOriginal { get; init; }
        public decimal Outstanding { get; init; }
    }
```

So what I'm trying to do is to unflatten the output from my stored procedure, using the supSupplierID and supName fields to create an instance of Supplier, and the CurrencyID and curCode fields to create an instance of Currency.  I can do this with a Class Handler (as per my previous message) but I wanted to know if there's a way I could create a Property Handler which refers to multiple fields.

**Comment by mikependon** [comment]
Thanks for elaborating, you did it right. This can only be done via ClassHandler and there is no otherway for now since RepoDB is not supporting a hydration to the entity/model properties that is of type 'class'.

**Comment by pmarflee** [comment]
Thanks, that's clarified things for me
