### ISSUE TITLE
实体继承基类的主键以及字段，无法在派生类中体现？

### ISSUE THREAD

**Issue by wangfei9999** [mikependon/RepoDb#986]
继承时，主键字段，在批量删除时，会出现报错 The declaring type of the property is not equal to the target entity type.

![image](https://user-images.githubusercontent.com/73685882/142517203-81a3b474-fdcc-4799-8440-06d0f71cde9c.png)
![image](https://user-images.githubusercontent.com/73685882/142517245-8364cfed-a0b7-4d40-86ef-8f94ec3ca8f2.png)

**Comment by mikependon** [comment]
应该支持。 您能否具体说明发生错误时调用的方法？
另外，您可以分享堆栈跟踪吗？

It should be supported. Would you be specific to which method did you call that the error has occurred?
Also, can you share the stack trace?

**Comment by wangfei9999** [comment]
您好，非常感谢您能够及时回复我的提问，谢谢！
1.如下图所示为异常：

2.具体异常堆栈内容：
&nbsp; System.InvalidOperationException
&nbsp; HResult=0x80131509
&nbsp; Message=The declaring type of the property is not equal to the target entity type.
&nbsp; Source=RepoDb
&nbsp; StackTrace:
&nbsp; &nbsp;在 RepoDb.ClassExpression.GetPropertyValuesCache`2.Guard(ClassProperty property)
&nbsp; &nbsp;在 RepoDb.ClassExpression.GetPropertyValuesCache`2.<Do&gt;d__3.MoveNext()
&nbsp; &nbsp;在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
&nbsp; &nbsp;在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
&nbsp; &nbsp;在 RepoDb.Extensions.EnumerableExtension.AsList[T](IEnumerable`1 value)
&nbsp; &nbsp;在 RepoDb.DbConnectionExtension.DeleteAll[TEntity](IDbConnection connection, IEnumerable`1 entities, String hints, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
&nbsp; &nbsp;在 RepoDb.DbRepository`1.DeleteAll[TEntity](IEnumerable`1 entities, String hints, IDbTransaction transaction)
&nbsp; &nbsp;在 Wf.Core.RepoDb.Repositorys.SqlServerRepository.Delete[TEntity](List`1 entity) 在 E:\2021\dotnet\wf\Wf.Core.RepoDb\Repositorys\SqlServerRepository.cs 中: 第 79 行
&nbsp; &nbsp;在 Wf.Application.WebApi.Controllers.WeatherForecastController.Get() 在 E:\2021\dotnet\wf\Wf.Application.WebApi\Controllers\WeatherForecastController.cs 中: 第 62 行


&nbsp; 此异常最初是在此调用堆栈中引发的:&nbsp;
&nbsp; &nbsp; [外部代码]
&nbsp; &nbsp; Wf.Core.RepoDb.Repositorys.SqlServerRepository.Delete<TEntity&gt;(System.Collections.Generic.List<TEntity&gt;) (位于 SqlServerRepository.cs 中)
&nbsp; &nbsp; Wf.Application.WebApi.Controllers.WeatherForecastController.Get() (位于 WeatherForecastController.cs 中)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mikependon/RepoDB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikependon/RepoDB] 实体继承基类的主键以及字段，无法在派生类中体现？ (Issue #986)





 
应该支持。 您能否具体说明发生错误时调用的方法？
 另外，您可以分享堆栈跟踪吗？
 
It should be supported. Would you be specific to which method did you call that the error has occurred?
 Also, can you share the stack trace?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wangfei9999** [comment]
您好，非常感谢您能够及时回复我的提问，谢谢！
1.如下图所示为异常：

2.具体异常堆栈内容：
&nbsp; System.InvalidOperationException
&nbsp; HResult=0x80131509
&nbsp; Message=The declaring type of the property is not equal to the target entity type.
&nbsp; Source=RepoDb
&nbsp; StackTrace:
&nbsp; &nbsp;在 RepoDb.ClassExpression.GetPropertyValuesCache`2.Guard(ClassProperty property)
&nbsp; &nbsp;在 RepoDb.ClassExpression.GetPropertyValuesCache`2.<Do&gt;d__3.MoveNext()
&nbsp; &nbsp;在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
&nbsp; &nbsp;在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
&nbsp; &nbsp;在 RepoDb.Extensions.EnumerableExtension.AsList[T](IEnumerable`1 value)
&nbsp; &nbsp;在 RepoDb.DbConnectionExtension.DeleteAll[TEntity](IDbConnection connection, IEnumerable`1 entities, String hints, Nullable`1 commandTimeout, IDbTransaction transaction, ITrace trace, IStatementBuilder statementBuilder)
&nbsp; &nbsp;在 RepoDb.DbRepository`1.DeleteAll[TEntity](IEnumerable`1 entities, String hints, IDbTransaction transaction)
&nbsp; &nbsp;在 Wf.Core.RepoDb.Repositorys.SqlServerRepository.Delete[TEntity](List`1 entity) 在 E:\2021\dotnet\wf\Wf.Core.RepoDb\Repositorys\SqlServerRepository.cs 中: 第 79 行
&nbsp; &nbsp;在 Wf.Application.WebApi.Controllers.WeatherForecastController.Get() 在 E:\2021\dotnet\wf\Wf.Application.WebApi\Controllers\WeatherForecastController.cs 中: 第 62 行


&nbsp; 此异常最初是在此调用堆栈中引发的: 
&nbsp; &nbsp; [外部代码]
&nbsp; &nbsp; Wf.Core.RepoDb.Repositorys.SqlServerRepository.Delete<TEntity&gt;(System.Collections.Generic.List<TEntity&gt;) (位于 SqlServerRepository.cs 中)
&nbsp; &nbsp; Wf.Application.WebApi.Controllers.WeatherForecastController.Get() (位于 WeatherForecastController.cs 中)





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "mikependon/RepoDB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mikependon/RepoDB] 实体继承基类的主键以及字段，无法在派生类中体现？ (Issue #986)





 
应该支持。 您能否具体说明发生错误时调用的方法？
 另外，您可以分享堆栈跟踪吗？
 
It should be supported. Would you be specific to which method did you call that the error has occurred?
 Also, can you share the stack trace?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mikependon** [comment]
这次真是万分感谢。 我们会研究一下。
Thank you for this. We will look into it.

**Comment by mikependon** [comment]
Related to #1011. The fix will be available on the next version of the core library (>= RepoDb v1.12.10-beta5
