### ISSUE TITLE
Microsoft.Data.Sqlite Version

### ISSUE THREAD

**Issue by fercala** [mikependon/RepoDb#995]
Hello,
On Microsoft.Data.Sqlite 6.0.0 Microsoft add Pooling and new features.
Are you planning to upgrate the version of Microsoft.Data.Sqlite to 6.0?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlite.sqliteconnectionstringbuilder?view=msdata-sqlite-6.0.0

Thanks & Regards.

**Comment by mikependon** [comment]
Yes, we can do this on the next release very soon. :smile:

**Comment by mikependon** [comment]
The fix will be avalable on v1.0.2.
