### ISSUE TITLE
Question: Usage with F# Query Expression

### ISSUE THREAD

**Issue by shanoaice** [mikependon/RepoDb#999]
I am very curious about whether I can use F#'s Query Expression feature with RepoDB. Query expression plays very well with SQL databases, but after some digging in the codebase, I am not sure if the return type implements `IQueryable<T>` which is required by the query expression.

**Comment by mikependon** [comment]
@shanoaice - if your consumers' code are expecting the `IQueryable` interface then it is not supported by RepoDB, we suggest to utilize the `EntityFramework` for that. RepoDB is using the `IEnumerable` as an abstraction in all areas.

**Comment by xperiandri** [comment]
He meant the use of F# Quotation type in place of C# Expression type
